/*
 * generated by Xtext 2.29.0
 */
grammar InternalCocktails;

options {
	superClass=AbstractInternalContentAssistParser;
}

@lexer::header {
package org.xtext.example.mydsl.ide.contentassist.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.Lexer;
}

@parser::header {
package org.xtext.example.mydsl.ide.contentassist.antlr.internal;

import java.io.InputStream;
import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.DFA;
import org.xtext.example.mydsl.services.CocktailsGrammarAccess;

}
@parser::members {
	private CocktailsGrammarAccess grammarAccess;

	public void setGrammarAccess(CocktailsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}

	@Override
	protected Grammar getGrammar() {
		return grammarAccess.getGrammar();
	}

	@Override
	protected String getValueForTokenName(String tokenName) {
		return tokenName;
	}
}

// Entry rule entryRuleOrder
entryRuleOrder
:
{ before(grammarAccess.getOrderRule()); }
	 ruleOrder
{ after(grammarAccess.getOrderRule()); } 
	 EOF 
;

// Rule Order
ruleOrder 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getOrderAccess().getInstructionsAssignment()); }
		(rule__Order__InstructionsAssignment)*
		{ after(grammarAccess.getOrderAccess().getInstructionsAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleInstruction
entryRuleInstruction
:
{ before(grammarAccess.getInstructionRule()); }
	 ruleInstruction
{ after(grammarAccess.getInstructionRule()); } 
	 EOF 
;

// Rule Instruction
ruleInstruction 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getInstructionAccess().getAlternatives()); }
		(rule__Instruction__Alternatives)
		{ after(grammarAccess.getInstructionAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleAddIngredient
entryRuleAddIngredient
:
{ before(grammarAccess.getAddIngredientRule()); }
	 ruleAddIngredient
{ after(grammarAccess.getAddIngredientRule()); } 
	 EOF 
;

// Rule AddIngredient
ruleAddIngredient 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getAddIngredientAccess().getGroup()); }
		(rule__AddIngredient__Group__0)
		{ after(grammarAccess.getAddIngredientAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleAddFixedIngredient
entryRuleAddFixedIngredient
:
{ before(grammarAccess.getAddFixedIngredientRule()); }
	 ruleAddFixedIngredient
{ after(grammarAccess.getAddFixedIngredientRule()); } 
	 EOF 
;

// Rule AddFixedIngredient
ruleAddFixedIngredient 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getAddFixedIngredientAccess().getGroup()); }
		(rule__AddFixedIngredient__Group__0)
		{ after(grammarAccess.getAddFixedIngredientAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleFancyStatement
entryRuleFancyStatement
:
{ before(grammarAccess.getFancyStatementRule()); }
	 ruleFancyStatement
{ after(grammarAccess.getFancyStatementRule()); } 
	 EOF 
;

// Rule FancyStatement
ruleFancyStatement 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getFancyStatementAccess().getGroup()); }
		(rule__FancyStatement__Group__0)
		{ after(grammarAccess.getFancyStatementAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleAddIce
entryRuleAddIce
:
{ before(grammarAccess.getAddIceRule()); }
	 ruleAddIce
{ after(grammarAccess.getAddIceRule()); } 
	 EOF 
;

// Rule AddIce
ruleAddIce 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getAddIceAccess().getGroup()); }
		(rule__AddIce__Group__0)
		{ after(grammarAccess.getAddIceAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleMuddleStatement
entryRuleMuddleStatement
:
{ before(grammarAccess.getMuddleStatementRule()); }
	 ruleMuddleStatement
{ after(grammarAccess.getMuddleStatementRule()); } 
	 EOF 
;

// Rule MuddleStatement
ruleMuddleStatement 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getMuddleStatementAccess().getGroup()); }
		(rule__MuddleStatement__Group__0)
		{ after(grammarAccess.getMuddleStatementAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleAddDecoration
entryRuleAddDecoration
:
{ before(grammarAccess.getAddDecorationRule()); }
	 ruleAddDecoration
{ after(grammarAccess.getAddDecorationRule()); } 
	 EOF 
;

// Rule AddDecoration
ruleAddDecoration 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getAddDecorationAccess().getGroup()); }
		(rule__AddDecoration__Group__0)
		{ after(grammarAccess.getAddDecorationAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleMakeStatement
entryRuleMakeStatement
:
{ before(grammarAccess.getMakeStatementRule()); }
	 ruleMakeStatement
{ after(grammarAccess.getMakeStatementRule()); } 
	 EOF 
;

// Rule MakeStatement
ruleMakeStatement 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getMakeStatementAccess().getGroup()); }
		(rule__MakeStatement__Group__0)
		{ after(grammarAccess.getMakeStatementAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleAddition
entryRuleAddition
:
{ before(grammarAccess.getAdditionRule()); }
	 ruleAddition
{ after(grammarAccess.getAdditionRule()); } 
	 EOF 
;

// Rule Addition
ruleAddition 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getAdditionAccess().getGroup()); }
		(rule__Addition__Group__0)
		{ after(grammarAccess.getAdditionAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleMultiplication
entryRuleMultiplication
:
{ before(grammarAccess.getMultiplicationRule()); }
	 ruleMultiplication
{ after(grammarAccess.getMultiplicationRule()); } 
	 EOF 
;

// Rule Multiplication
ruleMultiplication 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getMultiplicationAccess().getGroup()); }
		(rule__Multiplication__Group__0)
		{ after(grammarAccess.getMultiplicationAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRulePrimaryExpression
entryRulePrimaryExpression
:
{ before(grammarAccess.getPrimaryExpressionRule()); }
	 rulePrimaryExpression
{ after(grammarAccess.getPrimaryExpressionRule()); } 
	 EOF 
;

// Rule PrimaryExpression
rulePrimaryExpression 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getPrimaryExpressionAccess().getAlternatives()); }
		(rule__PrimaryExpression__Alternatives)
		{ after(grammarAccess.getPrimaryExpressionAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleIntLiteral
entryRuleIntLiteral
:
{ before(grammarAccess.getIntLiteralRule()); }
	 ruleIntLiteral
{ after(grammarAccess.getIntLiteralRule()); } 
	 EOF 
;

// Rule IntLiteral
ruleIntLiteral 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getIntLiteralAccess().getValAssignment()); }
		(rule__IntLiteral__ValAssignment)
		{ after(grammarAccess.getIntLiteralAccess().getValAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleVariableDeclaration
entryRuleVariableDeclaration
:
{ before(grammarAccess.getVariableDeclarationRule()); }
	 ruleVariableDeclaration
{ after(grammarAccess.getVariableDeclarationRule()); } 
	 EOF 
;

// Rule VariableDeclaration
ruleVariableDeclaration 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getVariableDeclarationAccess().getGroup()); }
		(rule__VariableDeclaration__Group__0)
		{ after(grammarAccess.getVariableDeclarationAccess().getGroup()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Entry rule entryRuleIntVarExpression
entryRuleIntVarExpression
:
{ before(grammarAccess.getIntVarExpressionRule()); }
	 ruleIntVarExpression
{ after(grammarAccess.getIntVarExpressionRule()); } 
	 EOF 
;

// Rule IntVarExpression
ruleIntVarExpression 
	@init {
		int stackSize = keepStackSize();
	}
	:
	(
		{ before(grammarAccess.getIntVarExpressionAccess().getVarAssignment()); }
		(rule__IntVarExpression__VarAssignment)
		{ after(grammarAccess.getIntVarExpressionAccess().getVarAssignment()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Rule FancyMakeStatement
ruleFancyMakeStatement
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getFancyMakeStatementAccess().getAlternatives()); }
		(rule__FancyMakeStatement__Alternatives)
		{ after(grammarAccess.getFancyMakeStatementAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Rule IceStatement
ruleIceStatement
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getIceStatementAccess().getAlternatives()); }
		(rule__IceStatement__Alternatives)
		{ after(grammarAccess.getIceStatementAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Rule FruitStatement
ruleFruitStatement
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getFruitStatementAccess().getAlternatives()); }
		(rule__FruitStatement__Alternatives)
		{ after(grammarAccess.getFruitStatementAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Rule DecorationStatement
ruleDecorationStatement
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDecorationStatementAccess().getAlternatives()); }
		(rule__DecorationStatement__Alternatives)
		{ after(grammarAccess.getDecorationStatementAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

// Rule MakeCommand
ruleMakeCommand
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMakeCommandAccess().getAlternatives()); }
		(rule__MakeCommand__Alternatives)
		{ after(grammarAccess.getMakeCommandAccess().getAlternatives()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Instruction__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getInstructionAccess().getAddIngredientParserRuleCall_0()); }
		ruleAddIngredient
		{ after(grammarAccess.getInstructionAccess().getAddIngredientParserRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getInstructionAccess().getAddFixedIngredientParserRuleCall_1()); }
		ruleAddFixedIngredient
		{ after(grammarAccess.getInstructionAccess().getAddFixedIngredientParserRuleCall_1()); }
	)
	|
	(
		{ before(grammarAccess.getInstructionAccess().getFancyStatementParserRuleCall_2()); }
		ruleFancyStatement
		{ after(grammarAccess.getInstructionAccess().getFancyStatementParserRuleCall_2()); }
	)
	|
	(
		{ before(grammarAccess.getInstructionAccess().getAddIceParserRuleCall_3()); }
		ruleAddIce
		{ after(grammarAccess.getInstructionAccess().getAddIceParserRuleCall_3()); }
	)
	|
	(
		{ before(grammarAccess.getInstructionAccess().getMuddleStatementParserRuleCall_4()); }
		ruleMuddleStatement
		{ after(grammarAccess.getInstructionAccess().getMuddleStatementParserRuleCall_4()); }
	)
	|
	(
		{ before(grammarAccess.getInstructionAccess().getAddDecorationParserRuleCall_5()); }
		ruleAddDecoration
		{ after(grammarAccess.getInstructionAccess().getAddDecorationParserRuleCall_5()); }
	)
	|
	(
		{ before(grammarAccess.getInstructionAccess().getMakeStatementParserRuleCall_6()); }
		ruleMakeStatement
		{ after(grammarAccess.getInstructionAccess().getMakeStatementParserRuleCall_6()); }
	)
	|
	(
		{ before(grammarAccess.getInstructionAccess().getVariableDeclarationParserRuleCall_7()); }
		ruleVariableDeclaration
		{ after(grammarAccess.getInstructionAccess().getVariableDeclarationParserRuleCall_7()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Addition__OperatorAlternatives_1_1_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAdditionAccess().getOperatorPlusSignKeyword_1_1_0_0()); }
		'+'
		{ after(grammarAccess.getAdditionAccess().getOperatorPlusSignKeyword_1_1_0_0()); }
	)
	|
	(
		{ before(grammarAccess.getAdditionAccess().getOperatorHyphenMinusKeyword_1_1_0_1()); }
		'-'
		{ after(grammarAccess.getAdditionAccess().getOperatorHyphenMinusKeyword_1_1_0_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Multiplication__OperatorAlternatives_1_1_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMultiplicationAccess().getOperatorAsteriskKeyword_1_1_0_0()); }
		'*'
		{ after(grammarAccess.getMultiplicationAccess().getOperatorAsteriskKeyword_1_1_0_0()); }
	)
	|
	(
		{ before(grammarAccess.getMultiplicationAccess().getOperatorSolidusKeyword_1_1_0_1()); }
		'/'
		{ after(grammarAccess.getMultiplicationAccess().getOperatorSolidusKeyword_1_1_0_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__PrimaryExpression__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getPrimaryExpressionAccess().getIntLiteralParserRuleCall_0()); }
		ruleIntLiteral
		{ after(grammarAccess.getPrimaryExpressionAccess().getIntLiteralParserRuleCall_0()); }
	)
	|
	(
		{ before(grammarAccess.getPrimaryExpressionAccess().getIntVarExpressionParserRuleCall_1()); }
		ruleIntVarExpression
		{ after(grammarAccess.getPrimaryExpressionAccess().getIntVarExpressionParserRuleCall_1()); }
	)
	|
	(
		{ before(grammarAccess.getPrimaryExpressionAccess().getGroup_2()); }
		(rule__PrimaryExpression__Group_2__0)
		{ after(grammarAccess.getPrimaryExpressionAccess().getGroup_2()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__FancyMakeStatement__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getFancyMakeStatementAccess().getLighterEnumLiteralDeclaration_0()); }
		('lighter')
		{ after(grammarAccess.getFancyMakeStatementAccess().getLighterEnumLiteralDeclaration_0()); }
	)
	|
	(
		{ before(grammarAccess.getFancyMakeStatementAccess().getCo2EnumLiteralDeclaration_1()); }
		('co2')
		{ after(grammarAccess.getFancyMakeStatementAccess().getCo2EnumLiteralDeclaration_1()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__IceStatement__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getIceStatementAccess().getCubeEnumLiteralDeclaration_0()); }
		('cube')
		{ after(grammarAccess.getIceStatementAccess().getCubeEnumLiteralDeclaration_0()); }
	)
	|
	(
		{ before(grammarAccess.getIceStatementAccess().getCrushEnumLiteralDeclaration_1()); }
		('crush')
		{ after(grammarAccess.getIceStatementAccess().getCrushEnumLiteralDeclaration_1()); }
	)
	|
	(
		{ before(grammarAccess.getIceStatementAccess().getShaveEnumLiteralDeclaration_2()); }
		('shave')
		{ after(grammarAccess.getIceStatementAccess().getShaveEnumLiteralDeclaration_2()); }
	)
	|
	(
		{ before(grammarAccess.getIceStatementAccess().getBlockEnumLiteralDeclaration_3()); }
		('block')
		{ after(grammarAccess.getIceStatementAccess().getBlockEnumLiteralDeclaration_3()); }
	)
	|
	(
		{ before(grammarAccess.getIceStatementAccess().getBallEnumLiteralDeclaration_4()); }
		('ball')
		{ after(grammarAccess.getIceStatementAccess().getBallEnumLiteralDeclaration_4()); }
	)
	|
	(
		{ before(grammarAccess.getIceStatementAccess().getConeEnumLiteralDeclaration_5()); }
		('cone')
		{ after(grammarAccess.getIceStatementAccess().getConeEnumLiteralDeclaration_5()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__FruitStatement__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getFruitStatementAccess().getLimeEnumLiteralDeclaration_0()); }
		('lime')
		{ after(grammarAccess.getFruitStatementAccess().getLimeEnumLiteralDeclaration_0()); }
	)
	|
	(
		{ before(grammarAccess.getFruitStatementAccess().getLemonEnumLiteralDeclaration_1()); }
		('lemon')
		{ after(grammarAccess.getFruitStatementAccess().getLemonEnumLiteralDeclaration_1()); }
	)
	|
	(
		{ before(grammarAccess.getFruitStatementAccess().getOrangeEnumLiteralDeclaration_2()); }
		('orange')
		{ after(grammarAccess.getFruitStatementAccess().getOrangeEnumLiteralDeclaration_2()); }
	)
	|
	(
		{ before(grammarAccess.getFruitStatementAccess().getGrapefruitEnumLiteralDeclaration_3()); }
		('grapefruit')
		{ after(grammarAccess.getFruitStatementAccess().getGrapefruitEnumLiteralDeclaration_3()); }
	)
	|
	(
		{ before(grammarAccess.getFruitStatementAccess().getPineappleEnumLiteralDeclaration_4()); }
		('pineapple')
		{ after(grammarAccess.getFruitStatementAccess().getPineappleEnumLiteralDeclaration_4()); }
	)
	|
	(
		{ before(grammarAccess.getFruitStatementAccess().getMangoEnumLiteralDeclaration_5()); }
		('mango')
		{ after(grammarAccess.getFruitStatementAccess().getMangoEnumLiteralDeclaration_5()); }
	)
	|
	(
		{ before(grammarAccess.getFruitStatementAccess().getKiwiEnumLiteralDeclaration_6()); }
		('kiwi')
		{ after(grammarAccess.getFruitStatementAccess().getKiwiEnumLiteralDeclaration_6()); }
	)
	|
	(
		{ before(grammarAccess.getFruitStatementAccess().getStrawberryEnumLiteralDeclaration_7()); }
		('strawberry')
		{ after(grammarAccess.getFruitStatementAccess().getStrawberryEnumLiteralDeclaration_7()); }
	)
	|
	(
		{ before(grammarAccess.getFruitStatementAccess().getBlueberryEnumLiteralDeclaration_8()); }
		('blueberry')
		{ after(grammarAccess.getFruitStatementAccess().getBlueberryEnumLiteralDeclaration_8()); }
	)
	|
	(
		{ before(grammarAccess.getFruitStatementAccess().getRaspberryEnumLiteralDeclaration_9()); }
		('raspberry')
		{ after(grammarAccess.getFruitStatementAccess().getRaspberryEnumLiteralDeclaration_9()); }
	)
	|
	(
		{ before(grammarAccess.getFruitStatementAccess().getBlackberryEnumLiteralDeclaration_10()); }
		('blackberry')
		{ after(grammarAccess.getFruitStatementAccess().getBlackberryEnumLiteralDeclaration_10()); }
	)
	|
	(
		{ before(grammarAccess.getFruitStatementAccess().getCherryEnumLiteralDeclaration_11()); }
		('cherry')
		{ after(grammarAccess.getFruitStatementAccess().getCherryEnumLiteralDeclaration_11()); }
	)
	|
	(
		{ before(grammarAccess.getFruitStatementAccess().getPeachEnumLiteralDeclaration_12()); }
		('peach')
		{ after(grammarAccess.getFruitStatementAccess().getPeachEnumLiteralDeclaration_12()); }
	)
	|
	(
		{ before(grammarAccess.getFruitStatementAccess().getPlumEnumLiteralDeclaration_13()); }
		('plum')
		{ after(grammarAccess.getFruitStatementAccess().getPlumEnumLiteralDeclaration_13()); }
	)
	|
	(
		{ before(grammarAccess.getFruitStatementAccess().getWatermelonEnumLiteralDeclaration_14()); }
		('watermelon')
		{ after(grammarAccess.getFruitStatementAccess().getWatermelonEnumLiteralDeclaration_14()); }
	)
	|
	(
		{ before(grammarAccess.getFruitStatementAccess().getCucumberEnumLiteralDeclaration_15()); }
		('cucumber')
		{ after(grammarAccess.getFruitStatementAccess().getCucumberEnumLiteralDeclaration_15()); }
	)
	|
	(
		{ before(grammarAccess.getFruitStatementAccess().getMintEnumLiteralDeclaration_16()); }
		('mint')
		{ after(grammarAccess.getFruitStatementAccess().getMintEnumLiteralDeclaration_16()); }
	)
	|
	(
		{ before(grammarAccess.getFruitStatementAccess().getBasilEnumLiteralDeclaration_17()); }
		('basil')
		{ after(grammarAccess.getFruitStatementAccess().getBasilEnumLiteralDeclaration_17()); }
	)
	|
	(
		{ before(grammarAccess.getFruitStatementAccess().getThymeEnumLiteralDeclaration_18()); }
		('thyme')
		{ after(grammarAccess.getFruitStatementAccess().getThymeEnumLiteralDeclaration_18()); }
	)
	|
	(
		{ before(grammarAccess.getFruitStatementAccess().getGingerEnumLiteralDeclaration_19()); }
		('ginger')
		{ after(grammarAccess.getFruitStatementAccess().getGingerEnumLiteralDeclaration_19()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__DecorationStatement__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getDecorationStatementAccess().getOrangeEnumLiteralDeclaration_0()); }
		('orange')
		{ after(grammarAccess.getDecorationStatementAccess().getOrangeEnumLiteralDeclaration_0()); }
	)
	|
	(
		{ before(grammarAccess.getDecorationStatementAccess().getLemonEnumLiteralDeclaration_1()); }
		('lemon')
		{ after(grammarAccess.getDecorationStatementAccess().getLemonEnumLiteralDeclaration_1()); }
	)
	|
	(
		{ before(grammarAccess.getDecorationStatementAccess().getLimeEnumLiteralDeclaration_2()); }
		('lime')
		{ after(grammarAccess.getDecorationStatementAccess().getLimeEnumLiteralDeclaration_2()); }
	)
	|
	(
		{ before(grammarAccess.getDecorationStatementAccess().getOliveEnumLiteralDeclaration_3()); }
		('olive')
		{ after(grammarAccess.getDecorationStatementAccess().getOliveEnumLiteralDeclaration_3()); }
	)
	|
	(
		{ before(grammarAccess.getDecorationStatementAccess().getCherryEnumLiteralDeclaration_4()); }
		('cherry')
		{ after(grammarAccess.getDecorationStatementAccess().getCherryEnumLiteralDeclaration_4()); }
	)
	|
	(
		{ before(grammarAccess.getDecorationStatementAccess().getMintEnumLiteralDeclaration_5()); }
		('mint')
		{ after(grammarAccess.getDecorationStatementAccess().getMintEnumLiteralDeclaration_5()); }
	)
	|
	(
		{ before(grammarAccess.getDecorationStatementAccess().getRoseEnumLiteralDeclaration_6()); }
		('rose')
		{ after(grammarAccess.getDecorationStatementAccess().getRoseEnumLiteralDeclaration_6()); }
	)
	|
	(
		{ before(grammarAccess.getDecorationStatementAccess().getCinnamonEnumLiteralDeclaration_7()); }
		('cinnamon')
		{ after(grammarAccess.getDecorationStatementAccess().getCinnamonEnumLiteralDeclaration_7()); }
	)
	|
	(
		{ before(grammarAccess.getDecorationStatementAccess().getMangoEnumLiteralDeclaration_8()); }
		('mango')
		{ after(grammarAccess.getDecorationStatementAccess().getMangoEnumLiteralDeclaration_8()); }
	)
	|
	(
		{ before(grammarAccess.getDecorationStatementAccess().getGrapefruitEnumLiteralDeclaration_9()); }
		('grapefruit')
		{ after(grammarAccess.getDecorationStatementAccess().getGrapefruitEnumLiteralDeclaration_9()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__MakeCommand__Alternatives
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMakeCommandAccess().getStirEnumLiteralDeclaration_0()); }
		('stir')
		{ after(grammarAccess.getMakeCommandAccess().getStirEnumLiteralDeclaration_0()); }
	)
	|
	(
		{ before(grammarAccess.getMakeCommandAccess().getShakeEnumLiteralDeclaration_1()); }
		('shake')
		{ after(grammarAccess.getMakeCommandAccess().getShakeEnumLiteralDeclaration_1()); }
	)
	|
	(
		{ before(grammarAccess.getMakeCommandAccess().getBlendEnumLiteralDeclaration_2()); }
		('blend')
		{ after(grammarAccess.getMakeCommandAccess().getBlendEnumLiteralDeclaration_2()); }
	)
	|
	(
		{ before(grammarAccess.getMakeCommandAccess().getFilterEnumLiteralDeclaration_3()); }
		('filter')
		{ after(grammarAccess.getMakeCommandAccess().getFilterEnumLiteralDeclaration_3()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIngredient__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AddIngredient__Group__0__Impl
	rule__AddIngredient__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIngredient__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAddIngredientAccess().getAddIKeyword_0()); }
	'addI'
	{ after(grammarAccess.getAddIngredientAccess().getAddIKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIngredient__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AddIngredient__Group__1__Impl
	rule__AddIngredient__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIngredient__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAddIngredientAccess().getNameAssignment_1()); }
	(rule__AddIngredient__NameAssignment_1)
	{ after(grammarAccess.getAddIngredientAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIngredient__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AddIngredient__Group__2__Impl
	rule__AddIngredient__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIngredient__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAddIngredientAccess().getColonKeyword_2()); }
	':'
	{ after(grammarAccess.getAddIngredientAccess().getColonKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIngredient__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AddIngredient__Group__3__Impl
	rule__AddIngredient__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIngredient__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAddIngredientAccess().getAmountAssignment_3()); }
	(rule__AddIngredient__AmountAssignment_3)
	{ after(grammarAccess.getAddIngredientAccess().getAmountAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIngredient__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AddIngredient__Group__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIngredient__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAddIngredientAccess().getMlKeyword_4()); }
	'ml'
	{ after(grammarAccess.getAddIngredientAccess().getMlKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__AddFixedIngredient__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AddFixedIngredient__Group__0__Impl
	rule__AddFixedIngredient__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__AddFixedIngredient__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAddFixedIngredientAccess().getAddFKeyword_0()); }
	'addF'
	{ after(grammarAccess.getAddFixedIngredientAccess().getAddFKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddFixedIngredient__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AddFixedIngredient__Group__1__Impl
	rule__AddFixedIngredient__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__AddFixedIngredient__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAddFixedIngredientAccess().getNameAssignment_1()); }
	(rule__AddFixedIngredient__NameAssignment_1)
	{ after(grammarAccess.getAddFixedIngredientAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddFixedIngredient__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AddFixedIngredient__Group__2__Impl
	rule__AddFixedIngredient__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__AddFixedIngredient__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAddFixedIngredientAccess().getColonKeyword_2()); }
	':'
	{ after(grammarAccess.getAddFixedIngredientAccess().getColonKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddFixedIngredient__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AddFixedIngredient__Group__3__Impl
	rule__AddFixedIngredient__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__AddFixedIngredient__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAddFixedIngredientAccess().getAmountAssignment_3()); }
	(rule__AddFixedIngredient__AmountAssignment_3)
	{ after(grammarAccess.getAddFixedIngredientAccess().getAmountAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddFixedIngredient__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AddFixedIngredient__Group__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__AddFixedIngredient__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAddFixedIngredientAccess().getGKeyword_4()); }
	'g'
	{ after(grammarAccess.getAddFixedIngredientAccess().getGKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__FancyStatement__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__FancyStatement__Group__0__Impl
	rule__FancyStatement__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__FancyStatement__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getFancyStatementAccess().getUseKeyword_0()); }
	'use'
	{ after(grammarAccess.getFancyStatementAccess().getUseKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__FancyStatement__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__FancyStatement__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__FancyStatement__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getFancyStatementAccess().getFcommandAssignment_1()); }
	(rule__FancyStatement__FcommandAssignment_1)
	{ after(grammarAccess.getFancyStatementAccess().getFcommandAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__AddIce__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AddIce__Group__0__Impl
	rule__AddIce__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIce__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAddIceAccess().getAddIcKeyword_0()); }
	'addIc'
	{ after(grammarAccess.getAddIceAccess().getAddIcKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIce__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AddIce__Group__1__Impl
	rule__AddIce__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIce__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAddIceAccess().getIceAssignment_1()); }
	(rule__AddIce__IceAssignment_1)
	{ after(grammarAccess.getAddIceAccess().getIceAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIce__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AddIce__Group__2__Impl
	rule__AddIce__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIce__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAddIceAccess().getColonKeyword_2()); }
	':'
	{ after(grammarAccess.getAddIceAccess().getColonKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIce__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AddIce__Group__3__Impl
	rule__AddIce__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIce__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAddIceAccess().getOunceAssignment_3()); }
	(rule__AddIce__OunceAssignment_3)
	{ after(grammarAccess.getAddIceAccess().getOunceAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIce__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AddIce__Group__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIce__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAddIceAccess().getOunceKeyword_4()); }
	'ounce'
	{ after(grammarAccess.getAddIceAccess().getOunceKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__MuddleStatement__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MuddleStatement__Group__0__Impl
	rule__MuddleStatement__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__MuddleStatement__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMuddleStatementAccess().getMudKeyword_0()); }
	'mud'
	{ after(grammarAccess.getMuddleStatementAccess().getMudKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__MuddleStatement__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MuddleStatement__Group__1__Impl
	rule__MuddleStatement__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__MuddleStatement__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMuddleStatementAccess().getMudFruitAssignment_1()); }
	(rule__MuddleStatement__MudFruitAssignment_1)*
	{ after(grammarAccess.getMuddleStatementAccess().getMudFruitAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__MuddleStatement__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MuddleStatement__Group__2__Impl
	rule__MuddleStatement__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__MuddleStatement__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMuddleStatementAccess().getColonKeyword_2()); }
	':'
	{ after(grammarAccess.getMuddleStatementAccess().getColonKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__MuddleStatement__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MuddleStatement__Group__3__Impl
	rule__MuddleStatement__Group__4
;
finally {
	restoreStackSize(stackSize);
}

rule__MuddleStatement__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMuddleStatementAccess().getMtimesAssignment_3()); }
	(rule__MuddleStatement__MtimesAssignment_3)
	{ after(grammarAccess.getMuddleStatementAccess().getMtimesAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__MuddleStatement__Group__4
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MuddleStatement__Group__4__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__MuddleStatement__Group__4__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMuddleStatementAccess().getTimesKeyword_4()); }
	'times'
	{ after(grammarAccess.getMuddleStatementAccess().getTimesKeyword_4()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__AddDecoration__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AddDecoration__Group__0__Impl
	rule__AddDecoration__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__AddDecoration__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAddDecorationAccess().getAddDKeyword_0()); }
	'addD'
	{ after(grammarAccess.getAddDecorationAccess().getAddDKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddDecoration__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AddDecoration__Group__1__Impl
	rule__AddDecoration__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__AddDecoration__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAddDecorationAccess().getDecorationAssignment_1()); }
	(rule__AddDecoration__DecorationAssignment_1)
	{ after(grammarAccess.getAddDecorationAccess().getDecorationAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddDecoration__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AddDecoration__Group__2__Impl
	rule__AddDecoration__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__AddDecoration__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAddDecorationAccess().getSliceAssignment_2()); }
	(rule__AddDecoration__SliceAssignment_2)
	{ after(grammarAccess.getAddDecorationAccess().getSliceAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddDecoration__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__AddDecoration__Group__3__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__AddDecoration__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAddDecorationAccess().getSlicesKeyword_3()); }
	'slices'
	{ after(grammarAccess.getAddDecorationAccess().getSlicesKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__MakeStatement__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MakeStatement__Group__0__Impl
	rule__MakeStatement__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__MakeStatement__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMakeStatementAccess().getMakeAssignment_0()); }
	(rule__MakeStatement__MakeAssignment_0)
	{ after(grammarAccess.getMakeStatementAccess().getMakeAssignment_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__MakeStatement__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MakeStatement__Group__1__Impl
	rule__MakeStatement__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__MakeStatement__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMakeStatementAccess().getColonKeyword_1()); }
	':'
	{ after(grammarAccess.getMakeStatementAccess().getColonKeyword_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__MakeStatement__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MakeStatement__Group__2__Impl
	rule__MakeStatement__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__MakeStatement__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMakeStatementAccess().getTimeAssignment_2()); }
	(rule__MakeStatement__TimeAssignment_2)
	{ after(grammarAccess.getMakeStatementAccess().getTimeAssignment_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__MakeStatement__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__MakeStatement__Group__3__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__MakeStatement__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMakeStatementAccess().getSecondsKeyword_3()); }
	'seconds'
	{ after(grammarAccess.getMakeStatementAccess().getSecondsKeyword_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Addition__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Addition__Group__0__Impl
	rule__Addition__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Addition__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAdditionAccess().getMultiplicationParserRuleCall_0()); }
	ruleMultiplication
	{ after(grammarAccess.getAdditionAccess().getMultiplicationParserRuleCall_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Addition__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Addition__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Addition__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAdditionAccess().getGroup_1()); }
	(rule__Addition__Group_1__0)*
	{ after(grammarAccess.getAdditionAccess().getGroup_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Addition__Group_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Addition__Group_1__0__Impl
	rule__Addition__Group_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Addition__Group_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAdditionAccess().getAdditionLeftAction_1_0()); }
	()
	{ after(grammarAccess.getAdditionAccess().getAdditionLeftAction_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Addition__Group_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Addition__Group_1__1__Impl
	rule__Addition__Group_1__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Addition__Group_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAdditionAccess().getOperatorAssignment_1_1()); }
	(rule__Addition__OperatorAssignment_1_1)
	{ after(grammarAccess.getAdditionAccess().getOperatorAssignment_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Addition__Group_1__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Addition__Group_1__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Addition__Group_1__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getAdditionAccess().getRightAssignment_1_2()); }
	(rule__Addition__RightAssignment_1_2)
	{ after(grammarAccess.getAdditionAccess().getRightAssignment_1_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Multiplication__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Multiplication__Group__0__Impl
	rule__Multiplication__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Multiplication__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMultiplicationAccess().getPrimaryExpressionParserRuleCall_0()); }
	rulePrimaryExpression
	{ after(grammarAccess.getMultiplicationAccess().getPrimaryExpressionParserRuleCall_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Multiplication__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Multiplication__Group__1__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Multiplication__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMultiplicationAccess().getGroup_1()); }
	(rule__Multiplication__Group_1__0)*
	{ after(grammarAccess.getMultiplicationAccess().getGroup_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Multiplication__Group_1__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Multiplication__Group_1__0__Impl
	rule__Multiplication__Group_1__1
;
finally {
	restoreStackSize(stackSize);
}

rule__Multiplication__Group_1__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMultiplicationAccess().getMultiplicationLeftAction_1_0()); }
	()
	{ after(grammarAccess.getMultiplicationAccess().getMultiplicationLeftAction_1_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Multiplication__Group_1__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Multiplication__Group_1__1__Impl
	rule__Multiplication__Group_1__2
;
finally {
	restoreStackSize(stackSize);
}

rule__Multiplication__Group_1__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMultiplicationAccess().getOperatorAssignment_1_1()); }
	(rule__Multiplication__OperatorAssignment_1_1)
	{ after(grammarAccess.getMultiplicationAccess().getOperatorAssignment_1_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__Multiplication__Group_1__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__Multiplication__Group_1__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__Multiplication__Group_1__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getMultiplicationAccess().getRightAssignment_1_2()); }
	(rule__Multiplication__RightAssignment_1_2)
	{ after(grammarAccess.getMultiplicationAccess().getRightAssignment_1_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__PrimaryExpression__Group_2__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__PrimaryExpression__Group_2__0__Impl
	rule__PrimaryExpression__Group_2__1
;
finally {
	restoreStackSize(stackSize);
}

rule__PrimaryExpression__Group_2__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPrimaryExpressionAccess().getLeftParenthesisKeyword_2_0()); }
	'('
	{ after(grammarAccess.getPrimaryExpressionAccess().getLeftParenthesisKeyword_2_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__PrimaryExpression__Group_2__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__PrimaryExpression__Group_2__1__Impl
	rule__PrimaryExpression__Group_2__2
;
finally {
	restoreStackSize(stackSize);
}

rule__PrimaryExpression__Group_2__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPrimaryExpressionAccess().getAdditionParserRuleCall_2_1()); }
	ruleAddition
	{ after(grammarAccess.getPrimaryExpressionAccess().getAdditionParserRuleCall_2_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__PrimaryExpression__Group_2__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__PrimaryExpression__Group_2__2__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__PrimaryExpression__Group_2__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getPrimaryExpressionAccess().getRightParenthesisKeyword_2_2()); }
	')'
	{ after(grammarAccess.getPrimaryExpressionAccess().getRightParenthesisKeyword_2_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__VariableDeclaration__Group__0
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__VariableDeclaration__Group__0__Impl
	rule__VariableDeclaration__Group__1
;
finally {
	restoreStackSize(stackSize);
}

rule__VariableDeclaration__Group__0__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getVariableDeclarationAccess().getVarKeyword_0()); }
	'var'
	{ after(grammarAccess.getVariableDeclarationAccess().getVarKeyword_0()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__VariableDeclaration__Group__1
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__VariableDeclaration__Group__1__Impl
	rule__VariableDeclaration__Group__2
;
finally {
	restoreStackSize(stackSize);
}

rule__VariableDeclaration__Group__1__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getVariableDeclarationAccess().getNameAssignment_1()); }
	(rule__VariableDeclaration__NameAssignment_1)
	{ after(grammarAccess.getVariableDeclarationAccess().getNameAssignment_1()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__VariableDeclaration__Group__2
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__VariableDeclaration__Group__2__Impl
	rule__VariableDeclaration__Group__3
;
finally {
	restoreStackSize(stackSize);
}

rule__VariableDeclaration__Group__2__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getVariableDeclarationAccess().getEqualsSignKeyword_2()); }
	'='
	{ after(grammarAccess.getVariableDeclarationAccess().getEqualsSignKeyword_2()); }
)
;
finally {
	restoreStackSize(stackSize);
}

rule__VariableDeclaration__Group__3
	@init {
		int stackSize = keepStackSize();
	}
:
	rule__VariableDeclaration__Group__3__Impl
;
finally {
	restoreStackSize(stackSize);
}

rule__VariableDeclaration__Group__3__Impl
	@init {
		int stackSize = keepStackSize();
	}
:
(
	{ before(grammarAccess.getVariableDeclarationAccess().getValueAssignment_3()); }
	(rule__VariableDeclaration__ValueAssignment_3)
	{ after(grammarAccess.getVariableDeclarationAccess().getValueAssignment_3()); }
)
;
finally {
	restoreStackSize(stackSize);
}


rule__Order__InstructionsAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getOrderAccess().getInstructionsInstructionParserRuleCall_0()); }
		ruleInstruction
		{ after(grammarAccess.getOrderAccess().getInstructionsInstructionParserRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIngredient__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAddIngredientAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getAddIngredientAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIngredient__AmountAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAddIngredientAccess().getAmountAdditionParserRuleCall_3_0()); }
		ruleAddition
		{ after(grammarAccess.getAddIngredientAccess().getAmountAdditionParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddFixedIngredient__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAddFixedIngredientAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getAddFixedIngredientAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddFixedIngredient__AmountAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAddFixedIngredientAccess().getAmountAdditionParserRuleCall_3_0()); }
		ruleAddition
		{ after(grammarAccess.getAddFixedIngredientAccess().getAmountAdditionParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__FancyStatement__FcommandAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getFancyStatementAccess().getFcommandFancyMakeStatementEnumRuleCall_1_0()); }
		ruleFancyMakeStatement
		{ after(grammarAccess.getFancyStatementAccess().getFcommandFancyMakeStatementEnumRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIce__IceAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAddIceAccess().getIceIceStatementEnumRuleCall_1_0()); }
		ruleIceStatement
		{ after(grammarAccess.getAddIceAccess().getIceIceStatementEnumRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddIce__OunceAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAddIceAccess().getOunceAdditionParserRuleCall_3_0()); }
		ruleAddition
		{ after(grammarAccess.getAddIceAccess().getOunceAdditionParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__MuddleStatement__MudFruitAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMuddleStatementAccess().getMudFruitFruitStatementEnumRuleCall_1_0()); }
		ruleFruitStatement
		{ after(grammarAccess.getMuddleStatementAccess().getMudFruitFruitStatementEnumRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__MuddleStatement__MtimesAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMuddleStatementAccess().getMtimesAdditionParserRuleCall_3_0()); }
		ruleAddition
		{ after(grammarAccess.getMuddleStatementAccess().getMtimesAdditionParserRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddDecoration__DecorationAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAddDecorationAccess().getDecorationDecorationStatementEnumRuleCall_1_0()); }
		ruleDecorationStatement
		{ after(grammarAccess.getAddDecorationAccess().getDecorationDecorationStatementEnumRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__AddDecoration__SliceAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAddDecorationAccess().getSliceAdditionParserRuleCall_2_0()); }
		ruleAddition
		{ after(grammarAccess.getAddDecorationAccess().getSliceAdditionParserRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__MakeStatement__MakeAssignment_0
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMakeStatementAccess().getMakeMakeCommandEnumRuleCall_0_0()); }
		ruleMakeCommand
		{ after(grammarAccess.getMakeStatementAccess().getMakeMakeCommandEnumRuleCall_0_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__MakeStatement__TimeAssignment_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMakeStatementAccess().getTimeAdditionParserRuleCall_2_0()); }
		ruleAddition
		{ after(grammarAccess.getMakeStatementAccess().getTimeAdditionParserRuleCall_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Addition__OperatorAssignment_1_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAdditionAccess().getOperatorAlternatives_1_1_0()); }
		(rule__Addition__OperatorAlternatives_1_1_0)
		{ after(grammarAccess.getAdditionAccess().getOperatorAlternatives_1_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Addition__RightAssignment_1_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getAdditionAccess().getRightMultiplicationParserRuleCall_1_2_0()); }
		ruleMultiplication
		{ after(grammarAccess.getAdditionAccess().getRightMultiplicationParserRuleCall_1_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Multiplication__OperatorAssignment_1_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMultiplicationAccess().getOperatorAlternatives_1_1_0()); }
		(rule__Multiplication__OperatorAlternatives_1_1_0)
		{ after(grammarAccess.getMultiplicationAccess().getOperatorAlternatives_1_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__Multiplication__RightAssignment_1_2
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getMultiplicationAccess().getRightPrimaryExpressionParserRuleCall_1_2_0()); }
		rulePrimaryExpression
		{ after(grammarAccess.getMultiplicationAccess().getRightPrimaryExpressionParserRuleCall_1_2_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__IntLiteral__ValAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getIntLiteralAccess().getValINTTerminalRuleCall_0()); }
		RULE_INT
		{ after(grammarAccess.getIntLiteralAccess().getValINTTerminalRuleCall_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__VariableDeclaration__NameAssignment_1
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getVariableDeclarationAccess().getNameIDTerminalRuleCall_1_0()); }
		RULE_ID
		{ after(grammarAccess.getVariableDeclarationAccess().getNameIDTerminalRuleCall_1_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__VariableDeclaration__ValueAssignment_3
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getVariableDeclarationAccess().getValueINTTerminalRuleCall_3_0()); }
		RULE_INT
		{ after(grammarAccess.getVariableDeclarationAccess().getValueINTTerminalRuleCall_3_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

rule__IntVarExpression__VarAssignment
	@init {
		int stackSize = keepStackSize();
	}
:
	(
		{ before(grammarAccess.getIntVarExpressionAccess().getVarVariableDeclarationCrossReference_0()); }
		(
			{ before(grammarAccess.getIntVarExpressionAccess().getVarVariableDeclarationIDTerminalRuleCall_0_1()); }
			RULE_ID
			{ after(grammarAccess.getIntVarExpressionAccess().getVarVariableDeclarationIDTerminalRuleCall_0_1()); }
		)
		{ after(grammarAccess.getIntVarExpressionAccess().getVarVariableDeclarationCrossReference_0()); }
	)
;
finally {
	restoreStackSize(stackSize);
}

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
