/*
 * generated by Xtext 2.29.0
 */
grammar InternalCocktails;

options {
	superClass=AbstractInternalAntlrParser;
}

@lexer::header {
package org.xtext.example.mydsl.parser.antlr.internal;

// Hack: Use our own Lexer superclass by means of import. 
// Currently there is no other way to specify the superclass for the lexer.
import org.eclipse.xtext.parser.antlr.Lexer;
}

@parser::header {
package org.xtext.example.mydsl.parser.antlr.internal;

import org.eclipse.xtext.*;
import org.eclipse.xtext.parser.*;
import org.eclipse.xtext.parser.impl.*;
import org.eclipse.emf.ecore.util.EcoreUtil;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.common.util.Enumerator;
import org.eclipse.xtext.parser.antlr.AbstractInternalAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.xtext.parser.antlr.XtextTokenStream.HiddenTokens;
import org.eclipse.xtext.parser.antlr.AntlrDatatypeRuleToken;
import org.xtext.example.mydsl.services.CocktailsGrammarAccess;

}

@parser::members {

 	private CocktailsGrammarAccess grammarAccess;

    public InternalCocktailsParser(TokenStream input, CocktailsGrammarAccess grammarAccess) {
        this(input);
        this.grammarAccess = grammarAccess;
        registerRules(grammarAccess.getGrammar());
    }

    @Override
    protected String getFirstRuleName() {
    	return "Order";
   	}

   	@Override
   	protected CocktailsGrammarAccess getGrammarAccess() {
   		return grammarAccess;
   	}

}

@rulecatch {
    catch (RecognitionException re) {
        recover(input,re);
        appendSkippedTokens();
    }
}

// Entry rule entryRuleOrder
entryRuleOrder returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getOrderRule()); }
	iv_ruleOrder=ruleOrder
	{ $current=$iv_ruleOrder.current; }
	EOF;

// Rule Order
ruleOrder returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				newCompositeNode(grammarAccess.getOrderAccess().getInstructionsInstructionParserRuleCall_0());
			}
			lv_instructions_0_0=ruleInstruction
			{
				if ($current==null) {
					$current = createModelElementForParent(grammarAccess.getOrderRule());
				}
				add(
					$current,
					"instructions",
					lv_instructions_0_0,
					"org.xtext.example.mydsl.Cocktails.Instruction");
				afterParserOrEnumRuleCall();
			}
		)
	)*
;

// Entry rule entryRuleInstruction
entryRuleInstruction returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getInstructionRule()); }
	iv_ruleInstruction=ruleInstruction
	{ $current=$iv_ruleInstruction.current; }
	EOF;

// Rule Instruction
ruleInstruction returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getInstructionAccess().getAddIngredientParserRuleCall_0());
		}
		this_AddIngredient_0=ruleAddIngredient
		{
			$current = $this_AddIngredient_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getInstructionAccess().getAddFixedIngredientParserRuleCall_1());
		}
		this_AddFixedIngredient_1=ruleAddFixedIngredient
		{
			$current = $this_AddFixedIngredient_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getInstructionAccess().getFancyStatementParserRuleCall_2());
		}
		this_FancyStatement_2=ruleFancyStatement
		{
			$current = $this_FancyStatement_2.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getInstructionAccess().getAddIceParserRuleCall_3());
		}
		this_AddIce_3=ruleAddIce
		{
			$current = $this_AddIce_3.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getInstructionAccess().getMuddleStatementParserRuleCall_4());
		}
		this_MuddleStatement_4=ruleMuddleStatement
		{
			$current = $this_MuddleStatement_4.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getInstructionAccess().getAddDecorationParserRuleCall_5());
		}
		this_AddDecoration_5=ruleAddDecoration
		{
			$current = $this_AddDecoration_5.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getInstructionAccess().getMakeStatementParserRuleCall_6());
		}
		this_MakeStatement_6=ruleMakeStatement
		{
			$current = $this_MakeStatement_6.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getInstructionAccess().getVariableDeclarationParserRuleCall_7());
		}
		this_VariableDeclaration_7=ruleVariableDeclaration
		{
			$current = $this_VariableDeclaration_7.current;
			afterParserOrEnumRuleCall();
		}
	)
;

// Entry rule entryRuleAddIngredient
entryRuleAddIngredient returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAddIngredientRule()); }
	iv_ruleAddIngredient=ruleAddIngredient
	{ $current=$iv_ruleAddIngredient.current; }
	EOF;

// Rule AddIngredient
ruleAddIngredient returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='addI'
		{
			newLeafNode(otherlv_0, grammarAccess.getAddIngredientAccess().getAddIKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getAddIngredientAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getAddIngredientRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2=':'
		{
			newLeafNode(otherlv_2, grammarAccess.getAddIngredientAccess().getColonKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAddIngredientAccess().getAmountAdditionParserRuleCall_3_0());
				}
				lv_amount_3_0=ruleAddition
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAddIngredientRule());
					}
					set(
						$current,
						"amount",
						lv_amount_3_0,
						"org.xtext.example.mydsl.Cocktails.Addition");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_4='ml'
		{
			newLeafNode(otherlv_4, grammarAccess.getAddIngredientAccess().getMlKeyword_4());
		}
	)
;

// Entry rule entryRuleAddFixedIngredient
entryRuleAddFixedIngredient returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAddFixedIngredientRule()); }
	iv_ruleAddFixedIngredient=ruleAddFixedIngredient
	{ $current=$iv_ruleAddFixedIngredient.current; }
	EOF;

// Rule AddFixedIngredient
ruleAddFixedIngredient returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='addF'
		{
			newLeafNode(otherlv_0, grammarAccess.getAddFixedIngredientAccess().getAddFKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getAddFixedIngredientAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getAddFixedIngredientRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2=':'
		{
			newLeafNode(otherlv_2, grammarAccess.getAddFixedIngredientAccess().getColonKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAddFixedIngredientAccess().getAmountAdditionParserRuleCall_3_0());
				}
				lv_amount_3_0=ruleAddition
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAddFixedIngredientRule());
					}
					set(
						$current,
						"amount",
						lv_amount_3_0,
						"org.xtext.example.mydsl.Cocktails.Addition");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_4='g'
		{
			newLeafNode(otherlv_4, grammarAccess.getAddFixedIngredientAccess().getGKeyword_4());
		}
	)
;

// Entry rule entryRuleFancyStatement
entryRuleFancyStatement returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getFancyStatementRule()); }
	iv_ruleFancyStatement=ruleFancyStatement
	{ $current=$iv_ruleFancyStatement.current; }
	EOF;

// Rule FancyStatement
ruleFancyStatement returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='use'
		{
			newLeafNode(otherlv_0, grammarAccess.getFancyStatementAccess().getUseKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getFancyStatementAccess().getFcommandFancyMakeStatementEnumRuleCall_1_0());
				}
				lv_fcommand_1_0=ruleFancyMakeStatement
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getFancyStatementRule());
					}
					set(
						$current,
						"fcommand",
						lv_fcommand_1_0,
						"org.xtext.example.mydsl.Cocktails.FancyMakeStatement");
					afterParserOrEnumRuleCall();
				}
			)
		)
	)
;

// Entry rule entryRuleAddIce
entryRuleAddIce returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAddIceRule()); }
	iv_ruleAddIce=ruleAddIce
	{ $current=$iv_ruleAddIce.current; }
	EOF;

// Rule AddIce
ruleAddIce returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='addIc'
		{
			newLeafNode(otherlv_0, grammarAccess.getAddIceAccess().getAddIcKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAddIceAccess().getIceIceStatementEnumRuleCall_1_0());
				}
				lv_ice_1_0=ruleIceStatement
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAddIceRule());
					}
					set(
						$current,
						"ice",
						lv_ice_1_0,
						"org.xtext.example.mydsl.Cocktails.IceStatement");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_2=':'
		{
			newLeafNode(otherlv_2, grammarAccess.getAddIceAccess().getColonKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAddIceAccess().getOunceAdditionParserRuleCall_3_0());
				}
				lv_ounce_3_0=ruleAddition
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAddIceRule());
					}
					set(
						$current,
						"ounce",
						lv_ounce_3_0,
						"org.xtext.example.mydsl.Cocktails.Addition");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_4='ounce'
		{
			newLeafNode(otherlv_4, grammarAccess.getAddIceAccess().getOunceKeyword_4());
		}
	)
;

// Entry rule entryRuleMuddleStatement
entryRuleMuddleStatement returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getMuddleStatementRule()); }
	iv_ruleMuddleStatement=ruleMuddleStatement
	{ $current=$iv_ruleMuddleStatement.current; }
	EOF;

// Rule MuddleStatement
ruleMuddleStatement returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='mud'
		{
			newLeafNode(otherlv_0, grammarAccess.getMuddleStatementAccess().getMudKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getMuddleStatementAccess().getMudFruitFruitStatementEnumRuleCall_1_0());
				}
				lv_mudFruit_1_0=ruleFruitStatement
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getMuddleStatementRule());
					}
					add(
						$current,
						"mudFruit",
						lv_mudFruit_1_0,
						"org.xtext.example.mydsl.Cocktails.FruitStatement");
					afterParserOrEnumRuleCall();
				}
			)
		)*
		otherlv_2=':'
		{
			newLeafNode(otherlv_2, grammarAccess.getMuddleStatementAccess().getColonKeyword_2());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getMuddleStatementAccess().getMtimesAdditionParserRuleCall_3_0());
				}
				lv_mtimes_3_0=ruleAddition
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getMuddleStatementRule());
					}
					set(
						$current,
						"mtimes",
						lv_mtimes_3_0,
						"org.xtext.example.mydsl.Cocktails.Addition");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_4='times'
		{
			newLeafNode(otherlv_4, grammarAccess.getMuddleStatementAccess().getTimesKeyword_4());
		}
	)
;

// Entry rule entryRuleAddDecoration
entryRuleAddDecoration returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAddDecorationRule()); }
	iv_ruleAddDecoration=ruleAddDecoration
	{ $current=$iv_ruleAddDecoration.current; }
	EOF;

// Rule AddDecoration
ruleAddDecoration returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='addD'
		{
			newLeafNode(otherlv_0, grammarAccess.getAddDecorationAccess().getAddDKeyword_0());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getAddDecorationAccess().getDecorationDecorationStatementEnumRuleCall_1_0());
				}
				lv_decoration_1_0=ruleDecorationStatement
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAddDecorationRule());
					}
					set(
						$current,
						"decoration",
						lv_decoration_1_0,
						"org.xtext.example.mydsl.Cocktails.DecorationStatement");
					afterParserOrEnumRuleCall();
				}
			)
		)
		(
			(
				{
					newCompositeNode(grammarAccess.getAddDecorationAccess().getSliceAdditionParserRuleCall_2_0());
				}
				lv_slice_2_0=ruleAddition
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getAddDecorationRule());
					}
					set(
						$current,
						"slice",
						lv_slice_2_0,
						"org.xtext.example.mydsl.Cocktails.Addition");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='slices'
		{
			newLeafNode(otherlv_3, grammarAccess.getAddDecorationAccess().getSlicesKeyword_3());
		}
	)
;

// Entry rule entryRuleMakeStatement
entryRuleMakeStatement returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getMakeStatementRule()); }
	iv_ruleMakeStatement=ruleMakeStatement
	{ $current=$iv_ruleMakeStatement.current; }
	EOF;

// Rule MakeStatement
ruleMakeStatement returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			(
				{
					newCompositeNode(grammarAccess.getMakeStatementAccess().getMakeMakeCommandEnumRuleCall_0_0());
				}
				lv_make_0_0=ruleMakeCommand
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getMakeStatementRule());
					}
					set(
						$current,
						"make",
						lv_make_0_0,
						"org.xtext.example.mydsl.Cocktails.MakeCommand");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_1=':'
		{
			newLeafNode(otherlv_1, grammarAccess.getMakeStatementAccess().getColonKeyword_1());
		}
		(
			(
				{
					newCompositeNode(grammarAccess.getMakeStatementAccess().getTimeAdditionParserRuleCall_2_0());
				}
				lv_time_2_0=ruleAddition
				{
					if ($current==null) {
						$current = createModelElementForParent(grammarAccess.getMakeStatementRule());
					}
					set(
						$current,
						"time",
						lv_time_2_0,
						"org.xtext.example.mydsl.Cocktails.Addition");
					afterParserOrEnumRuleCall();
				}
			)
		)
		otherlv_3='seconds'
		{
			newLeafNode(otherlv_3, grammarAccess.getMakeStatementAccess().getSecondsKeyword_3());
		}
	)
;

// Entry rule entryRuleAddition
entryRuleAddition returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getAdditionRule()); }
	iv_ruleAddition=ruleAddition
	{ $current=$iv_ruleAddition.current; }
	EOF;

// Rule Addition
ruleAddition returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getAdditionAccess().getMultiplicationParserRuleCall_0());
		}
		this_Multiplication_0=ruleMultiplication
		{
			$current = $this_Multiplication_0.current;
			afterParserOrEnumRuleCall();
		}
		(
			(
				{
					$current = forceCreateModelElementAndSet(
						grammarAccess.getAdditionAccess().getAdditionLeftAction_1_0(),
						$current);
				}
			)
			(
				(
					(
						lv_operator_2_1='+'
						{
							newLeafNode(lv_operator_2_1, grammarAccess.getAdditionAccess().getOperatorPlusSignKeyword_1_1_0_0());
						}
						{
							if ($current==null) {
								$current = createModelElement(grammarAccess.getAdditionRule());
							}
							addWithLastConsumed($current, "operator", lv_operator_2_1, null);
						}
						    |
						lv_operator_2_2='-'
						{
							newLeafNode(lv_operator_2_2, grammarAccess.getAdditionAccess().getOperatorHyphenMinusKeyword_1_1_0_1());
						}
						{
							if ($current==null) {
								$current = createModelElement(grammarAccess.getAdditionRule());
							}
							addWithLastConsumed($current, "operator", lv_operator_2_2, null);
						}
					)
				)
			)
			(
				(
					{
						newCompositeNode(grammarAccess.getAdditionAccess().getRightMultiplicationParserRuleCall_1_2_0());
					}
					lv_right_3_0=ruleMultiplication
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getAdditionRule());
						}
						add(
							$current,
							"right",
							lv_right_3_0,
							"org.xtext.example.mydsl.Cocktails.Multiplication");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
	)
;

// Entry rule entryRuleMultiplication
entryRuleMultiplication returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getMultiplicationRule()); }
	iv_ruleMultiplication=ruleMultiplication
	{ $current=$iv_ruleMultiplication.current; }
	EOF;

// Rule Multiplication
ruleMultiplication returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getMultiplicationAccess().getPrimaryExpressionParserRuleCall_0());
		}
		this_PrimaryExpression_0=rulePrimaryExpression
		{
			$current = $this_PrimaryExpression_0.current;
			afterParserOrEnumRuleCall();
		}
		(
			(
				{
					$current = forceCreateModelElementAndSet(
						grammarAccess.getMultiplicationAccess().getMultiplicationLeftAction_1_0(),
						$current);
				}
			)
			(
				(
					(
						lv_operator_2_1='*'
						{
							newLeafNode(lv_operator_2_1, grammarAccess.getMultiplicationAccess().getOperatorAsteriskKeyword_1_1_0_0());
						}
						{
							if ($current==null) {
								$current = createModelElement(grammarAccess.getMultiplicationRule());
							}
							addWithLastConsumed($current, "operator", lv_operator_2_1, null);
						}
						    |
						lv_operator_2_2='/'
						{
							newLeafNode(lv_operator_2_2, grammarAccess.getMultiplicationAccess().getOperatorSolidusKeyword_1_1_0_1());
						}
						{
							if ($current==null) {
								$current = createModelElement(grammarAccess.getMultiplicationRule());
							}
							addWithLastConsumed($current, "operator", lv_operator_2_2, null);
						}
					)
				)
			)
			(
				(
					{
						newCompositeNode(grammarAccess.getMultiplicationAccess().getRightPrimaryExpressionParserRuleCall_1_2_0());
					}
					lv_right_3_0=rulePrimaryExpression
					{
						if ($current==null) {
							$current = createModelElementForParent(grammarAccess.getMultiplicationRule());
						}
						add(
							$current,
							"right",
							lv_right_3_0,
							"org.xtext.example.mydsl.Cocktails.PrimaryExpression");
						afterParserOrEnumRuleCall();
					}
				)
			)
		)*
	)
;

// Entry rule entryRulePrimaryExpression
entryRulePrimaryExpression returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getPrimaryExpressionRule()); }
	iv_rulePrimaryExpression=rulePrimaryExpression
	{ $current=$iv_rulePrimaryExpression.current; }
	EOF;

// Rule PrimaryExpression
rulePrimaryExpression returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		{
			newCompositeNode(grammarAccess.getPrimaryExpressionAccess().getIntLiteralParserRuleCall_0());
		}
		this_IntLiteral_0=ruleIntLiteral
		{
			$current = $this_IntLiteral_0.current;
			afterParserOrEnumRuleCall();
		}
		    |
		{
			newCompositeNode(grammarAccess.getPrimaryExpressionAccess().getIntVarExpressionParserRuleCall_1());
		}
		this_IntVarExpression_1=ruleIntVarExpression
		{
			$current = $this_IntVarExpression_1.current;
			afterParserOrEnumRuleCall();
		}
		    |
		(
			otherlv_2='('
			{
				newLeafNode(otherlv_2, grammarAccess.getPrimaryExpressionAccess().getLeftParenthesisKeyword_2_0());
			}
			{
				newCompositeNode(grammarAccess.getPrimaryExpressionAccess().getAdditionParserRuleCall_2_1());
			}
			this_Addition_3=ruleAddition
			{
				$current = $this_Addition_3.current;
				afterParserOrEnumRuleCall();
			}
			otherlv_4=')'
			{
				newLeafNode(otherlv_4, grammarAccess.getPrimaryExpressionAccess().getRightParenthesisKeyword_2_2());
			}
		)
	)
;

// Entry rule entryRuleIntLiteral
entryRuleIntLiteral returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getIntLiteralRule()); }
	iv_ruleIntLiteral=ruleIntLiteral
	{ $current=$iv_ruleIntLiteral.current; }
	EOF;

// Rule IntLiteral
ruleIntLiteral returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			lv_val_0_0=RULE_INT
			{
				newLeafNode(lv_val_0_0, grammarAccess.getIntLiteralAccess().getValINTTerminalRuleCall_0());
			}
			{
				if ($current==null) {
					$current = createModelElement(grammarAccess.getIntLiteralRule());
				}
				setWithLastConsumed(
					$current,
					"val",
					lv_val_0_0,
					"org.eclipse.xtext.common.Terminals.INT");
			}
		)
	)
;

// Entry rule entryRuleVariableDeclaration
entryRuleVariableDeclaration returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getVariableDeclarationRule()); }
	iv_ruleVariableDeclaration=ruleVariableDeclaration
	{ $current=$iv_ruleVariableDeclaration.current; }
	EOF;

// Rule VariableDeclaration
ruleVariableDeclaration returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		otherlv_0='var'
		{
			newLeafNode(otherlv_0, grammarAccess.getVariableDeclarationAccess().getVarKeyword_0());
		}
		(
			(
				lv_name_1_0=RULE_ID
				{
					newLeafNode(lv_name_1_0, grammarAccess.getVariableDeclarationAccess().getNameIDTerminalRuleCall_1_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getVariableDeclarationRule());
					}
					setWithLastConsumed(
						$current,
						"name",
						lv_name_1_0,
						"org.eclipse.xtext.common.Terminals.ID");
				}
			)
		)
		otherlv_2='='
		{
			newLeafNode(otherlv_2, grammarAccess.getVariableDeclarationAccess().getEqualsSignKeyword_2());
		}
		(
			(
				lv_value_3_0=RULE_INT
				{
					newLeafNode(lv_value_3_0, grammarAccess.getVariableDeclarationAccess().getValueINTTerminalRuleCall_3_0());
				}
				{
					if ($current==null) {
						$current = createModelElement(grammarAccess.getVariableDeclarationRule());
					}
					setWithLastConsumed(
						$current,
						"value",
						lv_value_3_0,
						"org.eclipse.xtext.common.Terminals.INT");
				}
			)
		)
	)
;

// Entry rule entryRuleIntVarExpression
entryRuleIntVarExpression returns [EObject current=null]:
	{ newCompositeNode(grammarAccess.getIntVarExpressionRule()); }
	iv_ruleIntVarExpression=ruleIntVarExpression
	{ $current=$iv_ruleIntVarExpression.current; }
	EOF;

// Rule IntVarExpression
ruleIntVarExpression returns [EObject current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			{
				if ($current==null) {
					$current = createModelElement(grammarAccess.getIntVarExpressionRule());
				}
			}
			otherlv_0=RULE_ID
			{
				newLeafNode(otherlv_0, grammarAccess.getIntVarExpressionAccess().getVarVariableDeclarationCrossReference_0());
			}
		)
	)
;

// Rule FancyMakeStatement
ruleFancyMakeStatement returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='lighter'
			{
				$current = grammarAccess.getFancyMakeStatementAccess().getLighterEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getFancyMakeStatementAccess().getLighterEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='co2'
			{
				$current = grammarAccess.getFancyMakeStatementAccess().getCo2EnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getFancyMakeStatementAccess().getCo2EnumLiteralDeclaration_1());
			}
		)
	)
;

// Rule IceStatement
ruleIceStatement returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='cube'
			{
				$current = grammarAccess.getIceStatementAccess().getCubeEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getIceStatementAccess().getCubeEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='crush'
			{
				$current = grammarAccess.getIceStatementAccess().getCrushEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getIceStatementAccess().getCrushEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='shave'
			{
				$current = grammarAccess.getIceStatementAccess().getShaveEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getIceStatementAccess().getShaveEnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='block'
			{
				$current = grammarAccess.getIceStatementAccess().getBlockEnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getIceStatementAccess().getBlockEnumLiteralDeclaration_3());
			}
		)
		    |
		(
			enumLiteral_4='ball'
			{
				$current = grammarAccess.getIceStatementAccess().getBallEnumLiteralDeclaration_4().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_4, grammarAccess.getIceStatementAccess().getBallEnumLiteralDeclaration_4());
			}
		)
		    |
		(
			enumLiteral_5='cone'
			{
				$current = grammarAccess.getIceStatementAccess().getConeEnumLiteralDeclaration_5().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_5, grammarAccess.getIceStatementAccess().getConeEnumLiteralDeclaration_5());
			}
		)
	)
;

// Rule FruitStatement
ruleFruitStatement returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='lime'
			{
				$current = grammarAccess.getFruitStatementAccess().getLimeEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getFruitStatementAccess().getLimeEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='lemon'
			{
				$current = grammarAccess.getFruitStatementAccess().getLemonEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getFruitStatementAccess().getLemonEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='orange'
			{
				$current = grammarAccess.getFruitStatementAccess().getOrangeEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getFruitStatementAccess().getOrangeEnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='grapefruit'
			{
				$current = grammarAccess.getFruitStatementAccess().getGrapefruitEnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getFruitStatementAccess().getGrapefruitEnumLiteralDeclaration_3());
			}
		)
		    |
		(
			enumLiteral_4='pineapple'
			{
				$current = grammarAccess.getFruitStatementAccess().getPineappleEnumLiteralDeclaration_4().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_4, grammarAccess.getFruitStatementAccess().getPineappleEnumLiteralDeclaration_4());
			}
		)
		    |
		(
			enumLiteral_5='mango'
			{
				$current = grammarAccess.getFruitStatementAccess().getMangoEnumLiteralDeclaration_5().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_5, grammarAccess.getFruitStatementAccess().getMangoEnumLiteralDeclaration_5());
			}
		)
		    |
		(
			enumLiteral_6='kiwi'
			{
				$current = grammarAccess.getFruitStatementAccess().getKiwiEnumLiteralDeclaration_6().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_6, grammarAccess.getFruitStatementAccess().getKiwiEnumLiteralDeclaration_6());
			}
		)
		    |
		(
			enumLiteral_7='strawberry'
			{
				$current = grammarAccess.getFruitStatementAccess().getStrawberryEnumLiteralDeclaration_7().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_7, grammarAccess.getFruitStatementAccess().getStrawberryEnumLiteralDeclaration_7());
			}
		)
		    |
		(
			enumLiteral_8='blueberry'
			{
				$current = grammarAccess.getFruitStatementAccess().getBlueberryEnumLiteralDeclaration_8().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_8, grammarAccess.getFruitStatementAccess().getBlueberryEnumLiteralDeclaration_8());
			}
		)
		    |
		(
			enumLiteral_9='raspberry'
			{
				$current = grammarAccess.getFruitStatementAccess().getRaspberryEnumLiteralDeclaration_9().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_9, grammarAccess.getFruitStatementAccess().getRaspberryEnumLiteralDeclaration_9());
			}
		)
		    |
		(
			enumLiteral_10='blackberry'
			{
				$current = grammarAccess.getFruitStatementAccess().getBlackberryEnumLiteralDeclaration_10().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_10, grammarAccess.getFruitStatementAccess().getBlackberryEnumLiteralDeclaration_10());
			}
		)
		    |
		(
			enumLiteral_11='cherry'
			{
				$current = grammarAccess.getFruitStatementAccess().getCherryEnumLiteralDeclaration_11().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_11, grammarAccess.getFruitStatementAccess().getCherryEnumLiteralDeclaration_11());
			}
		)
		    |
		(
			enumLiteral_12='peach'
			{
				$current = grammarAccess.getFruitStatementAccess().getPeachEnumLiteralDeclaration_12().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_12, grammarAccess.getFruitStatementAccess().getPeachEnumLiteralDeclaration_12());
			}
		)
		    |
		(
			enumLiteral_13='plum'
			{
				$current = grammarAccess.getFruitStatementAccess().getPlumEnumLiteralDeclaration_13().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_13, grammarAccess.getFruitStatementAccess().getPlumEnumLiteralDeclaration_13());
			}
		)
		    |
		(
			enumLiteral_14='watermelon'
			{
				$current = grammarAccess.getFruitStatementAccess().getWatermelonEnumLiteralDeclaration_14().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_14, grammarAccess.getFruitStatementAccess().getWatermelonEnumLiteralDeclaration_14());
			}
		)
		    |
		(
			enumLiteral_15='cucumber'
			{
				$current = grammarAccess.getFruitStatementAccess().getCucumberEnumLiteralDeclaration_15().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_15, grammarAccess.getFruitStatementAccess().getCucumberEnumLiteralDeclaration_15());
			}
		)
		    |
		(
			enumLiteral_16='mint'
			{
				$current = grammarAccess.getFruitStatementAccess().getMintEnumLiteralDeclaration_16().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_16, grammarAccess.getFruitStatementAccess().getMintEnumLiteralDeclaration_16());
			}
		)
		    |
		(
			enumLiteral_17='basil'
			{
				$current = grammarAccess.getFruitStatementAccess().getBasilEnumLiteralDeclaration_17().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_17, grammarAccess.getFruitStatementAccess().getBasilEnumLiteralDeclaration_17());
			}
		)
		    |
		(
			enumLiteral_18='thyme'
			{
				$current = grammarAccess.getFruitStatementAccess().getThymeEnumLiteralDeclaration_18().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_18, grammarAccess.getFruitStatementAccess().getThymeEnumLiteralDeclaration_18());
			}
		)
		    |
		(
			enumLiteral_19='ginger'
			{
				$current = grammarAccess.getFruitStatementAccess().getGingerEnumLiteralDeclaration_19().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_19, grammarAccess.getFruitStatementAccess().getGingerEnumLiteralDeclaration_19());
			}
		)
	)
;

// Rule DecorationStatement
ruleDecorationStatement returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='orange'
			{
				$current = grammarAccess.getDecorationStatementAccess().getOrangeEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getDecorationStatementAccess().getOrangeEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='lemon'
			{
				$current = grammarAccess.getDecorationStatementAccess().getLemonEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getDecorationStatementAccess().getLemonEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='lime'
			{
				$current = grammarAccess.getDecorationStatementAccess().getLimeEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getDecorationStatementAccess().getLimeEnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='olive'
			{
				$current = grammarAccess.getDecorationStatementAccess().getOliveEnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getDecorationStatementAccess().getOliveEnumLiteralDeclaration_3());
			}
		)
		    |
		(
			enumLiteral_4='cherry'
			{
				$current = grammarAccess.getDecorationStatementAccess().getCherryEnumLiteralDeclaration_4().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_4, grammarAccess.getDecorationStatementAccess().getCherryEnumLiteralDeclaration_4());
			}
		)
		    |
		(
			enumLiteral_5='mint'
			{
				$current = grammarAccess.getDecorationStatementAccess().getMintEnumLiteralDeclaration_5().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_5, grammarAccess.getDecorationStatementAccess().getMintEnumLiteralDeclaration_5());
			}
		)
		    |
		(
			enumLiteral_6='rose'
			{
				$current = grammarAccess.getDecorationStatementAccess().getRoseEnumLiteralDeclaration_6().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_6, grammarAccess.getDecorationStatementAccess().getRoseEnumLiteralDeclaration_6());
			}
		)
		    |
		(
			enumLiteral_7='cinnamon'
			{
				$current = grammarAccess.getDecorationStatementAccess().getCinnamonEnumLiteralDeclaration_7().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_7, grammarAccess.getDecorationStatementAccess().getCinnamonEnumLiteralDeclaration_7());
			}
		)
		    |
		(
			enumLiteral_8='mango'
			{
				$current = grammarAccess.getDecorationStatementAccess().getMangoEnumLiteralDeclaration_8().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_8, grammarAccess.getDecorationStatementAccess().getMangoEnumLiteralDeclaration_8());
			}
		)
		    |
		(
			enumLiteral_9='grapefruit'
			{
				$current = grammarAccess.getDecorationStatementAccess().getGrapefruitEnumLiteralDeclaration_9().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_9, grammarAccess.getDecorationStatementAccess().getGrapefruitEnumLiteralDeclaration_9());
			}
		)
	)
;

// Rule MakeCommand
ruleMakeCommand returns [Enumerator current=null]
@init {
	enterRule();
}
@after {
	leaveRule();
}:
	(
		(
			enumLiteral_0='stir'
			{
				$current = grammarAccess.getMakeCommandAccess().getStirEnumLiteralDeclaration_0().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_0, grammarAccess.getMakeCommandAccess().getStirEnumLiteralDeclaration_0());
			}
		)
		    |
		(
			enumLiteral_1='shake'
			{
				$current = grammarAccess.getMakeCommandAccess().getShakeEnumLiteralDeclaration_1().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_1, grammarAccess.getMakeCommandAccess().getShakeEnumLiteralDeclaration_1());
			}
		)
		    |
		(
			enumLiteral_2='blend'
			{
				$current = grammarAccess.getMakeCommandAccess().getBlendEnumLiteralDeclaration_2().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_2, grammarAccess.getMakeCommandAccess().getBlendEnumLiteralDeclaration_2());
			}
		)
		    |
		(
			enumLiteral_3='filter'
			{
				$current = grammarAccess.getMakeCommandAccess().getFilterEnumLiteralDeclaration_3().getEnumLiteral().getInstance();
				newLeafNode(enumLiteral_3, grammarAccess.getMakeCommandAccess().getFilterEnumLiteralDeclaration_3());
			}
		)
	)
;

RULE_ID : '^'? ('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;

RULE_INT : ('0'..'9')+;

RULE_STRING : ('"' ('\\' .|~(('\\'|'"')))* '"'|'\'' ('\\' .|~(('\\'|'\'')))* '\'');

RULE_ML_COMMENT : '/*' ( options {greedy=false;} : . )*'*/';

RULE_SL_COMMENT : '//' ~(('\n'|'\r'))* ('\r'? '\n')?;

RULE_WS : (' '|'\t'|'\r'|'\n')+;

RULE_ANY_OTHER : .;
