/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.cocktails.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.cocktails.AddIce;
import org.xtext.example.mydsl.cocktails.CocktailsPackage;
import org.xtext.example.mydsl.cocktails.Expression;
import org.xtext.example.mydsl.cocktails.IceStatement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Add Ice</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.cocktails.impl.AddIceImpl#getIce <em>Ice</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.cocktails.impl.AddIceImpl#getOunce <em>Ounce</em>}</li>
 * </ul>
 *
 * @generated
 */
public class AddIceImpl extends InstructionImpl implements AddIce
{
  /**
   * The default value of the '{@link #getIce() <em>Ice</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIce()
   * @generated
   * @ordered
   */
  protected static final IceStatement ICE_EDEFAULT = IceStatement.CUBE;

  /**
   * The cached value of the '{@link #getIce() <em>Ice</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIce()
   * @generated
   * @ordered
   */
  protected IceStatement ice = ICE_EDEFAULT;

  /**
   * The cached value of the '{@link #getOunce() <em>Ounce</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOunce()
   * @generated
   * @ordered
   */
  protected Expression ounce;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected AddIceImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CocktailsPackage.Literals.ADD_ICE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IceStatement getIce()
  {
    return ice;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setIce(IceStatement newIce)
  {
    IceStatement oldIce = ice;
    ice = newIce == null ? ICE_EDEFAULT : newIce;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CocktailsPackage.ADD_ICE__ICE, oldIce, ice));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getOunce()
  {
    return ounce;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOunce(Expression newOunce, NotificationChain msgs)
  {
    Expression oldOunce = ounce;
    ounce = newOunce;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CocktailsPackage.ADD_ICE__OUNCE, oldOunce, newOunce);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOunce(Expression newOunce)
  {
    if (newOunce != ounce)
    {
      NotificationChain msgs = null;
      if (ounce != null)
        msgs = ((InternalEObject)ounce).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CocktailsPackage.ADD_ICE__OUNCE, null, msgs);
      if (newOunce != null)
        msgs = ((InternalEObject)newOunce).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CocktailsPackage.ADD_ICE__OUNCE, null, msgs);
      msgs = basicSetOunce(newOunce, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CocktailsPackage.ADD_ICE__OUNCE, newOunce, newOunce));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CocktailsPackage.ADD_ICE__OUNCE:
        return basicSetOunce(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CocktailsPackage.ADD_ICE__ICE:
        return getIce();
      case CocktailsPackage.ADD_ICE__OUNCE:
        return getOunce();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CocktailsPackage.ADD_ICE__ICE:
        setIce((IceStatement)newValue);
        return;
      case CocktailsPackage.ADD_ICE__OUNCE:
        setOunce((Expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CocktailsPackage.ADD_ICE__ICE:
        setIce(ICE_EDEFAULT);
        return;
      case CocktailsPackage.ADD_ICE__OUNCE:
        setOunce((Expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CocktailsPackage.ADD_ICE__ICE:
        return ice != ICE_EDEFAULT;
      case CocktailsPackage.ADD_ICE__OUNCE:
        return ounce != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (ice: ");
    result.append(ice);
    result.append(')');
    return result.toString();
  }

} //AddIceImpl
