/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.cocktails.impl;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

import org.eclipse.emf.ecore.impl.EPackageImpl;

import org.xtext.example.mydsl.cocktails.AddDecoration;
import org.xtext.example.mydsl.cocktails.AddFixedIngredient;
import org.xtext.example.mydsl.cocktails.AddIce;
import org.xtext.example.mydsl.cocktails.AddIngredient;
import org.xtext.example.mydsl.cocktails.Addition;
import org.xtext.example.mydsl.cocktails.CocktailsFactory;
import org.xtext.example.mydsl.cocktails.CocktailsPackage;
import org.xtext.example.mydsl.cocktails.DecorationStatement;
import org.xtext.example.mydsl.cocktails.Expression;
import org.xtext.example.mydsl.cocktails.FancyMakeStatement;
import org.xtext.example.mydsl.cocktails.FancyStatement;
import org.xtext.example.mydsl.cocktails.FruitStatement;
import org.xtext.example.mydsl.cocktails.IceStatement;
import org.xtext.example.mydsl.cocktails.Instruction;
import org.xtext.example.mydsl.cocktails.IntLiteral;
import org.xtext.example.mydsl.cocktails.IntVarExpression;
import org.xtext.example.mydsl.cocktails.MakeCommand;
import org.xtext.example.mydsl.cocktails.MakeStatement;
import org.xtext.example.mydsl.cocktails.MuddleStatement;
import org.xtext.example.mydsl.cocktails.Multiplication;
import org.xtext.example.mydsl.cocktails.Order;
import org.xtext.example.mydsl.cocktails.VariableDeclaration;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Package</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class CocktailsPackageImpl extends EPackageImpl implements CocktailsPackage
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass orderEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass instructionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass addIngredientEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass addFixedIngredientEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass fancyStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass addIceEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass muddleStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass addDecorationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass makeStatementEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass expressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass intLiteralEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass variableDeclarationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass intVarExpressionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass additionEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EClass multiplicationEClass = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum fancyMakeStatementEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum iceStatementEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum fruitStatementEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum decorationStatementEEnum = null;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private EEnum makeCommandEEnum = null;

  /**
   * Creates an instance of the model <b>Package</b>, registered with
   * {@link org.eclipse.emf.ecore.EPackage.Registry EPackage.Registry} by the package
   * package URI value.
   * <p>Note: the correct way to create the package is via the static
   * factory method {@link #init init()}, which also performs
   * initialization of the package, or returns the registered package,
   * if one already exists.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.eclipse.emf.ecore.EPackage.Registry
   * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#eNS_URI
   * @see #init()
   * @generated
   */
  private CocktailsPackageImpl()
  {
    super(eNS_URI, CocktailsFactory.eINSTANCE);
  }
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static boolean isInited = false;

  /**
   * Creates, registers, and initializes the <b>Package</b> for this model, and for any others upon which it depends.
   *
   * <p>This method is used to initialize {@link CocktailsPackage#eINSTANCE} when that field is accessed.
   * Clients should not invoke it directly. Instead, they should simply access that field to obtain the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #eNS_URI
   * @see #createPackageContents()
   * @see #initializePackageContents()
   * @generated
   */
  public static CocktailsPackage init()
  {
    if (isInited) return (CocktailsPackage)EPackage.Registry.INSTANCE.getEPackage(CocktailsPackage.eNS_URI);

    // Obtain or create and register package
    Object registeredCocktailsPackage = EPackage.Registry.INSTANCE.get(eNS_URI);
    CocktailsPackageImpl theCocktailsPackage = registeredCocktailsPackage instanceof CocktailsPackageImpl ? (CocktailsPackageImpl)registeredCocktailsPackage : new CocktailsPackageImpl();

    isInited = true;

    // Create package meta-data objects
    theCocktailsPackage.createPackageContents();

    // Initialize created meta-data
    theCocktailsPackage.initializePackageContents();

    // Mark meta-data to indicate it can't be changed
    theCocktailsPackage.freeze();

    // Update the registry and return the package
    EPackage.Registry.INSTANCE.put(CocktailsPackage.eNS_URI, theCocktailsPackage);
    return theCocktailsPackage;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getOrder()
  {
    return orderEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getOrder_Instructions()
  {
    return (EReference)orderEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getInstruction()
  {
    return instructionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAddIngredient()
  {
    return addIngredientEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAddIngredient_Name()
  {
    return (EAttribute)addIngredientEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAddIngredient_Amount()
  {
    return (EReference)addIngredientEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAddFixedIngredient()
  {
    return addFixedIngredientEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAddFixedIngredient_Name()
  {
    return (EAttribute)addFixedIngredientEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAddFixedIngredient_Amount()
  {
    return (EReference)addFixedIngredientEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getFancyStatement()
  {
    return fancyStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getFancyStatement_Fcommand()
  {
    return (EAttribute)fancyStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAddIce()
  {
    return addIceEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAddIce_Ice()
  {
    return (EAttribute)addIceEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAddIce_Ounce()
  {
    return (EReference)addIceEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMuddleStatement()
  {
    return muddleStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMuddleStatement_MudFruit()
  {
    return (EAttribute)muddleStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMuddleStatement_Mtimes()
  {
    return (EReference)muddleStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAddDecoration()
  {
    return addDecorationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAddDecoration_Decoration()
  {
    return (EAttribute)addDecorationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAddDecoration_Slice()
  {
    return (EReference)addDecorationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMakeStatement()
  {
    return makeStatementEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMakeStatement_Make()
  {
    return (EAttribute)makeStatementEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMakeStatement_Time()
  {
    return (EReference)makeStatementEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getExpression()
  {
    return expressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntLiteral()
  {
    return intLiteralEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getIntLiteral_Val()
  {
    return (EAttribute)intLiteralEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getVariableDeclaration()
  {
    return variableDeclarationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVariableDeclaration_Name()
  {
    return (EAttribute)variableDeclarationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getVariableDeclaration_Value()
  {
    return (EAttribute)variableDeclarationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getIntVarExpression()
  {
    return intVarExpressionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getIntVarExpression_Var()
  {
    return (EReference)intVarExpressionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getAddition()
  {
    return additionEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAddition_Left()
  {
    return (EReference)additionEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getAddition_Operator()
  {
    return (EAttribute)additionEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getAddition_Right()
  {
    return (EReference)additionEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EClass getMultiplication()
  {
    return multiplicationEClass;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMultiplication_Left()
  {
    return (EReference)multiplicationEClass.getEStructuralFeatures().get(0);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAttribute getMultiplication_Operator()
  {
    return (EAttribute)multiplicationEClass.getEStructuralFeatures().get(1);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EReference getMultiplication_Right()
  {
    return (EReference)multiplicationEClass.getEStructuralFeatures().get(2);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getFancyMakeStatement()
  {
    return fancyMakeStatementEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getIceStatement()
  {
    return iceStatementEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getFruitStatement()
  {
    return fruitStatementEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getDecorationStatement()
  {
    return decorationStatementEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EEnum getMakeCommand()
  {
    return makeCommandEEnum;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CocktailsFactory getCocktailsFactory()
  {
    return (CocktailsFactory)getEFactoryInstance();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isCreated = false;

  /**
   * Creates the meta-model objects for the package.  This method is
   * guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void createPackageContents()
  {
    if (isCreated) return;
    isCreated = true;

    // Create classes and their features
    orderEClass = createEClass(ORDER);
    createEReference(orderEClass, ORDER__INSTRUCTIONS);

    instructionEClass = createEClass(INSTRUCTION);

    addIngredientEClass = createEClass(ADD_INGREDIENT);
    createEAttribute(addIngredientEClass, ADD_INGREDIENT__NAME);
    createEReference(addIngredientEClass, ADD_INGREDIENT__AMOUNT);

    addFixedIngredientEClass = createEClass(ADD_FIXED_INGREDIENT);
    createEAttribute(addFixedIngredientEClass, ADD_FIXED_INGREDIENT__NAME);
    createEReference(addFixedIngredientEClass, ADD_FIXED_INGREDIENT__AMOUNT);

    fancyStatementEClass = createEClass(FANCY_STATEMENT);
    createEAttribute(fancyStatementEClass, FANCY_STATEMENT__FCOMMAND);

    addIceEClass = createEClass(ADD_ICE);
    createEAttribute(addIceEClass, ADD_ICE__ICE);
    createEReference(addIceEClass, ADD_ICE__OUNCE);

    muddleStatementEClass = createEClass(MUDDLE_STATEMENT);
    createEAttribute(muddleStatementEClass, MUDDLE_STATEMENT__MUD_FRUIT);
    createEReference(muddleStatementEClass, MUDDLE_STATEMENT__MTIMES);

    addDecorationEClass = createEClass(ADD_DECORATION);
    createEAttribute(addDecorationEClass, ADD_DECORATION__DECORATION);
    createEReference(addDecorationEClass, ADD_DECORATION__SLICE);

    makeStatementEClass = createEClass(MAKE_STATEMENT);
    createEAttribute(makeStatementEClass, MAKE_STATEMENT__MAKE);
    createEReference(makeStatementEClass, MAKE_STATEMENT__TIME);

    expressionEClass = createEClass(EXPRESSION);

    intLiteralEClass = createEClass(INT_LITERAL);
    createEAttribute(intLiteralEClass, INT_LITERAL__VAL);

    variableDeclarationEClass = createEClass(VARIABLE_DECLARATION);
    createEAttribute(variableDeclarationEClass, VARIABLE_DECLARATION__NAME);
    createEAttribute(variableDeclarationEClass, VARIABLE_DECLARATION__VALUE);

    intVarExpressionEClass = createEClass(INT_VAR_EXPRESSION);
    createEReference(intVarExpressionEClass, INT_VAR_EXPRESSION__VAR);

    additionEClass = createEClass(ADDITION);
    createEReference(additionEClass, ADDITION__LEFT);
    createEAttribute(additionEClass, ADDITION__OPERATOR);
    createEReference(additionEClass, ADDITION__RIGHT);

    multiplicationEClass = createEClass(MULTIPLICATION);
    createEReference(multiplicationEClass, MULTIPLICATION__LEFT);
    createEAttribute(multiplicationEClass, MULTIPLICATION__OPERATOR);
    createEReference(multiplicationEClass, MULTIPLICATION__RIGHT);

    // Create enums
    fancyMakeStatementEEnum = createEEnum(FANCY_MAKE_STATEMENT);
    iceStatementEEnum = createEEnum(ICE_STATEMENT);
    fruitStatementEEnum = createEEnum(FRUIT_STATEMENT);
    decorationStatementEEnum = createEEnum(DECORATION_STATEMENT);
    makeCommandEEnum = createEEnum(MAKE_COMMAND);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private boolean isInitialized = false;

  /**
   * Complete the initialization of the package and its meta-model.  This
   * method is guarded to have no affect on any invocation but its first.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void initializePackageContents()
  {
    if (isInitialized) return;
    isInitialized = true;

    // Initialize package
    setName(eNAME);
    setNsPrefix(eNS_PREFIX);
    setNsURI(eNS_URI);

    // Create type parameters

    // Set bounds for type parameters

    // Add supertypes to classes
    addIngredientEClass.getESuperTypes().add(this.getInstruction());
    addFixedIngredientEClass.getESuperTypes().add(this.getInstruction());
    fancyStatementEClass.getESuperTypes().add(this.getInstruction());
    addIceEClass.getESuperTypes().add(this.getInstruction());
    muddleStatementEClass.getESuperTypes().add(this.getInstruction());
    addDecorationEClass.getESuperTypes().add(this.getInstruction());
    makeStatementEClass.getESuperTypes().add(this.getInstruction());
    intLiteralEClass.getESuperTypes().add(this.getExpression());
    variableDeclarationEClass.getESuperTypes().add(this.getInstruction());
    intVarExpressionEClass.getESuperTypes().add(this.getExpression());
    additionEClass.getESuperTypes().add(this.getExpression());
    multiplicationEClass.getESuperTypes().add(this.getExpression());

    // Initialize classes and features; add operations and parameters
    initEClass(orderEClass, Order.class, "Order", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getOrder_Instructions(), this.getInstruction(), null, "instructions", null, 0, -1, Order.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(instructionEClass, Instruction.class, "Instruction", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(addIngredientEClass, AddIngredient.class, "AddIngredient", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAddIngredient_Name(), ecorePackage.getEString(), "name", null, 0, 1, AddIngredient.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAddIngredient_Amount(), this.getExpression(), null, "amount", null, 0, 1, AddIngredient.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(addFixedIngredientEClass, AddFixedIngredient.class, "AddFixedIngredient", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAddFixedIngredient_Name(), ecorePackage.getEString(), "name", null, 0, 1, AddFixedIngredient.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAddFixedIngredient_Amount(), this.getExpression(), null, "amount", null, 0, 1, AddFixedIngredient.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(fancyStatementEClass, FancyStatement.class, "FancyStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getFancyStatement_Fcommand(), this.getFancyMakeStatement(), "fcommand", null, 0, 1, FancyStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(addIceEClass, AddIce.class, "AddIce", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAddIce_Ice(), this.getIceStatement(), "ice", null, 0, 1, AddIce.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAddIce_Ounce(), this.getExpression(), null, "ounce", null, 0, 1, AddIce.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(muddleStatementEClass, MuddleStatement.class, "MuddleStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMuddleStatement_MudFruit(), this.getFruitStatement(), "mudFruit", null, 0, -1, MuddleStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMuddleStatement_Mtimes(), this.getExpression(), null, "mtimes", null, 0, 1, MuddleStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(addDecorationEClass, AddDecoration.class, "AddDecoration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getAddDecoration_Decoration(), this.getDecorationStatement(), "decoration", null, 0, 1, AddDecoration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAddDecoration_Slice(), this.getExpression(), null, "slice", null, 0, 1, AddDecoration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(makeStatementEClass, MakeStatement.class, "MakeStatement", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getMakeStatement_Make(), this.getMakeCommand(), "make", null, 0, 1, MakeStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMakeStatement_Time(), this.getExpression(), null, "time", null, 0, 1, MakeStatement.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(expressionEClass, Expression.class, "Expression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);

    initEClass(intLiteralEClass, IntLiteral.class, "IntLiteral", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getIntLiteral_Val(), ecorePackage.getEInt(), "val", null, 0, 1, IntLiteral.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(variableDeclarationEClass, VariableDeclaration.class, "VariableDeclaration", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEAttribute(getVariableDeclaration_Name(), ecorePackage.getEString(), "name", null, 0, 1, VariableDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getVariableDeclaration_Value(), ecorePackage.getEInt(), "value", null, 0, 1, VariableDeclaration.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(intVarExpressionEClass, IntVarExpression.class, "IntVarExpression", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getIntVarExpression_Var(), this.getVariableDeclaration(), null, "var", null, 0, 1, IntVarExpression.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_COMPOSITE, IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(additionEClass, Addition.class, "Addition", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getAddition_Left(), this.getExpression(), null, "left", null, 0, 1, Addition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getAddition_Operator(), ecorePackage.getEString(), "operator", null, 0, -1, Addition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getAddition_Right(), this.getExpression(), null, "right", null, 0, -1, Addition.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    initEClass(multiplicationEClass, Multiplication.class, "Multiplication", !IS_ABSTRACT, !IS_INTERFACE, IS_GENERATED_INSTANCE_CLASS);
    initEReference(getMultiplication_Left(), this.getExpression(), null, "left", null, 0, 1, Multiplication.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEAttribute(getMultiplication_Operator(), ecorePackage.getEString(), "operator", null, 0, -1, Multiplication.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, !IS_UNSETTABLE, !IS_ID, !IS_UNIQUE, !IS_DERIVED, IS_ORDERED);
    initEReference(getMultiplication_Right(), this.getExpression(), null, "right", null, 0, -1, Multiplication.class, !IS_TRANSIENT, !IS_VOLATILE, IS_CHANGEABLE, IS_COMPOSITE, !IS_RESOLVE_PROXIES, !IS_UNSETTABLE, IS_UNIQUE, !IS_DERIVED, IS_ORDERED);

    // Initialize enums and add enum literals
    initEEnum(fancyMakeStatementEEnum, FancyMakeStatement.class, "FancyMakeStatement");
    addEEnumLiteral(fancyMakeStatementEEnum, FancyMakeStatement.LIGHTER);
    addEEnumLiteral(fancyMakeStatementEEnum, FancyMakeStatement.CO2);

    initEEnum(iceStatementEEnum, IceStatement.class, "IceStatement");
    addEEnumLiteral(iceStatementEEnum, IceStatement.CUBE);
    addEEnumLiteral(iceStatementEEnum, IceStatement.CRUSH);
    addEEnumLiteral(iceStatementEEnum, IceStatement.SHAVE);
    addEEnumLiteral(iceStatementEEnum, IceStatement.BLOCK);
    addEEnumLiteral(iceStatementEEnum, IceStatement.BALL);
    addEEnumLiteral(iceStatementEEnum, IceStatement.CONE);

    initEEnum(fruitStatementEEnum, FruitStatement.class, "FruitStatement");
    addEEnumLiteral(fruitStatementEEnum, FruitStatement.LIME);
    addEEnumLiteral(fruitStatementEEnum, FruitStatement.LEMON);
    addEEnumLiteral(fruitStatementEEnum, FruitStatement.ORANGE);
    addEEnumLiteral(fruitStatementEEnum, FruitStatement.GRAPEFRUIT);
    addEEnumLiteral(fruitStatementEEnum, FruitStatement.PINEAPPLE);
    addEEnumLiteral(fruitStatementEEnum, FruitStatement.MANGO);
    addEEnumLiteral(fruitStatementEEnum, FruitStatement.KIWI);
    addEEnumLiteral(fruitStatementEEnum, FruitStatement.STRAWBERRY);
    addEEnumLiteral(fruitStatementEEnum, FruitStatement.BLUEBERRY);
    addEEnumLiteral(fruitStatementEEnum, FruitStatement.RASPBERRY);
    addEEnumLiteral(fruitStatementEEnum, FruitStatement.BLACKBERRY);
    addEEnumLiteral(fruitStatementEEnum, FruitStatement.CHERRY);
    addEEnumLiteral(fruitStatementEEnum, FruitStatement.PEACH);
    addEEnumLiteral(fruitStatementEEnum, FruitStatement.PLUM);
    addEEnumLiteral(fruitStatementEEnum, FruitStatement.WATERMELON);
    addEEnumLiteral(fruitStatementEEnum, FruitStatement.CUCUMBER);
    addEEnumLiteral(fruitStatementEEnum, FruitStatement.MINT);
    addEEnumLiteral(fruitStatementEEnum, FruitStatement.BASIL);
    addEEnumLiteral(fruitStatementEEnum, FruitStatement.THYME);
    addEEnumLiteral(fruitStatementEEnum, FruitStatement.GINGER);

    initEEnum(decorationStatementEEnum, DecorationStatement.class, "DecorationStatement");
    addEEnumLiteral(decorationStatementEEnum, DecorationStatement.ORANGE);
    addEEnumLiteral(decorationStatementEEnum, DecorationStatement.LEMON);
    addEEnumLiteral(decorationStatementEEnum, DecorationStatement.LIME);
    addEEnumLiteral(decorationStatementEEnum, DecorationStatement.OLIVE);
    addEEnumLiteral(decorationStatementEEnum, DecorationStatement.CHERRY);
    addEEnumLiteral(decorationStatementEEnum, DecorationStatement.MINT);
    addEEnumLiteral(decorationStatementEEnum, DecorationStatement.ROSE);
    addEEnumLiteral(decorationStatementEEnum, DecorationStatement.CINNAMON);
    addEEnumLiteral(decorationStatementEEnum, DecorationStatement.MANGO);
    addEEnumLiteral(decorationStatementEEnum, DecorationStatement.GRAPEFRUIT);

    initEEnum(makeCommandEEnum, MakeCommand.class, "MakeCommand");
    addEEnumLiteral(makeCommandEEnum, MakeCommand.STIR);
    addEEnumLiteral(makeCommandEEnum, MakeCommand.SHAKE);
    addEEnumLiteral(makeCommandEEnum, MakeCommand.BLEND);
    addEEnumLiteral(makeCommandEEnum, MakeCommand.FILTER);

    // Create resource
    createResource(eNS_URI);
  }

} //CocktailsPackageImpl
