/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.cocktails.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EDataType;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.xtext.example.mydsl.cocktails.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class CocktailsFactoryImpl extends EFactoryImpl implements CocktailsFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static CocktailsFactory init()
  {
    try
    {
      CocktailsFactory theCocktailsFactory = (CocktailsFactory)EPackage.Registry.INSTANCE.getEFactory(CocktailsPackage.eNS_URI);
      if (theCocktailsFactory != null)
      {
        return theCocktailsFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new CocktailsFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CocktailsFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case CocktailsPackage.ORDER: return createOrder();
      case CocktailsPackage.INSTRUCTION: return createInstruction();
      case CocktailsPackage.ADD_INGREDIENT: return createAddIngredient();
      case CocktailsPackage.ADD_FIXED_INGREDIENT: return createAddFixedIngredient();
      case CocktailsPackage.FANCY_STATEMENT: return createFancyStatement();
      case CocktailsPackage.ADD_ICE: return createAddIce();
      case CocktailsPackage.MUDDLE_STATEMENT: return createMuddleStatement();
      case CocktailsPackage.ADD_DECORATION: return createAddDecoration();
      case CocktailsPackage.MAKE_STATEMENT: return createMakeStatement();
      case CocktailsPackage.EXPRESSION: return createExpression();
      case CocktailsPackage.INT_LITERAL: return createIntLiteral();
      case CocktailsPackage.VARIABLE_DECLARATION: return createVariableDeclaration();
      case CocktailsPackage.INT_VAR_EXPRESSION: return createIntVarExpression();
      case CocktailsPackage.ADDITION: return createAddition();
      case CocktailsPackage.MULTIPLICATION: return createMultiplication();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object createFromString(EDataType eDataType, String initialValue)
  {
    switch (eDataType.getClassifierID())
    {
      case CocktailsPackage.FANCY_MAKE_STATEMENT:
        return createFancyMakeStatementFromString(eDataType, initialValue);
      case CocktailsPackage.ICE_STATEMENT:
        return createIceStatementFromString(eDataType, initialValue);
      case CocktailsPackage.FRUIT_STATEMENT:
        return createFruitStatementFromString(eDataType, initialValue);
      case CocktailsPackage.DECORATION_STATEMENT:
        return createDecorationStatementFromString(eDataType, initialValue);
      case CocktailsPackage.MAKE_COMMAND:
        return createMakeCommandFromString(eDataType, initialValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String convertToString(EDataType eDataType, Object instanceValue)
  {
    switch (eDataType.getClassifierID())
    {
      case CocktailsPackage.FANCY_MAKE_STATEMENT:
        return convertFancyMakeStatementToString(eDataType, instanceValue);
      case CocktailsPackage.ICE_STATEMENT:
        return convertIceStatementToString(eDataType, instanceValue);
      case CocktailsPackage.FRUIT_STATEMENT:
        return convertFruitStatementToString(eDataType, instanceValue);
      case CocktailsPackage.DECORATION_STATEMENT:
        return convertDecorationStatementToString(eDataType, instanceValue);
      case CocktailsPackage.MAKE_COMMAND:
        return convertMakeCommandToString(eDataType, instanceValue);
      default:
        throw new IllegalArgumentException("The datatype '" + eDataType.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Order createOrder()
  {
    OrderImpl order = new OrderImpl();
    return order;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Instruction createInstruction()
  {
    InstructionImpl instruction = new InstructionImpl();
    return instruction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AddIngredient createAddIngredient()
  {
    AddIngredientImpl addIngredient = new AddIngredientImpl();
    return addIngredient;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AddFixedIngredient createAddFixedIngredient()
  {
    AddFixedIngredientImpl addFixedIngredient = new AddFixedIngredientImpl();
    return addFixedIngredient;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FancyStatement createFancyStatement()
  {
    FancyStatementImpl fancyStatement = new FancyStatementImpl();
    return fancyStatement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AddIce createAddIce()
  {
    AddIceImpl addIce = new AddIceImpl();
    return addIce;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MuddleStatement createMuddleStatement()
  {
    MuddleStatementImpl muddleStatement = new MuddleStatementImpl();
    return muddleStatement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public AddDecoration createAddDecoration()
  {
    AddDecorationImpl addDecoration = new AddDecorationImpl();
    return addDecoration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public MakeStatement createMakeStatement()
  {
    MakeStatementImpl makeStatement = new MakeStatementImpl();
    return makeStatement;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression createExpression()
  {
    ExpressionImpl expression = new ExpressionImpl();
    return expression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntLiteral createIntLiteral()
  {
    IntLiteralImpl intLiteral = new IntLiteralImpl();
    return intLiteral;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public VariableDeclaration createVariableDeclaration()
  {
    VariableDeclarationImpl variableDeclaration = new VariableDeclarationImpl();
    return variableDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public IntVarExpression createIntVarExpression()
  {
    IntVarExpressionImpl intVarExpression = new IntVarExpressionImpl();
    return intVarExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Addition createAddition()
  {
    AdditionImpl addition = new AdditionImpl();
    return addition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Multiplication createMultiplication()
  {
    MultiplicationImpl multiplication = new MultiplicationImpl();
    return multiplication;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FancyMakeStatement createFancyMakeStatementFromString(EDataType eDataType, String initialValue)
  {
    FancyMakeStatement result = FancyMakeStatement.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertFancyMakeStatementToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IceStatement createIceStatementFromString(EDataType eDataType, String initialValue)
  {
    IceStatement result = IceStatement.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertIceStatementToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FruitStatement createFruitStatementFromString(EDataType eDataType, String initialValue)
  {
    FruitStatement result = FruitStatement.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertFruitStatementToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public DecorationStatement createDecorationStatementFromString(EDataType eDataType, String initialValue)
  {
    DecorationStatement result = DecorationStatement.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertDecorationStatementToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MakeCommand createMakeCommandFromString(EDataType eDataType, String initialValue)
  {
    MakeCommand result = MakeCommand.get(initialValue);
    if (result == null) throw new IllegalArgumentException("The value '" + initialValue + "' is not a valid enumerator of '" + eDataType.getName() + "'");
    return result;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String convertMakeCommandToString(EDataType eDataType, Object instanceValue)
  {
    return instanceValue == null ? null : instanceValue.toString();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CocktailsPackage getCocktailsPackage()
  {
    return (CocktailsPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static CocktailsPackage getPackage()
  {
    return CocktailsPackage.eINSTANCE;
  }

} //CocktailsFactoryImpl
