/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.cocktails.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.example.mydsl.cocktails.CocktailsPackage;
import org.xtext.example.mydsl.cocktails.FancyMakeStatement;
import org.xtext.example.mydsl.cocktails.FancyStatement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Fancy Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.cocktails.impl.FancyStatementImpl#getFcommand <em>Fcommand</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FancyStatementImpl extends InstructionImpl implements FancyStatement
{
  /**
   * The default value of the '{@link #getFcommand() <em>Fcommand</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFcommand()
   * @generated
   * @ordered
   */
  protected static final FancyMakeStatement FCOMMAND_EDEFAULT = FancyMakeStatement.LIGHTER;

  /**
   * The cached value of the '{@link #getFcommand() <em>Fcommand</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFcommand()
   * @generated
   * @ordered
   */
  protected FancyMakeStatement fcommand = FCOMMAND_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FancyStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CocktailsPackage.Literals.FANCY_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FancyMakeStatement getFcommand()
  {
    return fcommand;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setFcommand(FancyMakeStatement newFcommand)
  {
    FancyMakeStatement oldFcommand = fcommand;
    fcommand = newFcommand == null ? FCOMMAND_EDEFAULT : newFcommand;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CocktailsPackage.FANCY_STATEMENT__FCOMMAND, oldFcommand, fcommand));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CocktailsPackage.FANCY_STATEMENT__FCOMMAND:
        return getFcommand();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CocktailsPackage.FANCY_STATEMENT__FCOMMAND:
        setFcommand((FancyMakeStatement)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CocktailsPackage.FANCY_STATEMENT__FCOMMAND:
        setFcommand(FCOMMAND_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CocktailsPackage.FANCY_STATEMENT__FCOMMAND:
        return fcommand != FCOMMAND_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (fcommand: ");
    result.append(fcommand);
    result.append(')');
    return result.toString();
  }

} //FancyStatementImpl
