/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.cocktails.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EDataTypeEList;

import org.xtext.example.mydsl.cocktails.CocktailsPackage;
import org.xtext.example.mydsl.cocktails.Expression;
import org.xtext.example.mydsl.cocktails.FruitStatement;
import org.xtext.example.mydsl.cocktails.MuddleStatement;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Muddle Statement</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.cocktails.impl.MuddleStatementImpl#getMudFruit <em>Mud Fruit</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.cocktails.impl.MuddleStatementImpl#getMtimes <em>Mtimes</em>}</li>
 * </ul>
 *
 * @generated
 */
public class MuddleStatementImpl extends InstructionImpl implements MuddleStatement
{
  /**
   * The cached value of the '{@link #getMudFruit() <em>Mud Fruit</em>}' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMudFruit()
   * @generated
   * @ordered
   */
  protected EList<FruitStatement> mudFruit;

  /**
   * The cached value of the '{@link #getMtimes() <em>Mtimes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMtimes()
   * @generated
   * @ordered
   */
  protected Expression mtimes;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected MuddleStatementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return CocktailsPackage.Literals.MUDDLE_STATEMENT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<FruitStatement> getMudFruit()
  {
    if (mudFruit == null)
    {
      mudFruit = new EDataTypeEList<FruitStatement>(FruitStatement.class, this, CocktailsPackage.MUDDLE_STATEMENT__MUD_FRUIT);
    }
    return mudFruit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Expression getMtimes()
  {
    return mtimes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetMtimes(Expression newMtimes, NotificationChain msgs)
  {
    Expression oldMtimes = mtimes;
    mtimes = newMtimes;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, CocktailsPackage.MUDDLE_STATEMENT__MTIMES, oldMtimes, newMtimes);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setMtimes(Expression newMtimes)
  {
    if (newMtimes != mtimes)
    {
      NotificationChain msgs = null;
      if (mtimes != null)
        msgs = ((InternalEObject)mtimes).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - CocktailsPackage.MUDDLE_STATEMENT__MTIMES, null, msgs);
      if (newMtimes != null)
        msgs = ((InternalEObject)newMtimes).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - CocktailsPackage.MUDDLE_STATEMENT__MTIMES, null, msgs);
      msgs = basicSetMtimes(newMtimes, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, CocktailsPackage.MUDDLE_STATEMENT__MTIMES, newMtimes, newMtimes));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case CocktailsPackage.MUDDLE_STATEMENT__MTIMES:
        return basicSetMtimes(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case CocktailsPackage.MUDDLE_STATEMENT__MUD_FRUIT:
        return getMudFruit();
      case CocktailsPackage.MUDDLE_STATEMENT__MTIMES:
        return getMtimes();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case CocktailsPackage.MUDDLE_STATEMENT__MUD_FRUIT:
        getMudFruit().clear();
        getMudFruit().addAll((Collection<? extends FruitStatement>)newValue);
        return;
      case CocktailsPackage.MUDDLE_STATEMENT__MTIMES:
        setMtimes((Expression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case CocktailsPackage.MUDDLE_STATEMENT__MUD_FRUIT:
        getMudFruit().clear();
        return;
      case CocktailsPackage.MUDDLE_STATEMENT__MTIMES:
        setMtimes((Expression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case CocktailsPackage.MUDDLE_STATEMENT__MUD_FRUIT:
        return mudFruit != null && !mudFruit.isEmpty();
      case CocktailsPackage.MUDDLE_STATEMENT__MTIMES:
        return mtimes != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (mudFruit: ");
    result.append(mudFruit);
    result.append(')');
    return result.toString();
  }

} //MuddleStatementImpl
