/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.generator;

import com.google.common.base.Objects;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.epsilon.emc.emf.EmfModel;
import org.eclipse.epsilon.eol.models.IModel;
import org.eclipse.xtend2.lib.StringConcatenation;
import org.eclipse.xtext.generator.AbstractGenerator;
import org.eclipse.xtext.generator.IFileSystemAccess2;
import org.eclipse.xtext.generator.IGeneratorContext;
import org.eclipse.xtext.xbase.lib.CollectionLiterals;
import org.eclipse.xtext.xbase.lib.Exceptions;
import org.eclipse.xtext.xbase.lib.Functions.Function1;
import org.eclipse.xtext.xbase.lib.IntegerRange;
import org.eclipse.xtext.xbase.lib.IterableExtensions;
import org.eclipse.xtext.xbase.lib.ListExtensions;
import org.eclipse.xtext.xbase.lib.StringExtensions;
import org.xtext.example.mydsl.cocktails.AddDecoration;
import org.xtext.example.mydsl.cocktails.AddFixedIngredient;
import org.xtext.example.mydsl.cocktails.AddIce;
import org.xtext.example.mydsl.cocktails.AddIngredient;
import org.xtext.example.mydsl.cocktails.Addition;
import org.xtext.example.mydsl.cocktails.CocktailsPackage;
import org.xtext.example.mydsl.cocktails.Expression;
import org.xtext.example.mydsl.cocktails.FancyStatement;
import org.xtext.example.mydsl.cocktails.Instruction;
import org.xtext.example.mydsl.cocktails.IntLiteral;
import org.xtext.example.mydsl.cocktails.MakeStatement;
import org.xtext.example.mydsl.cocktails.MuddleStatement;
import org.xtext.example.mydsl.cocktails.Multiplication;
import org.xtext.example.mydsl.cocktails.Order;

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
@SuppressWarnings("all")
public class CocktailsGenerator extends AbstractGenerator {
  private static class ConstantFolder extends ETLRunner {
    private final Resource inModel;

    public ConstantFolder(final Resource inModel) {
      this.inModel = inModel;
    }

    @Override
    protected String getSource() {
      return "constant_fold.etl";
    }

    @Override
    protected List<IModel> getModels() throws Exception {
      List<IModel> _xblockexpression = null;
      {
        final EmfModel srcModel = this.createInMemoryEmfModel(this.inModel, "Source", CocktailsPackage.eNS_URI);
        final ResourceSet resourceSet = this.inModel.getResourceSet();
        final URI tgtResourceURI = URI.createFileURI("synthetic.cocktails");
        Resource tgtResource = resourceSet.getResource(tgtResourceURI, false);
        boolean _notEquals = (!Objects.equal(tgtResource, null));
        if (_notEquals) {
          tgtResource.getContents().clear();
        } else {
          tgtResource = resourceSet.createResource(tgtResourceURI);
        }
        final EmfModel tgtModel = this.createInMemoryEmfModel(tgtResource, "Target", CocktailsPackage.eNS_URI);
        _xblockexpression = Collections.<IModel>unmodifiableList(CollectionLiterals.<IModel>newArrayList(srcModel, tgtModel));
      }
      return _xblockexpression;
    }
  }

  private static class Environment {
    private int counter = 0;

    public CharSequence getFreshVarName() {
      StringConcatenation _builder = new StringConcatenation();
      _builder.append("i");
      int _plusPlus = this.counter++;
      _builder.append(_plusPlus);
      return _builder;
    }

    public int exit() {
      return this.counter--;
    }
  }

  @Override
  public void doGenerate(final Resource resource, final IFileSystemAccess2 fsa, final IGeneratorContext context) {
    try {
      EObject _head = IterableExtensions.<EObject>head(resource.getContents());
      final Order model = ((Order) _head);
      final String className = this.deriveClassName(resource);
      EObject _execute = new CocktailsGenerator.ConstantFolder(resource).execute();
      final Order interimModel = ((Order) _execute);
      fsa.generateFile((className + ".java"), this.doGenerateClass(interimModel, className));
    } catch (Throwable _e) {
      throw Exceptions.sneakyThrow(_e);
    }
  }

  public String deriveClassName(final Resource resource) {
    String _xblockexpression = null;
    {
      final String originFilename = resource.getURI().lastSegment();
      String _firstUpper = StringExtensions.toFirstUpper(originFilename.substring(0, originFilename.indexOf(".")));
      _xblockexpression = (_firstUpper + "Cocktail");
    }
    return _xblockexpression;
  }

  public CharSequence doGenerateClass(final Order order, final String className) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.newLine();
    _builder.newLine();
    _builder.append("public class ");
    _builder.append(className);
    _builder.append("{");
    _builder.newLineIfNotEmpty();
    _builder.append("\t");
    _builder.append("public static void main(String[] args){");
    _builder.newLine();
    _builder.append("\t\t");
    _builder.append("int count=1;");
    _builder.newLine();
    _builder.append("\t\t");
    final Function1<Instruction, String> _function = (Instruction it) -> {
      CocktailsGenerator.Environment _environment = new CocktailsGenerator.Environment();
      return this.generateJavaStatement(it, _environment);
    };
    String _join = IterableExtensions.join(ListExtensions.<Instruction, String>map(order.getInstructions(), _function), "\n");
    _builder.append(_join, "\t\t");
    _builder.newLineIfNotEmpty();
    _builder.append("\t\t");
    _builder.newLine();
    _builder.append("\t");
    _builder.append("}");
    _builder.newLine();
    _builder.append("\t");
    _builder.newLine();
    _builder.append("}");
    _builder.newLine();
    return _builder;
  }

  protected String _generateJavaStatement(final Instruction ins, final CocktailsGenerator.Environment env) {
    StringConcatenation _builder = new StringConcatenation();
    return _builder.toString();
  }

  protected String _generateJavaStatement(final MakeStatement ins, final CocktailsGenerator.Environment env) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("System.out.println(\"Step\"+count+\":\\n");
    String _firstUpper = StringExtensions.toFirstUpper(ins.getMake().getName());
    _builder.append(_firstUpper);
    _builder.append(" it for ");
    String _generateJavaExpression = this.generateJavaExpression(ins.getTime());
    _builder.append(_generateJavaExpression);
    _builder.append(" seconds\");");
    _builder.newLineIfNotEmpty();
    _builder.append("count++;");
    return _builder.toString();
  }

  protected String _generateJavaStatement(final AddIngredient ins, final CocktailsGenerator.Environment env) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.newLine();
    _builder.append("System.out.println(\"Step\"+count+\":\\nadd ingredient ");
    String _firstUpper = StringExtensions.toFirstUpper(ins.getName());
    _builder.append(_firstUpper);
    _builder.append(" for ");
    String _generateJavaExpression = this.generateJavaExpression(ins.getAmount());
    _builder.append(_generateJavaExpression);
    _builder.append(" ml\");");
    _builder.newLineIfNotEmpty();
    _builder.append("count++;");
    return _builder.toString();
  }

  protected String _generateJavaStatement(final AddFixedIngredient ins, final CocktailsGenerator.Environment env) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("System.out.println(\"Step\"+count+\":\\nadd ingredient ");
    String _firstUpper = StringExtensions.toFirstUpper(ins.getName());
    _builder.append(_firstUpper);
    _builder.append(" for ");
    String _generateJavaExpression = this.generateJavaExpression(ins.getAmount());
    _builder.append(_generateJavaExpression);
    _builder.append(" grams\");");
    _builder.newLineIfNotEmpty();
    _builder.append("count++;");
    return _builder.toString();
  }

  protected String _generateJavaStatement(final FancyStatement ins, final CocktailsGenerator.Environment env) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("System.out.println(\"Step\"+count+\":\\nuse ");
    String _firstUpper = StringExtensions.toFirstUpper(ins.getFcommand().getName());
    _builder.append(_firstUpper);
    _builder.append("\");");
    _builder.newLineIfNotEmpty();
    _builder.append("count++;");
    return _builder.toString();
  }

  protected String _generateJavaStatement(final MuddleStatement ins, final CocktailsGenerator.Environment env) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("System.out.println(\"Step\"+count+\":\\nuse mud machine to mud: \\n");
    {
      int _size = ins.getMudFruit().size();
      int _minus = (_size - 1);
      IntegerRange _upTo = new IntegerRange(0, _minus);
      for(final Integer idx : _upTo) {
        String _firstUpper = StringExtensions.toFirstUpper(ins.getMudFruit().get((idx).intValue()).getName());
        _builder.append(_firstUpper);
        {
          int _size_1 = ins.getMudFruit().size();
          int _minus_1 = (_size_1 - 1);
          boolean _equals = ((idx).intValue() == _minus_1);
          if (_equals) {
          } else {
            _builder.append("+ ");
          }
        }
      }
    }
    _builder.append("\\nfor ");
    String _generateJavaExpression = this.generateJavaExpression(ins.getMtimes());
    _builder.append(_generateJavaExpression);
    _builder.append(" times\");");
    _builder.newLineIfNotEmpty();
    _builder.append("count++;");
    return _builder.toString();
  }

  protected String _generateJavaStatement(final AddIce ins, final CocktailsGenerator.Environment env) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("System.out.println(\"Step\"+count+\":\\nput ");
    String _generateJavaExpression = this.generateJavaExpression(ins.getOunce());
    _builder.append(_generateJavaExpression);
    _builder.append(" ounce ");
    String _firstUpper = StringExtensions.toFirstUpper(ins.getIce().getName());
    _builder.append(_firstUpper);
    _builder.append(" ice\");");
    _builder.newLineIfNotEmpty();
    _builder.append("count++;");
    return _builder.toString();
  }

  protected String _generateJavaStatement(final AddDecoration ins, final CocktailsGenerator.Environment env) {
    StringConcatenation _builder = new StringConcatenation();
    _builder.append("System.out.println(\"Step\"+count+\":\\nput ");
    String _firstUpper = StringExtensions.toFirstUpper(ins.getDecoration().getName());
    _builder.append(_firstUpper);
    _builder.append(" ");
    String _generateJavaExpression = this.generateJavaExpression(ins.getSlice());
    _builder.append(_generateJavaExpression);
    _builder.append(" piece on the top of cocktail\");");
    _builder.newLineIfNotEmpty();
    _builder.append("count++;");
    return _builder.toString();
  }

  protected String _generateJavaExpression(final Expression exp) {
    StringConcatenation _builder = new StringConcatenation();
    return _builder.toString();
  }

  protected String _generateJavaExpression(final Addition exp) {
    StringConcatenation _builder = new StringConcatenation();
    String _generateJavaExpression = this.generateJavaExpression(exp.getLeft());
    _builder.append(_generateJavaExpression);
    {
      int _size = exp.getOperator().size();
      int _minus = (_size - 1);
      IntegerRange _upTo = new IntegerRange(0, _minus);
      for(final Integer idx : _upTo) {
        String _get = exp.getOperator().get((idx).intValue());
        _builder.append(_get);
        String _generateJavaExpression_1 = this.generateJavaExpression(exp.getRight().get((idx).intValue()));
        _builder.append(_generateJavaExpression_1);
      }
    }
    return _builder.toString();
  }

  protected String _generateJavaExpression(final Multiplication exp) {
    StringConcatenation _builder = new StringConcatenation();
    String _generateJavaExpression = this.generateJavaExpression(exp.getLeft());
    _builder.append(_generateJavaExpression);
    {
      int _size = exp.getOperator().size();
      int _minus = (_size - 1);
      IntegerRange _upTo = new IntegerRange(0, _minus);
      for(final Integer idx : _upTo) {
        String _get = exp.getOperator().get((idx).intValue());
        _builder.append(_get);
        String _generateJavaExpression_1 = this.generateJavaExpression(exp.getRight().get((idx).intValue()));
        _builder.append(_generateJavaExpression_1);
      }
    }
    return _builder.toString();
  }

  protected String _generateJavaExpression(final IntLiteral exp) {
    StringConcatenation _builder = new StringConcatenation();
    int _val = exp.getVal();
    _builder.append(_val);
    return _builder.toString();
  }

  public String generateJavaStatement(final Instruction ins, final CocktailsGenerator.Environment env) {
    if (ins instanceof AddDecoration) {
      return _generateJavaStatement((AddDecoration)ins, env);
    } else if (ins instanceof AddFixedIngredient) {
      return _generateJavaStatement((AddFixedIngredient)ins, env);
    } else if (ins instanceof AddIce) {
      return _generateJavaStatement((AddIce)ins, env);
    } else if (ins instanceof AddIngredient) {
      return _generateJavaStatement((AddIngredient)ins, env);
    } else if (ins instanceof FancyStatement) {
      return _generateJavaStatement((FancyStatement)ins, env);
    } else if (ins instanceof MakeStatement) {
      return _generateJavaStatement((MakeStatement)ins, env);
    } else if (ins instanceof MuddleStatement) {
      return _generateJavaStatement((MuddleStatement)ins, env);
    } else if (ins != null) {
      return _generateJavaStatement(ins, env);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(ins, env).toString());
    }
  }

  public String generateJavaExpression(final Expression exp) {
    if (exp instanceof Addition) {
      return _generateJavaExpression((Addition)exp);
    } else if (exp instanceof IntLiteral) {
      return _generateJavaExpression((IntLiteral)exp);
    } else if (exp instanceof Multiplication) {
      return _generateJavaExpression((Multiplication)exp);
    } else if (exp != null) {
      return _generateJavaExpression(exp);
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(exp).toString());
    }
  }
}
