/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.services;

import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.List;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Alternatives;
import org.eclipse.xtext.Assignment;
import org.eclipse.xtext.CrossReference;
import org.eclipse.xtext.EnumLiteralDeclaration;
import org.eclipse.xtext.EnumRule;
import org.eclipse.xtext.Grammar;
import org.eclipse.xtext.GrammarUtil;
import org.eclipse.xtext.Group;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.TerminalRule;
import org.eclipse.xtext.common.services.TerminalsGrammarAccess;
import org.eclipse.xtext.service.AbstractElementFinder;
import org.eclipse.xtext.service.GrammarProvider;

@Singleton
public class CocktailsGrammarAccess extends AbstractElementFinder.AbstractGrammarElementFinder {
	
	public class OrderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Cocktails.Order");
		private final Assignment cInstructionsAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cInstructionsInstructionParserRuleCall_0 = (RuleCall)cInstructionsAssignment.eContents().get(0);
		
		//Order:
		//    instructions+=Instruction*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//instructions+=Instruction*
		public Assignment getInstructionsAssignment() { return cInstructionsAssignment; }
		
		//Instruction
		public RuleCall getInstructionsInstructionParserRuleCall_0() { return cInstructionsInstructionParserRuleCall_0; }
	}
	public class InstructionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Cocktails.Instruction");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cAddIngredientParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cAddFixedIngredientParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cFancyStatementParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cAddIceParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cMuddleStatementParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cAddDecorationParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		private final RuleCall cMakeStatementParserRuleCall_6 = (RuleCall)cAlternatives.eContents().get(6);
		private final RuleCall cVariableDeclarationParserRuleCall_7 = (RuleCall)cAlternatives.eContents().get(7);
		
		//Instruction:
		//    AddIngredient|
		//    AddFixedIngredient|
		//    FancyStatement|
		//    AddIce|
		//    MuddleStatement|
		//    AddDecoration|
		//    MakeStatement|
		//    VariableDeclaration
		//    //    AddFruitformuddle |
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//AddIngredient|
		//AddFixedIngredient|
		//FancyStatement|
		//AddIce|
		//MuddleStatement|
		//AddDecoration|
		//MakeStatement|
		//VariableDeclaration
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//AddIngredient
		public RuleCall getAddIngredientParserRuleCall_0() { return cAddIngredientParserRuleCall_0; }
		
		//AddFixedIngredient
		public RuleCall getAddFixedIngredientParserRuleCall_1() { return cAddFixedIngredientParserRuleCall_1; }
		
		//FancyStatement
		public RuleCall getFancyStatementParserRuleCall_2() { return cFancyStatementParserRuleCall_2; }
		
		//AddIce
		public RuleCall getAddIceParserRuleCall_3() { return cAddIceParserRuleCall_3; }
		
		//MuddleStatement
		public RuleCall getMuddleStatementParserRuleCall_4() { return cMuddleStatementParserRuleCall_4; }
		
		//AddDecoration
		public RuleCall getAddDecorationParserRuleCall_5() { return cAddDecorationParserRuleCall_5; }
		
		//MakeStatement
		public RuleCall getMakeStatementParserRuleCall_6() { return cMakeStatementParserRuleCall_6; }
		
		//VariableDeclaration
		public RuleCall getVariableDeclarationParserRuleCall_7() { return cVariableDeclarationParserRuleCall_7; }
	}
	public class AddIngredientElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Cocktails.AddIngredient");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAddIKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAmountAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAmountAdditionParserRuleCall_3_0 = (RuleCall)cAmountAssignment_3.eContents().get(0);
		private final Keyword cMlKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//AddIngredient:
		//    "addI" name=ID ":" amount=Addition "ml"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"addI" name=ID ":" amount=Addition "ml"
		public Group getGroup() { return cGroup; }
		
		//"addI"
		public Keyword getAddIKeyword_0() { return cAddIKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//amount=Addition
		public Assignment getAmountAssignment_3() { return cAmountAssignment_3; }
		
		//Addition
		public RuleCall getAmountAdditionParserRuleCall_3_0() { return cAmountAdditionParserRuleCall_3_0; }
		
		//"ml"
		public Keyword getMlKeyword_4() { return cMlKeyword_4; }
	}
	public class AddFixedIngredientElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Cocktails.AddFixedIngredient");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAddFKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cAmountAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cAmountAdditionParserRuleCall_3_0 = (RuleCall)cAmountAssignment_3.eContents().get(0);
		private final Keyword cGKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//AddFixedIngredient:
		//    "addF" name=ID ":" amount=Addition "g"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"addF" name=ID ":" amount=Addition "g"
		public Group getGroup() { return cGroup; }
		
		//"addF"
		public Keyword getAddFKeyword_0() { return cAddFKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//amount=Addition
		public Assignment getAmountAssignment_3() { return cAmountAssignment_3; }
		
		//Addition
		public RuleCall getAmountAdditionParserRuleCall_3_0() { return cAmountAdditionParserRuleCall_3_0; }
		
		//"g"
		public Keyword getGKeyword_4() { return cGKeyword_4; }
	}
	public class FancyStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Cocktails.FancyStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUseKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cFcommandAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cFcommandFancyMakeStatementEnumRuleCall_1_0 = (RuleCall)cFcommandAssignment_1.eContents().get(0);
		
		//FancyStatement:
		//    "use" fcommand=FancyMakeStatement
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"use" fcommand=FancyMakeStatement
		public Group getGroup() { return cGroup; }
		
		//"use"
		public Keyword getUseKeyword_0() { return cUseKeyword_0; }
		
		//fcommand=FancyMakeStatement
		public Assignment getFcommandAssignment_1() { return cFcommandAssignment_1; }
		
		//FancyMakeStatement
		public RuleCall getFcommandFancyMakeStatementEnumRuleCall_1_0() { return cFcommandFancyMakeStatementEnumRuleCall_1_0; }
	}
	public class AddIceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Cocktails.AddIce");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAddIcKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cIceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cIceIceStatementEnumRuleCall_1_0 = (RuleCall)cIceAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cOunceAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cOunceAdditionParserRuleCall_3_0 = (RuleCall)cOunceAssignment_3.eContents().get(0);
		private final Keyword cOunceKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//AddIce:
		//    "addIc" ice=IceStatement ":" ounce=Addition "ounce"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"addIc" ice=IceStatement ":" ounce=Addition "ounce"
		public Group getGroup() { return cGroup; }
		
		//"addIc"
		public Keyword getAddIcKeyword_0() { return cAddIcKeyword_0; }
		
		//ice=IceStatement
		public Assignment getIceAssignment_1() { return cIceAssignment_1; }
		
		//IceStatement
		public RuleCall getIceIceStatementEnumRuleCall_1_0() { return cIceIceStatementEnumRuleCall_1_0; }
		
		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//ounce=Addition
		public Assignment getOunceAssignment_3() { return cOunceAssignment_3; }
		
		//Addition
		public RuleCall getOunceAdditionParserRuleCall_3_0() { return cOunceAdditionParserRuleCall_3_0; }
		
		//"ounce"
		public Keyword getOunceKeyword_4() { return cOunceKeyword_4; }
	}
	public class MuddleStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Cocktails.MuddleStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMudKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cMudFruitAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cMudFruitFruitStatementEnumRuleCall_1_0 = (RuleCall)cMudFruitAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cMtimesAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cMtimesAdditionParserRuleCall_3_0 = (RuleCall)cMtimesAssignment_3.eContents().get(0);
		private final Keyword cTimesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//MuddleStatement:
		//    "mud" mudFruit+=FruitStatement* ":" mtimes=Addition "times"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"mud" mudFruit+=FruitStatement* ":" mtimes=Addition "times"
		public Group getGroup() { return cGroup; }
		
		//"mud"
		public Keyword getMudKeyword_0() { return cMudKeyword_0; }
		
		//mudFruit+=FruitStatement*
		public Assignment getMudFruitAssignment_1() { return cMudFruitAssignment_1; }
		
		//FruitStatement
		public RuleCall getMudFruitFruitStatementEnumRuleCall_1_0() { return cMudFruitFruitStatementEnumRuleCall_1_0; }
		
		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }
		
		//mtimes=Addition
		public Assignment getMtimesAssignment_3() { return cMtimesAssignment_3; }
		
		//Addition
		public RuleCall getMtimesAdditionParserRuleCall_3_0() { return cMtimesAdditionParserRuleCall_3_0; }
		
		//"times"
		public Keyword getTimesKeyword_4() { return cTimesKeyword_4; }
	}
	public class AddDecorationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Cocktails.AddDecoration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAddDKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cDecorationAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDecorationDecorationStatementEnumRuleCall_1_0 = (RuleCall)cDecorationAssignment_1.eContents().get(0);
		private final Assignment cSliceAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cSliceAdditionParserRuleCall_2_0 = (RuleCall)cSliceAssignment_2.eContents().get(0);
		private final Keyword cSlicesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//AddDecoration:
		//    "addD" decoration=DecorationStatement slice=Addition "slices"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"addD" decoration=DecorationStatement slice=Addition "slices"
		public Group getGroup() { return cGroup; }
		
		//"addD"
		public Keyword getAddDKeyword_0() { return cAddDKeyword_0; }
		
		//decoration=DecorationStatement
		public Assignment getDecorationAssignment_1() { return cDecorationAssignment_1; }
		
		//DecorationStatement
		public RuleCall getDecorationDecorationStatementEnumRuleCall_1_0() { return cDecorationDecorationStatementEnumRuleCall_1_0; }
		
		//slice=Addition
		public Assignment getSliceAssignment_2() { return cSliceAssignment_2; }
		
		//Addition
		public RuleCall getSliceAdditionParserRuleCall_2_0() { return cSliceAdditionParserRuleCall_2_0; }
		
		//"slices"
		public Keyword getSlicesKeyword_3() { return cSlicesKeyword_3; }
	}
	public class MakeStatementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Cocktails.MakeStatement");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cMakeAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cMakeMakeCommandEnumRuleCall_0_0 = (RuleCall)cMakeAssignment_0.eContents().get(0);
		private final Keyword cColonKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTimeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTimeAdditionParserRuleCall_2_0 = (RuleCall)cTimeAssignment_2.eContents().get(0);
		private final Keyword cSecondsKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//MakeStatement:
		//    make=MakeCommand ":" time=Addition "seconds"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//make=MakeCommand ":" time=Addition "seconds"
		public Group getGroup() { return cGroup; }
		
		//make=MakeCommand
		public Assignment getMakeAssignment_0() { return cMakeAssignment_0; }
		
		//MakeCommand
		public RuleCall getMakeMakeCommandEnumRuleCall_0_0() { return cMakeMakeCommandEnumRuleCall_0_0; }
		
		//":"
		public Keyword getColonKeyword_1() { return cColonKeyword_1; }
		
		//time=Addition
		public Assignment getTimeAssignment_2() { return cTimeAssignment_2; }
		
		//Addition
		public RuleCall getTimeAdditionParserRuleCall_2_0() { return cTimeAdditionParserRuleCall_2_0; }
		
		//"seconds"
		public Keyword getSecondsKeyword_3() { return cSecondsKeyword_3; }
	}
	public class AdditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Cocktails.Addition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cMultiplicationParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cAdditionLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Alternatives cOperatorAlternatives_1_1_0 = (Alternatives)cOperatorAssignment_1_1.eContents().get(0);
		private final Keyword cOperatorPlusSignKeyword_1_1_0_0 = (Keyword)cOperatorAlternatives_1_1_0.eContents().get(0);
		private final Keyword cOperatorHyphenMinusKeyword_1_1_0_1 = (Keyword)cOperatorAlternatives_1_1_0.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightMultiplicationParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//Addition returns Expression:
		//    Multiplication({Addition.left=current} operator+=("+"|"-") right +=Multiplication)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//Multiplication({Addition.left=current} operator+=("+"|"-") right +=Multiplication)*
		public Group getGroup() { return cGroup; }
		
		//Multiplication
		public RuleCall getMultiplicationParserRuleCall_0() { return cMultiplicationParserRuleCall_0; }
		
		//({Addition.left=current} operator+=("+"|"-") right +=Multiplication)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{Addition.left=current}
		public Action getAdditionLeftAction_1_0() { return cAdditionLeftAction_1_0; }
		
		//operator+=("+"|"-")
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }
		
		//("+"|"-")
		public Alternatives getOperatorAlternatives_1_1_0() { return cOperatorAlternatives_1_1_0; }
		
		//"+"
		public Keyword getOperatorPlusSignKeyword_1_1_0_0() { return cOperatorPlusSignKeyword_1_1_0_0; }
		
		//"-"
		public Keyword getOperatorHyphenMinusKeyword_1_1_0_1() { return cOperatorHyphenMinusKeyword_1_1_0_1; }
		
		//right +=Multiplication
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//Multiplication
		public RuleCall getRightMultiplicationParserRuleCall_1_2_0() { return cRightMultiplicationParserRuleCall_1_2_0; }
	}
	public class MultiplicationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Cocktails.Multiplication");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cPrimaryExpressionParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cMultiplicationLeftAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cOperatorAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Alternatives cOperatorAlternatives_1_1_0 = (Alternatives)cOperatorAssignment_1_1.eContents().get(0);
		private final Keyword cOperatorAsteriskKeyword_1_1_0_0 = (Keyword)cOperatorAlternatives_1_1_0.eContents().get(0);
		private final Keyword cOperatorSolidusKeyword_1_1_0_1 = (Keyword)cOperatorAlternatives_1_1_0.eContents().get(1);
		private final Assignment cRightAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cRightPrimaryExpressionParserRuleCall_1_2_0 = (RuleCall)cRightAssignment_1_2.eContents().get(0);
		
		//Multiplication returns Expression:
		//    PrimaryExpression ({Multiplication.left= current} operator+=("*"|"/")right +=PrimaryExpression)*
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//PrimaryExpression ({Multiplication.left= current} operator+=("*"|"/")right +=PrimaryExpression)*
		public Group getGroup() { return cGroup; }
		
		//PrimaryExpression
		public RuleCall getPrimaryExpressionParserRuleCall_0() { return cPrimaryExpressionParserRuleCall_0; }
		
		//({Multiplication.left= current} operator+=("*"|"/")right +=PrimaryExpression)*
		public Group getGroup_1() { return cGroup_1; }
		
		//{Multiplication.left= current}
		public Action getMultiplicationLeftAction_1_0() { return cMultiplicationLeftAction_1_0; }
		
		//operator+=("*"|"/")
		public Assignment getOperatorAssignment_1_1() { return cOperatorAssignment_1_1; }
		
		//("*"|"/")
		public Alternatives getOperatorAlternatives_1_1_0() { return cOperatorAlternatives_1_1_0; }
		
		//"*"
		public Keyword getOperatorAsteriskKeyword_1_1_0_0() { return cOperatorAsteriskKeyword_1_1_0_0; }
		
		//"/"
		public Keyword getOperatorSolidusKeyword_1_1_0_1() { return cOperatorSolidusKeyword_1_1_0_1; }
		
		//right +=PrimaryExpression
		public Assignment getRightAssignment_1_2() { return cRightAssignment_1_2; }
		
		//PrimaryExpression
		public RuleCall getRightPrimaryExpressionParserRuleCall_1_2_0() { return cRightPrimaryExpressionParserRuleCall_1_2_0; }
	}
	public class PrimaryExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Cocktails.PrimaryExpression");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cIntLiteralParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIntVarExpressionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Keyword cLeftParenthesisKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final RuleCall cAdditionParserRuleCall_2_1 = (RuleCall)cGroup_2.eContents().get(1);
		private final Keyword cRightParenthesisKeyword_2_2 = (Keyword)cGroup_2.eContents().get(2);
		
		//PrimaryExpression returns Expression:
		//    IntLiteral|
		//    IntVarExpression |
		//    "("Addition")"
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//IntLiteral|
		//IntVarExpression |
		//"("Addition")"
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//IntLiteral
		public RuleCall getIntLiteralParserRuleCall_0() { return cIntLiteralParserRuleCall_0; }
		
		//IntVarExpression
		public RuleCall getIntVarExpressionParserRuleCall_1() { return cIntVarExpressionParserRuleCall_1; }
		
		//"("Addition")"
		public Group getGroup_2() { return cGroup_2; }
		
		//"("
		public Keyword getLeftParenthesisKeyword_2_0() { return cLeftParenthesisKeyword_2_0; }
		
		//Addition
		public RuleCall getAdditionParserRuleCall_2_1() { return cAdditionParserRuleCall_2_1; }
		
		//")"
		public Keyword getRightParenthesisKeyword_2_2() { return cRightParenthesisKeyword_2_2; }
	}
	public class IntLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Cocktails.IntLiteral");
		private final Assignment cValAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValINTTerminalRuleCall_0 = (RuleCall)cValAssignment.eContents().get(0);
		
		//IntLiteral:
		//    val=INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//val=INT
		public Assignment getValAssignment() { return cValAssignment; }
		
		//INT
		public RuleCall getValINTTerminalRuleCall_0() { return cValINTTerminalRuleCall_0; }
	}
	public class VariableDeclarationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Cocktails.VariableDeclaration");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVarKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cEqualsSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cValueAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cValueINTTerminalRuleCall_3_0 = (RuleCall)cValueAssignment_3.eContents().get(0);
		
		//VariableDeclaration:
		//    "var" name=ID "=" value=INT
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//"var" name=ID "=" value=INT
		public Group getGroup() { return cGroup; }
		
		//"var"
		public Keyword getVarKeyword_0() { return cVarKeyword_0; }
		
		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }
		
		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }
		
		//"="
		public Keyword getEqualsSignKeyword_2() { return cEqualsSignKeyword_2; }
		
		//value=INT
		public Assignment getValueAssignment_3() { return cValueAssignment_3; }
		
		//INT
		public RuleCall getValueINTTerminalRuleCall_3_0() { return cValueINTTerminalRuleCall_3_0; }
	}
	public class IntVarExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Cocktails.IntVarExpression");
		private final Assignment cVarAssignment = (Assignment)rule.eContents().get(1);
		private final CrossReference cVarVariableDeclarationCrossReference_0 = (CrossReference)cVarAssignment.eContents().get(0);
		private final RuleCall cVarVariableDeclarationIDTerminalRuleCall_0_1 = (RuleCall)cVarVariableDeclarationCrossReference_0.eContents().get(1);
		
		//IntVarExpression:
		//    var = [VariableDeclaration]
		//;
		@Override public ParserRule getRule() { return rule; }
		
		//var = [VariableDeclaration]
		public Assignment getVarAssignment() { return cVarAssignment; }
		
		//[VariableDeclaration]
		public CrossReference getVarVariableDeclarationCrossReference_0() { return cVarVariableDeclarationCrossReference_0; }
		
		//ID
		public RuleCall getVarVariableDeclarationIDTerminalRuleCall_0_1() { return cVarVariableDeclarationIDTerminalRuleCall_0_1; }
	}
	
	public class FancyMakeStatementElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Cocktails.FancyMakeStatement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cLighterEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cLighterLighterKeyword_0_0 = (Keyword)cLighterEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCo2EnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCo2Co2Keyword_1_0 = (Keyword)cCo2EnumLiteralDeclaration_1.eContents().get(0);
		
		//enum FancyMakeStatement:
		//    lighter|
		//    co2
		//;
		public EnumRule getRule() { return rule; }
		
		//lighter|
		//co2
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//lighter
		public EnumLiteralDeclaration getLighterEnumLiteralDeclaration_0() { return cLighterEnumLiteralDeclaration_0; }
		
		public Keyword getLighterLighterKeyword_0_0() { return cLighterLighterKeyword_0_0; }
		
		//co2
		public EnumLiteralDeclaration getCo2EnumLiteralDeclaration_1() { return cCo2EnumLiteralDeclaration_1; }
		
		public Keyword getCo2Co2Keyword_1_0() { return cCo2Co2Keyword_1_0; }
	}
	public class IceStatementElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Cocktails.IceStatement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cCubeEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cCubeCubeKeyword_0_0 = (Keyword)cCubeEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cCrushEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cCrushCrushKeyword_1_0 = (Keyword)cCrushEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cShaveEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cShaveShaveKeyword_2_0 = (Keyword)cShaveEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cBlockEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cBlockBlockKeyword_3_0 = (Keyword)cBlockEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cBallEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cBallBallKeyword_4_0 = (Keyword)cBallEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cConeEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cConeConeKeyword_5_0 = (Keyword)cConeEnumLiteralDeclaration_5.eContents().get(0);
		
		//enum IceStatement:
		//    cube|crush|shave|block|ball|cone
		//;
		public EnumRule getRule() { return rule; }
		
		//cube|crush|shave|block|ball|cone
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//cube
		public EnumLiteralDeclaration getCubeEnumLiteralDeclaration_0() { return cCubeEnumLiteralDeclaration_0; }
		
		public Keyword getCubeCubeKeyword_0_0() { return cCubeCubeKeyword_0_0; }
		
		//crush
		public EnumLiteralDeclaration getCrushEnumLiteralDeclaration_1() { return cCrushEnumLiteralDeclaration_1; }
		
		public Keyword getCrushCrushKeyword_1_0() { return cCrushCrushKeyword_1_0; }
		
		//shave
		public EnumLiteralDeclaration getShaveEnumLiteralDeclaration_2() { return cShaveEnumLiteralDeclaration_2; }
		
		public Keyword getShaveShaveKeyword_2_0() { return cShaveShaveKeyword_2_0; }
		
		//block
		public EnumLiteralDeclaration getBlockEnumLiteralDeclaration_3() { return cBlockEnumLiteralDeclaration_3; }
		
		public Keyword getBlockBlockKeyword_3_0() { return cBlockBlockKeyword_3_0; }
		
		//ball
		public EnumLiteralDeclaration getBallEnumLiteralDeclaration_4() { return cBallEnumLiteralDeclaration_4; }
		
		public Keyword getBallBallKeyword_4_0() { return cBallBallKeyword_4_0; }
		
		//cone
		public EnumLiteralDeclaration getConeEnumLiteralDeclaration_5() { return cConeEnumLiteralDeclaration_5; }
		
		public Keyword getConeConeKeyword_5_0() { return cConeConeKeyword_5_0; }
	}
	public class FruitStatementElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Cocktails.FruitStatement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cLimeEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cLimeLimeKeyword_0_0 = (Keyword)cLimeEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cLemonEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cLemonLemonKeyword_1_0 = (Keyword)cLemonEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cOrangeEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cOrangeOrangeKeyword_2_0 = (Keyword)cOrangeEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cGrapefruitEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cGrapefruitGrapefruitKeyword_3_0 = (Keyword)cGrapefruitEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cPineappleEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cPineapplePineappleKeyword_4_0 = (Keyword)cPineappleEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cMangoEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cMangoMangoKeyword_5_0 = (Keyword)cMangoEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cKiwiEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cKiwiKiwiKeyword_6_0 = (Keyword)cKiwiEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cStrawberryEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cStrawberryStrawberryKeyword_7_0 = (Keyword)cStrawberryEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cBlueberryEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cBlueberryBlueberryKeyword_8_0 = (Keyword)cBlueberryEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cRaspberryEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cRaspberryRaspberryKeyword_9_0 = (Keyword)cRaspberryEnumLiteralDeclaration_9.eContents().get(0);
		private final EnumLiteralDeclaration cBlackberryEnumLiteralDeclaration_10 = (EnumLiteralDeclaration)cAlternatives.eContents().get(10);
		private final Keyword cBlackberryBlackberryKeyword_10_0 = (Keyword)cBlackberryEnumLiteralDeclaration_10.eContents().get(0);
		private final EnumLiteralDeclaration cCherryEnumLiteralDeclaration_11 = (EnumLiteralDeclaration)cAlternatives.eContents().get(11);
		private final Keyword cCherryCherryKeyword_11_0 = (Keyword)cCherryEnumLiteralDeclaration_11.eContents().get(0);
		private final EnumLiteralDeclaration cPeachEnumLiteralDeclaration_12 = (EnumLiteralDeclaration)cAlternatives.eContents().get(12);
		private final Keyword cPeachPeachKeyword_12_0 = (Keyword)cPeachEnumLiteralDeclaration_12.eContents().get(0);
		private final EnumLiteralDeclaration cPlumEnumLiteralDeclaration_13 = (EnumLiteralDeclaration)cAlternatives.eContents().get(13);
		private final Keyword cPlumPlumKeyword_13_0 = (Keyword)cPlumEnumLiteralDeclaration_13.eContents().get(0);
		private final EnumLiteralDeclaration cWatermelonEnumLiteralDeclaration_14 = (EnumLiteralDeclaration)cAlternatives.eContents().get(14);
		private final Keyword cWatermelonWatermelonKeyword_14_0 = (Keyword)cWatermelonEnumLiteralDeclaration_14.eContents().get(0);
		private final EnumLiteralDeclaration cCucumberEnumLiteralDeclaration_15 = (EnumLiteralDeclaration)cAlternatives.eContents().get(15);
		private final Keyword cCucumberCucumberKeyword_15_0 = (Keyword)cCucumberEnumLiteralDeclaration_15.eContents().get(0);
		private final EnumLiteralDeclaration cMintEnumLiteralDeclaration_16 = (EnumLiteralDeclaration)cAlternatives.eContents().get(16);
		private final Keyword cMintMintKeyword_16_0 = (Keyword)cMintEnumLiteralDeclaration_16.eContents().get(0);
		private final EnumLiteralDeclaration cBasilEnumLiteralDeclaration_17 = (EnumLiteralDeclaration)cAlternatives.eContents().get(17);
		private final Keyword cBasilBasilKeyword_17_0 = (Keyword)cBasilEnumLiteralDeclaration_17.eContents().get(0);
		private final EnumLiteralDeclaration cThymeEnumLiteralDeclaration_18 = (EnumLiteralDeclaration)cAlternatives.eContents().get(18);
		private final Keyword cThymeThymeKeyword_18_0 = (Keyword)cThymeEnumLiteralDeclaration_18.eContents().get(0);
		private final EnumLiteralDeclaration cGingerEnumLiteralDeclaration_19 = (EnumLiteralDeclaration)cAlternatives.eContents().get(19);
		private final Keyword cGingerGingerKeyword_19_0 = (Keyword)cGingerEnumLiteralDeclaration_19.eContents().get(0);
		
		//enum FruitStatement:
		//    lime |
		//    lemon |
		//    orange |
		//    grapefruit |
		//    pineapple |
		//    mango |
		//    kiwi |
		//    strawberry |
		//    blueberry |
		//    raspberry |
		//    blackberry |
		//    cherry |
		//    peach |
		//    plum |
		//    watermelon |
		//    cucumber |
		//    mint |
		//    basil |
		//    thyme |
		//    ginger
		//;
		public EnumRule getRule() { return rule; }
		
		//lime |
		//lemon |
		//orange |
		//grapefruit |
		//pineapple |
		//mango |
		//kiwi |
		//strawberry |
		//blueberry |
		//raspberry |
		//blackberry |
		//cherry |
		//peach |
		//plum |
		//watermelon |
		//cucumber |
		//mint |
		//basil |
		//thyme |
		//ginger
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//lime
		public EnumLiteralDeclaration getLimeEnumLiteralDeclaration_0() { return cLimeEnumLiteralDeclaration_0; }
		
		public Keyword getLimeLimeKeyword_0_0() { return cLimeLimeKeyword_0_0; }
		
		//lemon
		public EnumLiteralDeclaration getLemonEnumLiteralDeclaration_1() { return cLemonEnumLiteralDeclaration_1; }
		
		public Keyword getLemonLemonKeyword_1_0() { return cLemonLemonKeyword_1_0; }
		
		//orange
		public EnumLiteralDeclaration getOrangeEnumLiteralDeclaration_2() { return cOrangeEnumLiteralDeclaration_2; }
		
		public Keyword getOrangeOrangeKeyword_2_0() { return cOrangeOrangeKeyword_2_0; }
		
		//grapefruit
		public EnumLiteralDeclaration getGrapefruitEnumLiteralDeclaration_3() { return cGrapefruitEnumLiteralDeclaration_3; }
		
		public Keyword getGrapefruitGrapefruitKeyword_3_0() { return cGrapefruitGrapefruitKeyword_3_0; }
		
		//pineapple
		public EnumLiteralDeclaration getPineappleEnumLiteralDeclaration_4() { return cPineappleEnumLiteralDeclaration_4; }
		
		public Keyword getPineapplePineappleKeyword_4_0() { return cPineapplePineappleKeyword_4_0; }
		
		//mango
		public EnumLiteralDeclaration getMangoEnumLiteralDeclaration_5() { return cMangoEnumLiteralDeclaration_5; }
		
		public Keyword getMangoMangoKeyword_5_0() { return cMangoMangoKeyword_5_0; }
		
		//kiwi
		public EnumLiteralDeclaration getKiwiEnumLiteralDeclaration_6() { return cKiwiEnumLiteralDeclaration_6; }
		
		public Keyword getKiwiKiwiKeyword_6_0() { return cKiwiKiwiKeyword_6_0; }
		
		//strawberry
		public EnumLiteralDeclaration getStrawberryEnumLiteralDeclaration_7() { return cStrawberryEnumLiteralDeclaration_7; }
		
		public Keyword getStrawberryStrawberryKeyword_7_0() { return cStrawberryStrawberryKeyword_7_0; }
		
		//blueberry
		public EnumLiteralDeclaration getBlueberryEnumLiteralDeclaration_8() { return cBlueberryEnumLiteralDeclaration_8; }
		
		public Keyword getBlueberryBlueberryKeyword_8_0() { return cBlueberryBlueberryKeyword_8_0; }
		
		//raspberry
		public EnumLiteralDeclaration getRaspberryEnumLiteralDeclaration_9() { return cRaspberryEnumLiteralDeclaration_9; }
		
		public Keyword getRaspberryRaspberryKeyword_9_0() { return cRaspberryRaspberryKeyword_9_0; }
		
		//blackberry
		public EnumLiteralDeclaration getBlackberryEnumLiteralDeclaration_10() { return cBlackberryEnumLiteralDeclaration_10; }
		
		public Keyword getBlackberryBlackberryKeyword_10_0() { return cBlackberryBlackberryKeyword_10_0; }
		
		//cherry
		public EnumLiteralDeclaration getCherryEnumLiteralDeclaration_11() { return cCherryEnumLiteralDeclaration_11; }
		
		public Keyword getCherryCherryKeyword_11_0() { return cCherryCherryKeyword_11_0; }
		
		//peach
		public EnumLiteralDeclaration getPeachEnumLiteralDeclaration_12() { return cPeachEnumLiteralDeclaration_12; }
		
		public Keyword getPeachPeachKeyword_12_0() { return cPeachPeachKeyword_12_0; }
		
		//plum
		public EnumLiteralDeclaration getPlumEnumLiteralDeclaration_13() { return cPlumEnumLiteralDeclaration_13; }
		
		public Keyword getPlumPlumKeyword_13_0() { return cPlumPlumKeyword_13_0; }
		
		//watermelon
		public EnumLiteralDeclaration getWatermelonEnumLiteralDeclaration_14() { return cWatermelonEnumLiteralDeclaration_14; }
		
		public Keyword getWatermelonWatermelonKeyword_14_0() { return cWatermelonWatermelonKeyword_14_0; }
		
		//cucumber
		public EnumLiteralDeclaration getCucumberEnumLiteralDeclaration_15() { return cCucumberEnumLiteralDeclaration_15; }
		
		public Keyword getCucumberCucumberKeyword_15_0() { return cCucumberCucumberKeyword_15_0; }
		
		//mint
		public EnumLiteralDeclaration getMintEnumLiteralDeclaration_16() { return cMintEnumLiteralDeclaration_16; }
		
		public Keyword getMintMintKeyword_16_0() { return cMintMintKeyword_16_0; }
		
		//basil
		public EnumLiteralDeclaration getBasilEnumLiteralDeclaration_17() { return cBasilEnumLiteralDeclaration_17; }
		
		public Keyword getBasilBasilKeyword_17_0() { return cBasilBasilKeyword_17_0; }
		
		//thyme
		public EnumLiteralDeclaration getThymeEnumLiteralDeclaration_18() { return cThymeEnumLiteralDeclaration_18; }
		
		public Keyword getThymeThymeKeyword_18_0() { return cThymeThymeKeyword_18_0; }
		
		//ginger
		public EnumLiteralDeclaration getGingerEnumLiteralDeclaration_19() { return cGingerEnumLiteralDeclaration_19; }
		
		public Keyword getGingerGingerKeyword_19_0() { return cGingerGingerKeyword_19_0; }
	}
	public class DecorationStatementElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Cocktails.DecorationStatement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cOrangeEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cOrangeOrangeKeyword_0_0 = (Keyword)cOrangeEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cLemonEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cLemonLemonKeyword_1_0 = (Keyword)cLemonEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cLimeEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cLimeLimeKeyword_2_0 = (Keyword)cLimeEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cOliveEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cOliveOliveKeyword_3_0 = (Keyword)cOliveEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cCherryEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cCherryCherryKeyword_4_0 = (Keyword)cCherryEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cMintEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cMintMintKeyword_5_0 = (Keyword)cMintEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cRoseEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cRoseRoseKeyword_6_0 = (Keyword)cRoseEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cCinnamonEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cCinnamonCinnamonKeyword_7_0 = (Keyword)cCinnamonEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cMangoEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cMangoMangoKeyword_8_0 = (Keyword)cMangoEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cGrapefruitEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cGrapefruitGrapefruitKeyword_9_0 = (Keyword)cGrapefruitEnumLiteralDeclaration_9.eContents().get(0);
		
		//enum DecorationStatement:
		//    orange|
		//    lemon|
		//    lime|
		//    olive|
		//    cherry|
		//    mint|
		//    rose|
		//    cinnamon|
		//    mango|
		//    grapefruit
		//;
		public EnumRule getRule() { return rule; }
		
		//orange|
		//lemon|
		//lime|
		//olive|
		//cherry|
		//mint|
		//rose|
		//cinnamon|
		//mango|
		//grapefruit
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//orange
		public EnumLiteralDeclaration getOrangeEnumLiteralDeclaration_0() { return cOrangeEnumLiteralDeclaration_0; }
		
		public Keyword getOrangeOrangeKeyword_0_0() { return cOrangeOrangeKeyword_0_0; }
		
		//lemon
		public EnumLiteralDeclaration getLemonEnumLiteralDeclaration_1() { return cLemonEnumLiteralDeclaration_1; }
		
		public Keyword getLemonLemonKeyword_1_0() { return cLemonLemonKeyword_1_0; }
		
		//lime
		public EnumLiteralDeclaration getLimeEnumLiteralDeclaration_2() { return cLimeEnumLiteralDeclaration_2; }
		
		public Keyword getLimeLimeKeyword_2_0() { return cLimeLimeKeyword_2_0; }
		
		//olive
		public EnumLiteralDeclaration getOliveEnumLiteralDeclaration_3() { return cOliveEnumLiteralDeclaration_3; }
		
		public Keyword getOliveOliveKeyword_3_0() { return cOliveOliveKeyword_3_0; }
		
		//cherry
		public EnumLiteralDeclaration getCherryEnumLiteralDeclaration_4() { return cCherryEnumLiteralDeclaration_4; }
		
		public Keyword getCherryCherryKeyword_4_0() { return cCherryCherryKeyword_4_0; }
		
		//mint
		public EnumLiteralDeclaration getMintEnumLiteralDeclaration_5() { return cMintEnumLiteralDeclaration_5; }
		
		public Keyword getMintMintKeyword_5_0() { return cMintMintKeyword_5_0; }
		
		//rose
		public EnumLiteralDeclaration getRoseEnumLiteralDeclaration_6() { return cRoseEnumLiteralDeclaration_6; }
		
		public Keyword getRoseRoseKeyword_6_0() { return cRoseRoseKeyword_6_0; }
		
		//cinnamon
		public EnumLiteralDeclaration getCinnamonEnumLiteralDeclaration_7() { return cCinnamonEnumLiteralDeclaration_7; }
		
		public Keyword getCinnamonCinnamonKeyword_7_0() { return cCinnamonCinnamonKeyword_7_0; }
		
		//mango
		public EnumLiteralDeclaration getMangoEnumLiteralDeclaration_8() { return cMangoEnumLiteralDeclaration_8; }
		
		public Keyword getMangoMangoKeyword_8_0() { return cMangoMangoKeyword_8_0; }
		
		//grapefruit
		public EnumLiteralDeclaration getGrapefruitEnumLiteralDeclaration_9() { return cGrapefruitEnumLiteralDeclaration_9; }
		
		public Keyword getGrapefruitGrapefruitKeyword_9_0() { return cGrapefruitGrapefruitKeyword_9_0; }
	}
	public class MakeCommandElements extends AbstractElementFinder.AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "org.xtext.example.mydsl.Cocktails.MakeCommand");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cStirEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cStirStirKeyword_0_0 = (Keyword)cStirEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cShakeEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cShakeShakeKeyword_1_0 = (Keyword)cShakeEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cBlendEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cBlendBlendKeyword_2_0 = (Keyword)cBlendEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cFilterEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cFilterFilterKeyword_3_0 = (Keyword)cFilterEnumLiteralDeclaration_3.eContents().get(0);
		
		//enum MakeCommand:
		//    stir|
		//    shake|
		//    blend|
		//    filter
		//;
		public EnumRule getRule() { return rule; }
		
		//stir|
		//shake|
		//blend|
		//filter
		public Alternatives getAlternatives() { return cAlternatives; }
		
		//stir
		public EnumLiteralDeclaration getStirEnumLiteralDeclaration_0() { return cStirEnumLiteralDeclaration_0; }
		
		public Keyword getStirStirKeyword_0_0() { return cStirStirKeyword_0_0; }
		
		//shake
		public EnumLiteralDeclaration getShakeEnumLiteralDeclaration_1() { return cShakeEnumLiteralDeclaration_1; }
		
		public Keyword getShakeShakeKeyword_1_0() { return cShakeShakeKeyword_1_0; }
		
		//blend
		public EnumLiteralDeclaration getBlendEnumLiteralDeclaration_2() { return cBlendEnumLiteralDeclaration_2; }
		
		public Keyword getBlendBlendKeyword_2_0() { return cBlendBlendKeyword_2_0; }
		
		//filter
		public EnumLiteralDeclaration getFilterEnumLiteralDeclaration_3() { return cFilterEnumLiteralDeclaration_3; }
		
		public Keyword getFilterFilterKeyword_3_0() { return cFilterFilterKeyword_3_0; }
	}
	
	private final OrderElements pOrder;
	private final InstructionElements pInstruction;
	private final AddIngredientElements pAddIngredient;
	private final AddFixedIngredientElements pAddFixedIngredient;
	private final FancyStatementElements pFancyStatement;
	private final FancyMakeStatementElements eFancyMakeStatement;
	private final AddIceElements pAddIce;
	private final IceStatementElements eIceStatement;
	private final MuddleStatementElements pMuddleStatement;
	private final FruitStatementElements eFruitStatement;
	private final AddDecorationElements pAddDecoration;
	private final DecorationStatementElements eDecorationStatement;
	private final MakeStatementElements pMakeStatement;
	private final MakeCommandElements eMakeCommand;
	private final AdditionElements pAddition;
	private final MultiplicationElements pMultiplication;
	private final PrimaryExpressionElements pPrimaryExpression;
	private final IntLiteralElements pIntLiteral;
	private final VariableDeclarationElements pVariableDeclaration;
	private final IntVarExpressionElements pIntVarExpression;
	
	private final Grammar grammar;
	
	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public CocktailsGrammarAccess(GrammarProvider grammarProvider,
			TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pOrder = new OrderElements();
		this.pInstruction = new InstructionElements();
		this.pAddIngredient = new AddIngredientElements();
		this.pAddFixedIngredient = new AddFixedIngredientElements();
		this.pFancyStatement = new FancyStatementElements();
		this.eFancyMakeStatement = new FancyMakeStatementElements();
		this.pAddIce = new AddIceElements();
		this.eIceStatement = new IceStatementElements();
		this.pMuddleStatement = new MuddleStatementElements();
		this.eFruitStatement = new FruitStatementElements();
		this.pAddDecoration = new AddDecorationElements();
		this.eDecorationStatement = new DecorationStatementElements();
		this.pMakeStatement = new MakeStatementElements();
		this.eMakeCommand = new MakeCommandElements();
		this.pAddition = new AdditionElements();
		this.pMultiplication = new MultiplicationElements();
		this.pPrimaryExpression = new PrimaryExpressionElements();
		this.pIntLiteral = new IntLiteralElements();
		this.pVariableDeclaration = new VariableDeclarationElements();
		this.pIntVarExpression = new IntVarExpressionElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.example.mydsl.Cocktails".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	
	
	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//Order:
	//    instructions+=Instruction*
	//;
	public OrderElements getOrderAccess() {
		return pOrder;
	}
	
	public ParserRule getOrderRule() {
		return getOrderAccess().getRule();
	}
	
	//Instruction:
	//    AddIngredient|
	//    AddFixedIngredient|
	//    FancyStatement|
	//    AddIce|
	//    MuddleStatement|
	//    AddDecoration|
	//    MakeStatement|
	//    VariableDeclaration
	//    //    AddFruitformuddle |
	//;
	public InstructionElements getInstructionAccess() {
		return pInstruction;
	}
	
	public ParserRule getInstructionRule() {
		return getInstructionAccess().getRule();
	}
	
	//AddIngredient:
	//    "addI" name=ID ":" amount=Addition "ml"
	//;
	public AddIngredientElements getAddIngredientAccess() {
		return pAddIngredient;
	}
	
	public ParserRule getAddIngredientRule() {
		return getAddIngredientAccess().getRule();
	}
	
	//AddFixedIngredient:
	//    "addF" name=ID ":" amount=Addition "g"
	//;
	public AddFixedIngredientElements getAddFixedIngredientAccess() {
		return pAddFixedIngredient;
	}
	
	public ParserRule getAddFixedIngredientRule() {
		return getAddFixedIngredientAccess().getRule();
	}
	
	//FancyStatement:
	//    "use" fcommand=FancyMakeStatement
	//;
	public FancyStatementElements getFancyStatementAccess() {
		return pFancyStatement;
	}
	
	public ParserRule getFancyStatementRule() {
		return getFancyStatementAccess().getRule();
	}
	
	//enum FancyMakeStatement:
	//    lighter|
	//    co2
	//;
	public FancyMakeStatementElements getFancyMakeStatementAccess() {
		return eFancyMakeStatement;
	}
	
	public EnumRule getFancyMakeStatementRule() {
		return getFancyMakeStatementAccess().getRule();
	}
	
	//AddIce:
	//    "addIc" ice=IceStatement ":" ounce=Addition "ounce"
	//;
	public AddIceElements getAddIceAccess() {
		return pAddIce;
	}
	
	public ParserRule getAddIceRule() {
		return getAddIceAccess().getRule();
	}
	
	//enum IceStatement:
	//    cube|crush|shave|block|ball|cone
	//;
	public IceStatementElements getIceStatementAccess() {
		return eIceStatement;
	}
	
	public EnumRule getIceStatementRule() {
		return getIceStatementAccess().getRule();
	}
	
	//MuddleStatement:
	//    "mud" mudFruit+=FruitStatement* ":" mtimes=Addition "times"
	//;
	public MuddleStatementElements getMuddleStatementAccess() {
		return pMuddleStatement;
	}
	
	public ParserRule getMuddleStatementRule() {
		return getMuddleStatementAccess().getRule();
	}
	
	//enum FruitStatement:
	//    lime |
	//    lemon |
	//    orange |
	//    grapefruit |
	//    pineapple |
	//    mango |
	//    kiwi |
	//    strawberry |
	//    blueberry |
	//    raspberry |
	//    blackberry |
	//    cherry |
	//    peach |
	//    plum |
	//    watermelon |
	//    cucumber |
	//    mint |
	//    basil |
	//    thyme |
	//    ginger
	//;
	public FruitStatementElements getFruitStatementAccess() {
		return eFruitStatement;
	}
	
	public EnumRule getFruitStatementRule() {
		return getFruitStatementAccess().getRule();
	}
	
	//AddDecoration:
	//    "addD" decoration=DecorationStatement slice=Addition "slices"
	//;
	public AddDecorationElements getAddDecorationAccess() {
		return pAddDecoration;
	}
	
	public ParserRule getAddDecorationRule() {
		return getAddDecorationAccess().getRule();
	}
	
	//enum DecorationStatement:
	//    orange|
	//    lemon|
	//    lime|
	//    olive|
	//    cherry|
	//    mint|
	//    rose|
	//    cinnamon|
	//    mango|
	//    grapefruit
	//;
	public DecorationStatementElements getDecorationStatementAccess() {
		return eDecorationStatement;
	}
	
	public EnumRule getDecorationStatementRule() {
		return getDecorationStatementAccess().getRule();
	}
	
	//MakeStatement:
	//    make=MakeCommand ":" time=Addition "seconds"
	//;
	public MakeStatementElements getMakeStatementAccess() {
		return pMakeStatement;
	}
	
	public ParserRule getMakeStatementRule() {
		return getMakeStatementAccess().getRule();
	}
	
	//enum MakeCommand:
	//    stir|
	//    shake|
	//    blend|
	//    filter
	//;
	public MakeCommandElements getMakeCommandAccess() {
		return eMakeCommand;
	}
	
	public EnumRule getMakeCommandRule() {
		return getMakeCommandAccess().getRule();
	}
	
	//Addition returns Expression:
	//    Multiplication({Addition.left=current} operator+=("+"|"-") right +=Multiplication)*
	//;
	public AdditionElements getAdditionAccess() {
		return pAddition;
	}
	
	public ParserRule getAdditionRule() {
		return getAdditionAccess().getRule();
	}
	
	//Multiplication returns Expression:
	//    PrimaryExpression ({Multiplication.left= current} operator+=("*"|"/")right +=PrimaryExpression)*
	//;
	public MultiplicationElements getMultiplicationAccess() {
		return pMultiplication;
	}
	
	public ParserRule getMultiplicationRule() {
		return getMultiplicationAccess().getRule();
	}
	
	//PrimaryExpression returns Expression:
	//    IntLiteral|
	//    IntVarExpression |
	//    "("Addition")"
	//;
	public PrimaryExpressionElements getPrimaryExpressionAccess() {
		return pPrimaryExpression;
	}
	
	public ParserRule getPrimaryExpressionRule() {
		return getPrimaryExpressionAccess().getRule();
	}
	
	//IntLiteral:
	//    val=INT
	//;
	public IntLiteralElements getIntLiteralAccess() {
		return pIntLiteral;
	}
	
	public ParserRule getIntLiteralRule() {
		return getIntLiteralAccess().getRule();
	}
	
	//VariableDeclaration:
	//    "var" name=ID "=" value=INT
	//;
	public VariableDeclarationElements getVariableDeclarationAccess() {
		return pVariableDeclaration;
	}
	
	public ParserRule getVariableDeclarationRule() {
		return getVariableDeclarationAccess().getRule();
	}
	
	//IntVarExpression:
	//    var = [VariableDeclaration]
	//;
	public IntVarExpressionElements getIntVarExpressionAccess() {
		return pIntVarExpression;
	}
	
	public ParserRule getIntVarExpressionRule() {
		return getIntVarExpressionAccess().getRule();
	}
	
	//terminal ID: '^'?('a'..'z'|'A'..'Z'|'_') ('a'..'z'|'A'..'Z'|'_'|'0'..'9')*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	}
	
	//terminal INT returns ecore::EInt: ('0'..'9')+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	}
	
	//terminal STRING:
	//            '"' ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|'"') )* '"' |
	//            "'" ( '\\' . /* 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' */ | !('\\'|"'") )* "'"
	//        ;
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	}
	
	//terminal ML_COMMENT : '/*' -> '*/';
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	}
	
	//terminal SL_COMMENT : '//' !('\n'|'\r')* ('\r'? '\n')?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	}
	
	//terminal WS         : (' '|'\t'|'\r'|'\n')+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	}
	
	//terminal ANY_OTHER: .;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	}
}
