/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.example.mydsl.ide.contentassist.antlr.internal.InternalCocktailsParser;
import org.xtext.example.mydsl.services.CocktailsGrammarAccess;

public class CocktailsParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(CocktailsGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, CocktailsGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getInstructionAccess().getAlternatives(), "rule__Instruction__Alternatives");
			builder.put(grammarAccess.getAdditionAccess().getOperatorAlternatives_1_1_0(), "rule__Addition__OperatorAlternatives_1_1_0");
			builder.put(grammarAccess.getMultiplicationAccess().getOperatorAlternatives_1_1_0(), "rule__Multiplication__OperatorAlternatives_1_1_0");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getAlternatives(), "rule__PrimaryExpression__Alternatives");
			builder.put(grammarAccess.getFancyMakeStatementAccess().getAlternatives(), "rule__FancyMakeStatement__Alternatives");
			builder.put(grammarAccess.getIceStatementAccess().getAlternatives(), "rule__IceStatement__Alternatives");
			builder.put(grammarAccess.getFruitStatementAccess().getAlternatives(), "rule__FruitStatement__Alternatives");
			builder.put(grammarAccess.getDecorationStatementAccess().getAlternatives(), "rule__DecorationStatement__Alternatives");
			builder.put(grammarAccess.getMakeCommandAccess().getAlternatives(), "rule__MakeCommand__Alternatives");
			builder.put(grammarAccess.getAddIngredientAccess().getGroup(), "rule__AddIngredient__Group__0");
			builder.put(grammarAccess.getAddFixedIngredientAccess().getGroup(), "rule__AddFixedIngredient__Group__0");
			builder.put(grammarAccess.getFancyStatementAccess().getGroup(), "rule__FancyStatement__Group__0");
			builder.put(grammarAccess.getAddIceAccess().getGroup(), "rule__AddIce__Group__0");
			builder.put(grammarAccess.getMuddleStatementAccess().getGroup(), "rule__MuddleStatement__Group__0");
			builder.put(grammarAccess.getAddDecorationAccess().getGroup(), "rule__AddDecoration__Group__0");
			builder.put(grammarAccess.getMakeStatementAccess().getGroup(), "rule__MakeStatement__Group__0");
			builder.put(grammarAccess.getAdditionAccess().getGroup(), "rule__Addition__Group__0");
			builder.put(grammarAccess.getAdditionAccess().getGroup_1(), "rule__Addition__Group_1__0");
			builder.put(grammarAccess.getMultiplicationAccess().getGroup(), "rule__Multiplication__Group__0");
			builder.put(grammarAccess.getMultiplicationAccess().getGroup_1(), "rule__Multiplication__Group_1__0");
			builder.put(grammarAccess.getPrimaryExpressionAccess().getGroup_2(), "rule__PrimaryExpression__Group_2__0");
			builder.put(grammarAccess.getVariableDeclarationAccess().getGroup(), "rule__VariableDeclaration__Group__0");
			builder.put(grammarAccess.getOrderAccess().getInstructionsAssignment(), "rule__Order__InstructionsAssignment");
			builder.put(grammarAccess.getAddIngredientAccess().getNameAssignment_1(), "rule__AddIngredient__NameAssignment_1");
			builder.put(grammarAccess.getAddIngredientAccess().getAmountAssignment_3(), "rule__AddIngredient__AmountAssignment_3");
			builder.put(grammarAccess.getAddFixedIngredientAccess().getNameAssignment_1(), "rule__AddFixedIngredient__NameAssignment_1");
			builder.put(grammarAccess.getAddFixedIngredientAccess().getAmountAssignment_3(), "rule__AddFixedIngredient__AmountAssignment_3");
			builder.put(grammarAccess.getFancyStatementAccess().getFcommandAssignment_1(), "rule__FancyStatement__FcommandAssignment_1");
			builder.put(grammarAccess.getAddIceAccess().getIceAssignment_1(), "rule__AddIce__IceAssignment_1");
			builder.put(grammarAccess.getAddIceAccess().getOunceAssignment_3(), "rule__AddIce__OunceAssignment_3");
			builder.put(grammarAccess.getMuddleStatementAccess().getMudFruitAssignment_1(), "rule__MuddleStatement__MudFruitAssignment_1");
			builder.put(grammarAccess.getMuddleStatementAccess().getMtimesAssignment_3(), "rule__MuddleStatement__MtimesAssignment_3");
			builder.put(grammarAccess.getAddDecorationAccess().getDecorationAssignment_1(), "rule__AddDecoration__DecorationAssignment_1");
			builder.put(grammarAccess.getAddDecorationAccess().getSliceAssignment_2(), "rule__AddDecoration__SliceAssignment_2");
			builder.put(grammarAccess.getMakeStatementAccess().getMakeAssignment_0(), "rule__MakeStatement__MakeAssignment_0");
			builder.put(grammarAccess.getMakeStatementAccess().getTimeAssignment_2(), "rule__MakeStatement__TimeAssignment_2");
			builder.put(grammarAccess.getAdditionAccess().getOperatorAssignment_1_1(), "rule__Addition__OperatorAssignment_1_1");
			builder.put(grammarAccess.getAdditionAccess().getRightAssignment_1_2(), "rule__Addition__RightAssignment_1_2");
			builder.put(grammarAccess.getMultiplicationAccess().getOperatorAssignment_1_1(), "rule__Multiplication__OperatorAssignment_1_1");
			builder.put(grammarAccess.getMultiplicationAccess().getRightAssignment_1_2(), "rule__Multiplication__RightAssignment_1_2");
			builder.put(grammarAccess.getIntLiteralAccess().getValAssignment(), "rule__IntLiteral__ValAssignment");
			builder.put(grammarAccess.getVariableDeclarationAccess().getNameAssignment_1(), "rule__VariableDeclaration__NameAssignment_1");
			builder.put(grammarAccess.getVariableDeclarationAccess().getValueAssignment_3(), "rule__VariableDeclaration__ValueAssignment_3");
			builder.put(grammarAccess.getIntVarExpressionAccess().getVarAssignment(), "rule__IntVarExpression__VarAssignment");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private CocktailsGrammarAccess grammarAccess;

	@Override
	protected InternalCocktailsParser createParser() {
		InternalCocktailsParser result = new InternalCocktailsParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public CocktailsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CocktailsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
