/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import uk.ac.kcl.inf.group6.cocktail.ui.internal.CocktailActivator;

public class CocktailsUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return CocktailActivator.getInstance().getInjector("org.xtext.example.mydsl.Cocktails");
	}

}
