/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.example.mydsl.parser.antlr.internal.InternalCocktailsParser;
import org.xtext.example.mydsl.services.CocktailsGrammarAccess;

public class CocktailsParser extends AbstractAntlrParser {

	@Inject
	private CocktailsGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalCocktailsParser createParser(XtextTokenStream stream) {
		return new InternalCocktailsParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Order";
	}

	public CocktailsGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(CocktailsGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
