/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.generator

import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.xtext.generator.AbstractGenerator
import org.eclipse.xtext.generator.IFileSystemAccess2
import org.eclipse.xtext.generator.IGeneratorContext
import org.xtext.example.mydsl.cocktails.Order
import org.xtext.example.mydsl.cocktails.Instruction
import org.xtext.example.mydsl.cocktails.MakeStatement
import org.xtext.example.mydsl.cocktails.AddIngredient
import org.xtext.example.mydsl.cocktails.AddFixedIngredient
import org.xtext.example.mydsl.cocktails.FancyStatement
import org.xtext.example.mydsl.cocktails.AddIce
import org.xtext.example.mydsl.cocktails.MuddleStatement
import org.xtext.example.mydsl.cocktails.AddDecoration
import org.xtext.example.mydsl.cocktails.Expression
import org.xtext.example.mydsl.cocktails.Addition
import org.xtext.example.mydsl.cocktails.Multiplication
import org.xtext.example.mydsl.cocktails.IntLiteral
import java.net.URI
import java.net.URISyntaxException
import java.util.List
import org.eclipse.emf.ecore.EObject
import org.eclipse.emf.ecore.resource.Resource
import org.eclipse.epsilon.common.util.StringProperties
import org.eclipse.epsilon.emc.emf.EmfModel
import org.eclipse.epsilon.emc.emf.InMemoryEmfModel
import org.eclipse.epsilon.eol.exceptions.models.EolModelLoadingException
import org.eclipse.epsilon.eol.models.IModel
import org.eclipse.epsilon.eol.models.IRelativePathResolver
import org.eclipse.epsilon.etl.EtlModule
import org.xtext.example.mydsl.cocktails.CocktailsPackage

/**
 * Generates code from your model files on save.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#code-generation
 */
class CocktailsGenerator extends AbstractGenerator {
	
	private static class ConstantFolder extends ETLRunner{
		
		val Resource inModel
		
		new (Resource inModel){
			this.inModel=inModel
		}
		
		override protected getSource() {
			"constant_fold.etl"
		}
		
		override protected getModels() throws Exception {
			val srcModel= inModel.createInMemoryEmfModel("Source", CocktailsPackage.eNS_URI)
			val resourceSet=inModel.resourceSet
			val tgtResourceURI= org.eclipse.emf.common.util.URI.createFileURI("synthetic.cocktails")
			var tgtResource=resourceSet.getResource(tgtResourceURI,false)
			if(tgtResource!= null){
				tgtResource.contents.clear
			}else{
				tgtResource=resourceSet.createResource(tgtResourceURI)
			}
			val tgtModel=tgtResource.createInMemoryEmfModel("Target", CocktailsPackage.eNS_URI)
			#[
				srcModel,
				tgtModel
			]
		}
		
		
	}
	
	

	override void doGenerate(Resource resource, IFileSystemAccess2 fsa, IGeneratorContext context) {
		val model= resource.contents.head as Order
//		fsa.generateFile(deriveTargetFileNameFor(model, resource), model.doGenerate)
		val className=resource.deriveClassName
		
		
		val interimModel =new ConstantFolder(resource).execute as Order
		fsa.generateFile(className+'.java',interimModel.doGenerateClass(className))
	}
		
		
		//Create txt file
		def String deriveClassName(Resource resource){
			val originFilename=resource.URI.lastSegment
			
			originFilename.substring(0,originFilename.indexOf('.')).toFirstUpper+'Cocktail'
		}
//		
//		def deriveTargetFileNameFor(Order program, Resource resource) {
//			resource.URI.appendFileExtension('.txt').lastSegment
//		}
//		def String doGenerate(Order order)'''
//			Order instructions:
//			'''
		
		
		
		
		def  doGenerateClass(Order order, String className)'''
			
			
			public class «className»{
				public static void main(String[] args){
					int count=1;
					«order.instructions.map[generateJavaStatement(new Environment)].join('\n')»
					
				}
				
			}
		'''
		private static class Environment{
			var int counter=0
			
			def getFreshVarName()'''i«counter++»'''
			def exit(){counter--}
		}
		dispatch def String generateJavaStatement(Instruction ins, Environment env)''''''
		dispatch def String generateJavaStatement(MakeStatement ins, Environment env)'''
			System.out.println("Step"+count+":\n«ins.make.getName.toFirstUpper» it for «ins.time.generateJavaExpression» seconds");
			count++;'''
		dispatch def String generateJavaStatement(AddIngredient ins, Environment env)'''
			
			System.out.println("Step"+count+":\nadd ingredient «ins.name.toFirstUpper» for «ins.amount.generateJavaExpression» ml");
			count++;'''
		dispatch def String generateJavaStatement(AddFixedIngredient ins, Environment env)'''
			System.out.println("Step"+count+":\nadd ingredient «ins.name.toFirstUpper» for «ins.amount.generateJavaExpression» grams");
			count++;'''
		dispatch def String generateJavaStatement(FancyStatement ins, Environment env)'''
			System.out.println("Step"+count+":\nuse «ins.fcommand.getName.toFirstUpper»");
			count++;'''
		dispatch def String generateJavaStatement(MuddleStatement ins, Environment env)'''
			System.out.println("Step"+count+":\nuse mud machine to mud: \n«FOR idx:(0..ins.mudFruit.size-1)»«ins.mudFruit.get(idx).getName.toFirstUpper»«IF idx==ins.mudFruit.size-1»«ELSE»+ «ENDIF»«ENDFOR»\nfor «ins.mtimes.generateJavaExpression» times");
			count++;'''
//		dispatch def String generateJavaStatement(AddFruitformuddle ins, Environment env)'''
//			System.out.println("Step"+count+":\nput «ins.famount.generateJavaExpression» «ins.fruit.getName.toFirstUpper» into muddle machine");
//			count++;
//		'''
		dispatch def String generateJavaStatement(AddIce ins, Environment env)'''
			System.out.println("Step"+count+":\nput «ins.ounce.generateJavaExpression» ounce «ins.ice.getName.toFirstUpper» ice");
			count++;'''

		dispatch def String generateJavaStatement(AddDecoration ins, Environment env)'''
			System.out.println("Step"+count+":\nput «ins.decoration.getName.toFirstUpper» «ins.slice.generateJavaExpression» piece on the top of cocktail");
			count++;'''
		dispatch def String generateJavaExpression(Expression exp)''''''
		dispatch def String generateJavaExpression(Addition exp)'''
			«exp.left.generateJavaExpression»«FOR idx: (0..exp.operator.size-1)»«exp.operator.get(idx)»«exp.right.get(idx).generateJavaExpression»«ENDFOR»'''
		dispatch def String generateJavaExpression(Multiplication exp)'''
			«exp.left.generateJavaExpression»«FOR idx: (0..exp.operator.size-1)»«exp.operator.get(idx)»«exp.right.get(idx).generateJavaExpression»«ENDFOR»'''
		dispatch def String generateJavaExpression(IntLiteral exp)'''«exp.^val»'''
		
}


abstract class ETLRunner {

	protected def String getSource()

	protected def List<IModel> getModels() throws Exception

	def EObject execute() throws Exception {

		val module = new EtlModule

		module.parse(getSource.getFileURI)

		if (module.parseProblems.size > 0) {
			System.err.println("Parse errors occured...")
			module.parseProblems.forEach[System.err.println(it.toString())]

			return null
		}

		models.forEach[module.context.modelRepository.addModel(it)
		]

		module.execute

		val result = (module.context.modelRepository.getModelByName("Target") as EmfModel).resource.contents.head

		module.context.modelRepository.dispose

		result
	}

	protected def EmfModel createEmfModel(String name, String model, String metamodel, boolean readOnLoad,
		boolean storeOnDisposal) throws EolModelLoadingException, URISyntaxException {
		val emfModel = new EmfModel

		val properties = new StringProperties
		properties.put(EmfModel.PROPERTY_NAME, name)
		properties.put(EmfModel.PROPERTY_FILE_BASED_METAMODEL_URI, metamodel.getFileURI.toString)
		properties.put(EmfModel.PROPERTY_MODEL_URI, model.getFileURI.toString)
		properties.put(EmfModel.PROPERTY_READONLOAD, readOnLoad + "")
		properties.put(EmfModel.PROPERTY_STOREONDISPOSAL, storeOnDisposal + "")

		emfModel.load(properties, null as IRelativePathResolver)

		emfModel
	}

	protected def EmfModel createEmfModelByURI(String name, String model, String metamodel, boolean readOnLoad,
		boolean storeOnDisposal) throws EolModelLoadingException, URISyntaxException {
		val emfModel = new EmfModel

		val properties = new StringProperties
		properties.put(EmfModel.PROPERTY_NAME, name)
		properties.put(EmfModel.PROPERTY_METAMODEL_URI, metamodel)
		properties.put(EmfModel.PROPERTY_MODEL_URI, model.getFileURI.toString)
		properties.put(EmfModel.PROPERTY_READONLOAD, readOnLoad + "")
		properties.put(EmfModel.PROPERTY_STOREONDISPOSAL, storeOnDisposal + "")

		emfModel.load(properties, null as IRelativePathResolver)

		emfModel
	}

	protected def EmfModel createInMemoryEmfModel(Resource res, String name, String metamodel) throws EolModelLoadingException, URISyntaxException {
	    new InMemoryEmfModel(name, res, metamodel)
	}

	protected def URI getFileURI(String fileName) throws URISyntaxException {

		val binUri = ETLRunner.getResource(fileName).toURI
		var URI uri = null

		if (binUri.toString.indexOf("bin") > -1) {
			uri = new URI(binUri.toString.replaceAll("bin", "src"))
		} else {
			uri = binUri
		}

		return uri;
	}
}
