/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.cocktails;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add Decoration</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.cocktails.AddDecoration#getDecoration <em>Decoration</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.cocktails.AddDecoration#getSlice <em>Slice</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#getAddDecoration()
 * @model
 * @generated
 */
public interface AddDecoration extends Instruction
{
  /**
   * Returns the value of the '<em><b>Decoration</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.cocktails.DecorationStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Decoration</em>' attribute.
   * @see org.xtext.example.mydsl.cocktails.DecorationStatement
   * @see #setDecoration(DecorationStatement)
   * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#getAddDecoration_Decoration()
   * @model
   * @generated
   */
  DecorationStatement getDecoration();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.cocktails.AddDecoration#getDecoration <em>Decoration</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Decoration</em>' attribute.
   * @see org.xtext.example.mydsl.cocktails.DecorationStatement
   * @see #getDecoration()
   * @generated
   */
  void setDecoration(DecorationStatement value);

  /**
   * Returns the value of the '<em><b>Slice</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Slice</em>' containment reference.
   * @see #setSlice(Expression)
   * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#getAddDecoration_Slice()
   * @model containment="true"
   * @generated
   */
  Expression getSlice();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.cocktails.AddDecoration#getSlice <em>Slice</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Slice</em>' containment reference.
   * @see #getSlice()
   * @generated
   */
  void setSlice(Expression value);

} // AddDecoration
