/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.cocktails;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add Ingredient</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.cocktails.AddIngredient#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.cocktails.AddIngredient#getAmount <em>Amount</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#getAddIngredient()
 * @model
 * @generated
 */
public interface AddIngredient extends Instruction
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#getAddIngredient_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.cocktails.AddIngredient#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Amount</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Amount</em>' containment reference.
   * @see #setAmount(Expression)
   * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#getAddIngredient_Amount()
   * @model containment="true"
   * @generated
   */
  Expression getAmount();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.cocktails.AddIngredient#getAmount <em>Amount</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Amount</em>' containment reference.
   * @see #getAmount()
   * @generated
   */
  void setAmount(Expression value);

} // AddIngredient
