/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.cocktails;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Add Ice</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.cocktails.AddIce#getIce <em>Ice</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.cocktails.AddIce#getOunce <em>Ounce</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#getAddIce()
 * @model
 * @generated
 */
public interface AddIce extends Instruction
{
  /**
   * Returns the value of the '<em><b>Ice</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.cocktails.IceStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ice</em>' attribute.
   * @see org.xtext.example.mydsl.cocktails.IceStatement
   * @see #setIce(IceStatement)
   * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#getAddIce_Ice()
   * @model
   * @generated
   */
  IceStatement getIce();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.cocktails.AddIce#getIce <em>Ice</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ice</em>' attribute.
   * @see org.xtext.example.mydsl.cocktails.IceStatement
   * @see #getIce()
   * @generated
   */
  void setIce(IceStatement value);

  /**
   * Returns the value of the '<em><b>Ounce</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ounce</em>' containment reference.
   * @see #setOunce(Expression)
   * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#getAddIce_Ounce()
   * @model containment="true"
   * @generated
   */
  Expression getOunce();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.cocktails.AddIce#getOunce <em>Ounce</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ounce</em>' containment reference.
   * @see #getOunce()
   * @generated
   */
  void setOunce(Expression value);

} // AddIce
