/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.cocktails;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.cocktails.CocktailsFactory
 * @model kind="package"
 * @generated
 */
public interface CocktailsPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "cocktails";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/example/mydsl/Cocktails";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "cocktails";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  CocktailsPackage eINSTANCE = org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.cocktails.impl.OrderImpl <em>Order</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.cocktails.impl.OrderImpl
   * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getOrder()
   * @generated
   */
  int ORDER = 0;

  /**
   * The feature id for the '<em><b>Instructions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDER__INSTRUCTIONS = 0;

  /**
   * The number of structural features of the '<em>Order</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ORDER_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.cocktails.impl.InstructionImpl <em>Instruction</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.cocktails.impl.InstructionImpl
   * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getInstruction()
   * @generated
   */
  int INSTRUCTION = 1;

  /**
   * The number of structural features of the '<em>Instruction</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.cocktails.impl.AddIngredientImpl <em>Add Ingredient</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.cocktails.impl.AddIngredientImpl
   * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getAddIngredient()
   * @generated
   */
  int ADD_INGREDIENT = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_INGREDIENT__NAME = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Amount</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_INGREDIENT__AMOUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Add Ingredient</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_INGREDIENT_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.cocktails.impl.AddFixedIngredientImpl <em>Add Fixed Ingredient</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.cocktails.impl.AddFixedIngredientImpl
   * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getAddFixedIngredient()
   * @generated
   */
  int ADD_FIXED_INGREDIENT = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_FIXED_INGREDIENT__NAME = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Amount</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_FIXED_INGREDIENT__AMOUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Add Fixed Ingredient</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_FIXED_INGREDIENT_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.cocktails.impl.FancyStatementImpl <em>Fancy Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.cocktails.impl.FancyStatementImpl
   * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getFancyStatement()
   * @generated
   */
  int FANCY_STATEMENT = 4;

  /**
   * The feature id for the '<em><b>Fcommand</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FANCY_STATEMENT__FCOMMAND = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Fancy Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FANCY_STATEMENT_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.cocktails.impl.AddIceImpl <em>Add Ice</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.cocktails.impl.AddIceImpl
   * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getAddIce()
   * @generated
   */
  int ADD_ICE = 5;

  /**
   * The feature id for the '<em><b>Ice</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_ICE__ICE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Ounce</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_ICE__OUNCE = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Add Ice</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_ICE_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.cocktails.impl.MuddleStatementImpl <em>Muddle Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.cocktails.impl.MuddleStatementImpl
   * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getMuddleStatement()
   * @generated
   */
  int MUDDLE_STATEMENT = 6;

  /**
   * The feature id for the '<em><b>Mud Fruit</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MUDDLE_STATEMENT__MUD_FRUIT = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Mtimes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MUDDLE_STATEMENT__MTIMES = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Muddle Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MUDDLE_STATEMENT_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.cocktails.impl.AddDecorationImpl <em>Add Decoration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.cocktails.impl.AddDecorationImpl
   * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getAddDecoration()
   * @generated
   */
  int ADD_DECORATION = 7;

  /**
   * The feature id for the '<em><b>Decoration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_DECORATION__DECORATION = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Slice</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_DECORATION__SLICE = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Add Decoration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADD_DECORATION_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.cocktails.impl.MakeStatementImpl <em>Make Statement</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.cocktails.impl.MakeStatementImpl
   * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getMakeStatement()
   * @generated
   */
  int MAKE_STATEMENT = 8;

  /**
   * The feature id for the '<em><b>Make</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAKE_STATEMENT__MAKE = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAKE_STATEMENT__TIME = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Make Statement</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MAKE_STATEMENT_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.cocktails.impl.ExpressionImpl <em>Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.cocktails.impl.ExpressionImpl
   * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getExpression()
   * @generated
   */
  int EXPRESSION = 9;

  /**
   * The number of structural features of the '<em>Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXPRESSION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.cocktails.impl.IntLiteralImpl <em>Int Literal</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.cocktails.impl.IntLiteralImpl
   * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getIntLiteral()
   * @generated
   */
  int INT_LITERAL = 10;

  /**
   * The feature id for the '<em><b>Val</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL__VAL = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Literal</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_LITERAL_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.cocktails.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.cocktails.impl.VariableDeclarationImpl
   * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getVariableDeclaration()
   * @generated
   */
  int VARIABLE_DECLARATION = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__NAME = INSTRUCTION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Value</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION__VALUE = INSTRUCTION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Variable Declaration</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int VARIABLE_DECLARATION_FEATURE_COUNT = INSTRUCTION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.cocktails.impl.IntVarExpressionImpl <em>Int Var Expression</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.cocktails.impl.IntVarExpressionImpl
   * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getIntVarExpression()
   * @generated
   */
  int INT_VAR_EXPRESSION = 12;

  /**
   * The feature id for the '<em><b>Var</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VAR_EXPRESSION__VAR = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Int Var Expression</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INT_VAR_EXPRESSION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.cocktails.impl.AdditionImpl <em>Addition</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.cocktails.impl.AdditionImpl
   * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getAddition()
   * @generated
   */
  int ADDITION = 13;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Addition</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ADDITION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.cocktails.impl.MultiplicationImpl <em>Multiplication</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.cocktails.impl.MultiplicationImpl
   * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getMultiplication()
   * @generated
   */
  int MULTIPLICATION = 14;

  /**
   * The feature id for the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__LEFT = EXPRESSION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Operator</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__OPERATOR = EXPRESSION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Right</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION__RIGHT = EXPRESSION_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>Multiplication</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MULTIPLICATION_FEATURE_COUNT = EXPRESSION_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.cocktails.FancyMakeStatement <em>Fancy Make Statement</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.cocktails.FancyMakeStatement
   * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getFancyMakeStatement()
   * @generated
   */
  int FANCY_MAKE_STATEMENT = 15;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.cocktails.IceStatement <em>Ice Statement</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.cocktails.IceStatement
   * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getIceStatement()
   * @generated
   */
  int ICE_STATEMENT = 16;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.cocktails.FruitStatement <em>Fruit Statement</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.cocktails.FruitStatement
   * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getFruitStatement()
   * @generated
   */
  int FRUIT_STATEMENT = 17;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.cocktails.DecorationStatement <em>Decoration Statement</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.cocktails.DecorationStatement
   * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getDecorationStatement()
   * @generated
   */
  int DECORATION_STATEMENT = 18;

  /**
   * The meta object id for the '{@link org.xtext.example.mydsl.cocktails.MakeCommand <em>Make Command</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.example.mydsl.cocktails.MakeCommand
   * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getMakeCommand()
   * @generated
   */
  int MAKE_COMMAND = 19;


  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.cocktails.Order <em>Order</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Order</em>'.
   * @see org.xtext.example.mydsl.cocktails.Order
   * @generated
   */
  EClass getOrder();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.cocktails.Order#getInstructions <em>Instructions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Instructions</em>'.
   * @see org.xtext.example.mydsl.cocktails.Order#getInstructions()
   * @see #getOrder()
   * @generated
   */
  EReference getOrder_Instructions();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.cocktails.Instruction <em>Instruction</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Instruction</em>'.
   * @see org.xtext.example.mydsl.cocktails.Instruction
   * @generated
   */
  EClass getInstruction();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.cocktails.AddIngredient <em>Add Ingredient</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add Ingredient</em>'.
   * @see org.xtext.example.mydsl.cocktails.AddIngredient
   * @generated
   */
  EClass getAddIngredient();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.cocktails.AddIngredient#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.cocktails.AddIngredient#getName()
   * @see #getAddIngredient()
   * @generated
   */
  EAttribute getAddIngredient_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.cocktails.AddIngredient#getAmount <em>Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Amount</em>'.
   * @see org.xtext.example.mydsl.cocktails.AddIngredient#getAmount()
   * @see #getAddIngredient()
   * @generated
   */
  EReference getAddIngredient_Amount();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.cocktails.AddFixedIngredient <em>Add Fixed Ingredient</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add Fixed Ingredient</em>'.
   * @see org.xtext.example.mydsl.cocktails.AddFixedIngredient
   * @generated
   */
  EClass getAddFixedIngredient();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.cocktails.AddFixedIngredient#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.cocktails.AddFixedIngredient#getName()
   * @see #getAddFixedIngredient()
   * @generated
   */
  EAttribute getAddFixedIngredient_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.cocktails.AddFixedIngredient#getAmount <em>Amount</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Amount</em>'.
   * @see org.xtext.example.mydsl.cocktails.AddFixedIngredient#getAmount()
   * @see #getAddFixedIngredient()
   * @generated
   */
  EReference getAddFixedIngredient_Amount();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.cocktails.FancyStatement <em>Fancy Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Fancy Statement</em>'.
   * @see org.xtext.example.mydsl.cocktails.FancyStatement
   * @generated
   */
  EClass getFancyStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.cocktails.FancyStatement#getFcommand <em>Fcommand</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Fcommand</em>'.
   * @see org.xtext.example.mydsl.cocktails.FancyStatement#getFcommand()
   * @see #getFancyStatement()
   * @generated
   */
  EAttribute getFancyStatement_Fcommand();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.cocktails.AddIce <em>Add Ice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add Ice</em>'.
   * @see org.xtext.example.mydsl.cocktails.AddIce
   * @generated
   */
  EClass getAddIce();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.cocktails.AddIce#getIce <em>Ice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Ice</em>'.
   * @see org.xtext.example.mydsl.cocktails.AddIce#getIce()
   * @see #getAddIce()
   * @generated
   */
  EAttribute getAddIce_Ice();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.cocktails.AddIce#getOunce <em>Ounce</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Ounce</em>'.
   * @see org.xtext.example.mydsl.cocktails.AddIce#getOunce()
   * @see #getAddIce()
   * @generated
   */
  EReference getAddIce_Ounce();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.cocktails.MuddleStatement <em>Muddle Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Muddle Statement</em>'.
   * @see org.xtext.example.mydsl.cocktails.MuddleStatement
   * @generated
   */
  EClass getMuddleStatement();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.cocktails.MuddleStatement#getMudFruit <em>Mud Fruit</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Mud Fruit</em>'.
   * @see org.xtext.example.mydsl.cocktails.MuddleStatement#getMudFruit()
   * @see #getMuddleStatement()
   * @generated
   */
  EAttribute getMuddleStatement_MudFruit();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.cocktails.MuddleStatement#getMtimes <em>Mtimes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Mtimes</em>'.
   * @see org.xtext.example.mydsl.cocktails.MuddleStatement#getMtimes()
   * @see #getMuddleStatement()
   * @generated
   */
  EReference getMuddleStatement_Mtimes();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.cocktails.AddDecoration <em>Add Decoration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Add Decoration</em>'.
   * @see org.xtext.example.mydsl.cocktails.AddDecoration
   * @generated
   */
  EClass getAddDecoration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.cocktails.AddDecoration#getDecoration <em>Decoration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Decoration</em>'.
   * @see org.xtext.example.mydsl.cocktails.AddDecoration#getDecoration()
   * @see #getAddDecoration()
   * @generated
   */
  EAttribute getAddDecoration_Decoration();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.cocktails.AddDecoration#getSlice <em>Slice</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Slice</em>'.
   * @see org.xtext.example.mydsl.cocktails.AddDecoration#getSlice()
   * @see #getAddDecoration()
   * @generated
   */
  EReference getAddDecoration_Slice();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.cocktails.MakeStatement <em>Make Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Make Statement</em>'.
   * @see org.xtext.example.mydsl.cocktails.MakeStatement
   * @generated
   */
  EClass getMakeStatement();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.cocktails.MakeStatement#getMake <em>Make</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Make</em>'.
   * @see org.xtext.example.mydsl.cocktails.MakeStatement#getMake()
   * @see #getMakeStatement()
   * @generated
   */
  EAttribute getMakeStatement_Make();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.cocktails.MakeStatement#getTime <em>Time</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Time</em>'.
   * @see org.xtext.example.mydsl.cocktails.MakeStatement#getTime()
   * @see #getMakeStatement()
   * @generated
   */
  EReference getMakeStatement_Time();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.cocktails.Expression <em>Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Expression</em>'.
   * @see org.xtext.example.mydsl.cocktails.Expression
   * @generated
   */
  EClass getExpression();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.cocktails.IntLiteral <em>Int Literal</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Literal</em>'.
   * @see org.xtext.example.mydsl.cocktails.IntLiteral
   * @generated
   */
  EClass getIntLiteral();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.cocktails.IntLiteral#getVal <em>Val</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Val</em>'.
   * @see org.xtext.example.mydsl.cocktails.IntLiteral#getVal()
   * @see #getIntLiteral()
   * @generated
   */
  EAttribute getIntLiteral_Val();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.cocktails.VariableDeclaration <em>Variable Declaration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Variable Declaration</em>'.
   * @see org.xtext.example.mydsl.cocktails.VariableDeclaration
   * @generated
   */
  EClass getVariableDeclaration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.cocktails.VariableDeclaration#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.example.mydsl.cocktails.VariableDeclaration#getName()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.example.mydsl.cocktails.VariableDeclaration#getValue <em>Value</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Value</em>'.
   * @see org.xtext.example.mydsl.cocktails.VariableDeclaration#getValue()
   * @see #getVariableDeclaration()
   * @generated
   */
  EAttribute getVariableDeclaration_Value();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.cocktails.IntVarExpression <em>Int Var Expression</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Int Var Expression</em>'.
   * @see org.xtext.example.mydsl.cocktails.IntVarExpression
   * @generated
   */
  EClass getIntVarExpression();

  /**
   * Returns the meta object for the reference '{@link org.xtext.example.mydsl.cocktails.IntVarExpression#getVar <em>Var</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the reference '<em>Var</em>'.
   * @see org.xtext.example.mydsl.cocktails.IntVarExpression#getVar()
   * @see #getIntVarExpression()
   * @generated
   */
  EReference getIntVarExpression_Var();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.cocktails.Addition <em>Addition</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Addition</em>'.
   * @see org.xtext.example.mydsl.cocktails.Addition
   * @generated
   */
  EClass getAddition();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.cocktails.Addition#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.mydsl.cocktails.Addition#getLeft()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Left();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.cocktails.Addition#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operator</em>'.
   * @see org.xtext.example.mydsl.cocktails.Addition#getOperator()
   * @see #getAddition()
   * @generated
   */
  EAttribute getAddition_Operator();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.cocktails.Addition#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see org.xtext.example.mydsl.cocktails.Addition#getRight()
   * @see #getAddition()
   * @generated
   */
  EReference getAddition_Right();

  /**
   * Returns the meta object for class '{@link org.xtext.example.mydsl.cocktails.Multiplication <em>Multiplication</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Multiplication</em>'.
   * @see org.xtext.example.mydsl.cocktails.Multiplication
   * @generated
   */
  EClass getMultiplication();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.example.mydsl.cocktails.Multiplication#getLeft <em>Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Left</em>'.
   * @see org.xtext.example.mydsl.cocktails.Multiplication#getLeft()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Left();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.example.mydsl.cocktails.Multiplication#getOperator <em>Operator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Operator</em>'.
   * @see org.xtext.example.mydsl.cocktails.Multiplication#getOperator()
   * @see #getMultiplication()
   * @generated
   */
  EAttribute getMultiplication_Operator();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.example.mydsl.cocktails.Multiplication#getRight <em>Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Right</em>'.
   * @see org.xtext.example.mydsl.cocktails.Multiplication#getRight()
   * @see #getMultiplication()
   * @generated
   */
  EReference getMultiplication_Right();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.cocktails.FancyMakeStatement <em>Fancy Make Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Fancy Make Statement</em>'.
   * @see org.xtext.example.mydsl.cocktails.FancyMakeStatement
   * @generated
   */
  EEnum getFancyMakeStatement();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.cocktails.IceStatement <em>Ice Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Ice Statement</em>'.
   * @see org.xtext.example.mydsl.cocktails.IceStatement
   * @generated
   */
  EEnum getIceStatement();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.cocktails.FruitStatement <em>Fruit Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Fruit Statement</em>'.
   * @see org.xtext.example.mydsl.cocktails.FruitStatement
   * @generated
   */
  EEnum getFruitStatement();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.cocktails.DecorationStatement <em>Decoration Statement</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Decoration Statement</em>'.
   * @see org.xtext.example.mydsl.cocktails.DecorationStatement
   * @generated
   */
  EEnum getDecorationStatement();

  /**
   * Returns the meta object for enum '{@link org.xtext.example.mydsl.cocktails.MakeCommand <em>Make Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Make Command</em>'.
   * @see org.xtext.example.mydsl.cocktails.MakeCommand
   * @generated
   */
  EEnum getMakeCommand();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  CocktailsFactory getCocktailsFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.cocktails.impl.OrderImpl <em>Order</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.cocktails.impl.OrderImpl
     * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getOrder()
     * @generated
     */
    EClass ORDER = eINSTANCE.getOrder();

    /**
     * The meta object literal for the '<em><b>Instructions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ORDER__INSTRUCTIONS = eINSTANCE.getOrder_Instructions();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.cocktails.impl.InstructionImpl <em>Instruction</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.cocktails.impl.InstructionImpl
     * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getInstruction()
     * @generated
     */
    EClass INSTRUCTION = eINSTANCE.getInstruction();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.cocktails.impl.AddIngredientImpl <em>Add Ingredient</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.cocktails.impl.AddIngredientImpl
     * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getAddIngredient()
     * @generated
     */
    EClass ADD_INGREDIENT = eINSTANCE.getAddIngredient();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADD_INGREDIENT__NAME = eINSTANCE.getAddIngredient_Name();

    /**
     * The meta object literal for the '<em><b>Amount</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD_INGREDIENT__AMOUNT = eINSTANCE.getAddIngredient_Amount();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.cocktails.impl.AddFixedIngredientImpl <em>Add Fixed Ingredient</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.cocktails.impl.AddFixedIngredientImpl
     * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getAddFixedIngredient()
     * @generated
     */
    EClass ADD_FIXED_INGREDIENT = eINSTANCE.getAddFixedIngredient();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADD_FIXED_INGREDIENT__NAME = eINSTANCE.getAddFixedIngredient_Name();

    /**
     * The meta object literal for the '<em><b>Amount</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD_FIXED_INGREDIENT__AMOUNT = eINSTANCE.getAddFixedIngredient_Amount();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.cocktails.impl.FancyStatementImpl <em>Fancy Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.cocktails.impl.FancyStatementImpl
     * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getFancyStatement()
     * @generated
     */
    EClass FANCY_STATEMENT = eINSTANCE.getFancyStatement();

    /**
     * The meta object literal for the '<em><b>Fcommand</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FANCY_STATEMENT__FCOMMAND = eINSTANCE.getFancyStatement_Fcommand();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.cocktails.impl.AddIceImpl <em>Add Ice</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.cocktails.impl.AddIceImpl
     * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getAddIce()
     * @generated
     */
    EClass ADD_ICE = eINSTANCE.getAddIce();

    /**
     * The meta object literal for the '<em><b>Ice</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADD_ICE__ICE = eINSTANCE.getAddIce_Ice();

    /**
     * The meta object literal for the '<em><b>Ounce</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD_ICE__OUNCE = eINSTANCE.getAddIce_Ounce();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.cocktails.impl.MuddleStatementImpl <em>Muddle Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.cocktails.impl.MuddleStatementImpl
     * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getMuddleStatement()
     * @generated
     */
    EClass MUDDLE_STATEMENT = eINSTANCE.getMuddleStatement();

    /**
     * The meta object literal for the '<em><b>Mud Fruit</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MUDDLE_STATEMENT__MUD_FRUIT = eINSTANCE.getMuddleStatement_MudFruit();

    /**
     * The meta object literal for the '<em><b>Mtimes</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MUDDLE_STATEMENT__MTIMES = eINSTANCE.getMuddleStatement_Mtimes();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.cocktails.impl.AddDecorationImpl <em>Add Decoration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.cocktails.impl.AddDecorationImpl
     * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getAddDecoration()
     * @generated
     */
    EClass ADD_DECORATION = eINSTANCE.getAddDecoration();

    /**
     * The meta object literal for the '<em><b>Decoration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADD_DECORATION__DECORATION = eINSTANCE.getAddDecoration_Decoration();

    /**
     * The meta object literal for the '<em><b>Slice</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADD_DECORATION__SLICE = eINSTANCE.getAddDecoration_Slice();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.cocktails.impl.MakeStatementImpl <em>Make Statement</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.cocktails.impl.MakeStatementImpl
     * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getMakeStatement()
     * @generated
     */
    EClass MAKE_STATEMENT = eINSTANCE.getMakeStatement();

    /**
     * The meta object literal for the '<em><b>Make</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MAKE_STATEMENT__MAKE = eINSTANCE.getMakeStatement_Make();

    /**
     * The meta object literal for the '<em><b>Time</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MAKE_STATEMENT__TIME = eINSTANCE.getMakeStatement_Time();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.cocktails.impl.ExpressionImpl <em>Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.cocktails.impl.ExpressionImpl
     * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getExpression()
     * @generated
     */
    EClass EXPRESSION = eINSTANCE.getExpression();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.cocktails.impl.IntLiteralImpl <em>Int Literal</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.cocktails.impl.IntLiteralImpl
     * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getIntLiteral()
     * @generated
     */
    EClass INT_LITERAL = eINSTANCE.getIntLiteral();

    /**
     * The meta object literal for the '<em><b>Val</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INT_LITERAL__VAL = eINSTANCE.getIntLiteral_Val();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.cocktails.impl.VariableDeclarationImpl <em>Variable Declaration</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.cocktails.impl.VariableDeclarationImpl
     * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getVariableDeclaration()
     * @generated
     */
    EClass VARIABLE_DECLARATION = eINSTANCE.getVariableDeclaration();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__NAME = eINSTANCE.getVariableDeclaration_Name();

    /**
     * The meta object literal for the '<em><b>Value</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute VARIABLE_DECLARATION__VALUE = eINSTANCE.getVariableDeclaration_Value();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.cocktails.impl.IntVarExpressionImpl <em>Int Var Expression</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.cocktails.impl.IntVarExpressionImpl
     * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getIntVarExpression()
     * @generated
     */
    EClass INT_VAR_EXPRESSION = eINSTANCE.getIntVarExpression();

    /**
     * The meta object literal for the '<em><b>Var</b></em>' reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INT_VAR_EXPRESSION__VAR = eINSTANCE.getIntVarExpression_Var();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.cocktails.impl.AdditionImpl <em>Addition</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.cocktails.impl.AdditionImpl
     * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getAddition()
     * @generated
     */
    EClass ADDITION = eINSTANCE.getAddition();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__LEFT = eINSTANCE.getAddition_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ADDITION__OPERATOR = eINSTANCE.getAddition_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ADDITION__RIGHT = eINSTANCE.getAddition_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.cocktails.impl.MultiplicationImpl <em>Multiplication</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.cocktails.impl.MultiplicationImpl
     * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getMultiplication()
     * @generated
     */
    EClass MULTIPLICATION = eINSTANCE.getMultiplication();

    /**
     * The meta object literal for the '<em><b>Left</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__LEFT = eINSTANCE.getMultiplication_Left();

    /**
     * The meta object literal for the '<em><b>Operator</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MULTIPLICATION__OPERATOR = eINSTANCE.getMultiplication_Operator();

    /**
     * The meta object literal for the '<em><b>Right</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MULTIPLICATION__RIGHT = eINSTANCE.getMultiplication_Right();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.cocktails.FancyMakeStatement <em>Fancy Make Statement</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.cocktails.FancyMakeStatement
     * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getFancyMakeStatement()
     * @generated
     */
    EEnum FANCY_MAKE_STATEMENT = eINSTANCE.getFancyMakeStatement();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.cocktails.IceStatement <em>Ice Statement</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.cocktails.IceStatement
     * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getIceStatement()
     * @generated
     */
    EEnum ICE_STATEMENT = eINSTANCE.getIceStatement();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.cocktails.FruitStatement <em>Fruit Statement</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.cocktails.FruitStatement
     * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getFruitStatement()
     * @generated
     */
    EEnum FRUIT_STATEMENT = eINSTANCE.getFruitStatement();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.cocktails.DecorationStatement <em>Decoration Statement</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.cocktails.DecorationStatement
     * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getDecorationStatement()
     * @generated
     */
    EEnum DECORATION_STATEMENT = eINSTANCE.getDecorationStatement();

    /**
     * The meta object literal for the '{@link org.xtext.example.mydsl.cocktails.MakeCommand <em>Make Command</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.example.mydsl.cocktails.MakeCommand
     * @see org.xtext.example.mydsl.cocktails.impl.CocktailsPackageImpl#getMakeCommand()
     * @generated
     */
    EEnum MAKE_COMMAND = eINSTANCE.getMakeCommand();

  }

} //CocktailsPackage
