/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.cocktails;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Decoration Statement</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#getDecorationStatement()
 * @model
 * @generated
 */
public enum DecorationStatement implements Enumerator
{
  /**
   * The '<em><b>Orange</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ORANGE_VALUE
   * @generated
   * @ordered
   */
  ORANGE(0, "orange", "orange"),

  /**
   * The '<em><b>Lemon</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LEMON_VALUE
   * @generated
   * @ordered
   */
  LEMON(1, "lemon", "lemon"),

  /**
   * The '<em><b>Lime</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LIME_VALUE
   * @generated
   * @ordered
   */
  LIME(2, "lime", "lime"),

  /**
   * The '<em><b>Olive</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #OLIVE_VALUE
   * @generated
   * @ordered
   */
  OLIVE(3, "olive", "olive"),

  /**
   * The '<em><b>Cherry</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CHERRY_VALUE
   * @generated
   * @ordered
   */
  CHERRY(4, "cherry", "cherry"),

  /**
   * The '<em><b>Mint</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MINT_VALUE
   * @generated
   * @ordered
   */
  MINT(5, "mint", "mint"),

  /**
   * The '<em><b>Rose</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ROSE_VALUE
   * @generated
   * @ordered
   */
  ROSE(6, "rose", "rose"),

  /**
   * The '<em><b>Cinnamon</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CINNAMON_VALUE
   * @generated
   * @ordered
   */
  CINNAMON(7, "cinnamon", "cinnamon"),

  /**
   * The '<em><b>Mango</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MANGO_VALUE
   * @generated
   * @ordered
   */
  MANGO(8, "mango", "mango"),

  /**
   * The '<em><b>Grapefruit</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GRAPEFRUIT_VALUE
   * @generated
   * @ordered
   */
  GRAPEFRUIT(9, "grapefruit", "grapefruit");

  /**
   * The '<em><b>Orange</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ORANGE
   * @model name="orange"
   * @generated
   * @ordered
   */
  public static final int ORANGE_VALUE = 0;

  /**
   * The '<em><b>Lemon</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LEMON
   * @model name="lemon"
   * @generated
   * @ordered
   */
  public static final int LEMON_VALUE = 1;

  /**
   * The '<em><b>Lime</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LIME
   * @model name="lime"
   * @generated
   * @ordered
   */
  public static final int LIME_VALUE = 2;

  /**
   * The '<em><b>Olive</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #OLIVE
   * @model name="olive"
   * @generated
   * @ordered
   */
  public static final int OLIVE_VALUE = 3;

  /**
   * The '<em><b>Cherry</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CHERRY
   * @model name="cherry"
   * @generated
   * @ordered
   */
  public static final int CHERRY_VALUE = 4;

  /**
   * The '<em><b>Mint</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MINT
   * @model name="mint"
   * @generated
   * @ordered
   */
  public static final int MINT_VALUE = 5;

  /**
   * The '<em><b>Rose</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ROSE
   * @model name="rose"
   * @generated
   * @ordered
   */
  public static final int ROSE_VALUE = 6;

  /**
   * The '<em><b>Cinnamon</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CINNAMON
   * @model name="cinnamon"
   * @generated
   * @ordered
   */
  public static final int CINNAMON_VALUE = 7;

  /**
   * The '<em><b>Mango</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MANGO
   * @model name="mango"
   * @generated
   * @ordered
   */
  public static final int MANGO_VALUE = 8;

  /**
   * The '<em><b>Grapefruit</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GRAPEFRUIT
   * @model name="grapefruit"
   * @generated
   * @ordered
   */
  public static final int GRAPEFRUIT_VALUE = 9;

  /**
   * An array of all the '<em><b>Decoration Statement</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final DecorationStatement[] VALUES_ARRAY =
    new DecorationStatement[]
    {
      ORANGE,
      LEMON,
      LIME,
      OLIVE,
      CHERRY,
      MINT,
      ROSE,
      CINNAMON,
      MANGO,
      GRAPEFRUIT,
    };

  /**
   * A public read-only list of all the '<em><b>Decoration Statement</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<DecorationStatement> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Decoration Statement</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static DecorationStatement get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      DecorationStatement result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Decoration Statement</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static DecorationStatement getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      DecorationStatement result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Decoration Statement</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static DecorationStatement get(int value)
  {
    switch (value)
    {
      case ORANGE_VALUE: return ORANGE;
      case LEMON_VALUE: return LEMON;
      case LIME_VALUE: return LIME;
      case OLIVE_VALUE: return OLIVE;
      case CHERRY_VALUE: return CHERRY;
      case MINT_VALUE: return MINT;
      case ROSE_VALUE: return ROSE;
      case CINNAMON_VALUE: return CINNAMON;
      case MANGO_VALUE: return MANGO;
      case GRAPEFRUIT_VALUE: return GRAPEFRUIT;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private DecorationStatement(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //DecorationStatement
