/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.cocktails;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fancy Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.cocktails.FancyStatement#getFcommand <em>Fcommand</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#getFancyStatement()
 * @model
 * @generated
 */
public interface FancyStatement extends Instruction
{
  /**
   * Returns the value of the '<em><b>Fcommand</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.cocktails.FancyMakeStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fcommand</em>' attribute.
   * @see org.xtext.example.mydsl.cocktails.FancyMakeStatement
   * @see #setFcommand(FancyMakeStatement)
   * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#getFancyStatement_Fcommand()
   * @model
   * @generated
   */
  FancyMakeStatement getFcommand();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.cocktails.FancyStatement#getFcommand <em>Fcommand</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fcommand</em>' attribute.
   * @see org.xtext.example.mydsl.cocktails.FancyMakeStatement
   * @see #getFcommand()
   * @generated
   */
  void setFcommand(FancyMakeStatement value);

} // FancyStatement
