/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.cocktails;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Fruit Statement</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#getFruitStatement()
 * @model
 * @generated
 */
public enum FruitStatement implements Enumerator
{
  /**
   * The '<em><b>Lime</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LIME_VALUE
   * @generated
   * @ordered
   */
  LIME(0, "lime", "lime"),

  /**
   * The '<em><b>Lemon</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LEMON_VALUE
   * @generated
   * @ordered
   */
  LEMON(1, "lemon", "lemon"),

  /**
   * The '<em><b>Orange</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ORANGE_VALUE
   * @generated
   * @ordered
   */
  ORANGE(2, "orange", "orange"),

  /**
   * The '<em><b>Grapefruit</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GRAPEFRUIT_VALUE
   * @generated
   * @ordered
   */
  GRAPEFRUIT(3, "grapefruit", "grapefruit"),

  /**
   * The '<em><b>Pineapple</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PINEAPPLE_VALUE
   * @generated
   * @ordered
   */
  PINEAPPLE(4, "pineapple", "pineapple"),

  /**
   * The '<em><b>Mango</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MANGO_VALUE
   * @generated
   * @ordered
   */
  MANGO(5, "mango", "mango"),

  /**
   * The '<em><b>Kiwi</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #KIWI_VALUE
   * @generated
   * @ordered
   */
  KIWI(6, "kiwi", "kiwi"),

  /**
   * The '<em><b>Strawberry</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #STRAWBERRY_VALUE
   * @generated
   * @ordered
   */
  STRAWBERRY(7, "strawberry", "strawberry"),

  /**
   * The '<em><b>Blueberry</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BLUEBERRY_VALUE
   * @generated
   * @ordered
   */
  BLUEBERRY(8, "blueberry", "blueberry"),

  /**
   * The '<em><b>Raspberry</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RASPBERRY_VALUE
   * @generated
   * @ordered
   */
  RASPBERRY(9, "raspberry", "raspberry"),

  /**
   * The '<em><b>Blackberry</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BLACKBERRY_VALUE
   * @generated
   * @ordered
   */
  BLACKBERRY(10, "blackberry", "blackberry"),

  /**
   * The '<em><b>Cherry</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CHERRY_VALUE
   * @generated
   * @ordered
   */
  CHERRY(11, "cherry", "cherry"),

  /**
   * The '<em><b>Peach</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PEACH_VALUE
   * @generated
   * @ordered
   */
  PEACH(12, "peach", "peach"),

  /**
   * The '<em><b>Plum</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PLUM_VALUE
   * @generated
   * @ordered
   */
  PLUM(13, "plum", "plum"),

  /**
   * The '<em><b>Watermelon</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WATERMELON_VALUE
   * @generated
   * @ordered
   */
  WATERMELON(14, "watermelon", "watermelon"),

  /**
   * The '<em><b>Cucumber</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CUCUMBER_VALUE
   * @generated
   * @ordered
   */
  CUCUMBER(15, "cucumber", "cucumber"),

  /**
   * The '<em><b>Mint</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MINT_VALUE
   * @generated
   * @ordered
   */
  MINT(16, "mint", "mint"),

  /**
   * The '<em><b>Basil</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BASIL_VALUE
   * @generated
   * @ordered
   */
  BASIL(17, "basil", "basil"),

  /**
   * The '<em><b>Thyme</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #THYME_VALUE
   * @generated
   * @ordered
   */
  THYME(18, "thyme", "thyme"),

  /**
   * The '<em><b>Ginger</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GINGER_VALUE
   * @generated
   * @ordered
   */
  GINGER(19, "ginger", "ginger");

  /**
   * The '<em><b>Lime</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LIME
   * @model name="lime"
   * @generated
   * @ordered
   */
  public static final int LIME_VALUE = 0;

  /**
   * The '<em><b>Lemon</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #LEMON
   * @model name="lemon"
   * @generated
   * @ordered
   */
  public static final int LEMON_VALUE = 1;

  /**
   * The '<em><b>Orange</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #ORANGE
   * @model name="orange"
   * @generated
   * @ordered
   */
  public static final int ORANGE_VALUE = 2;

  /**
   * The '<em><b>Grapefruit</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GRAPEFRUIT
   * @model name="grapefruit"
   * @generated
   * @ordered
   */
  public static final int GRAPEFRUIT_VALUE = 3;

  /**
   * The '<em><b>Pineapple</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PINEAPPLE
   * @model name="pineapple"
   * @generated
   * @ordered
   */
  public static final int PINEAPPLE_VALUE = 4;

  /**
   * The '<em><b>Mango</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MANGO
   * @model name="mango"
   * @generated
   * @ordered
   */
  public static final int MANGO_VALUE = 5;

  /**
   * The '<em><b>Kiwi</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #KIWI
   * @model name="kiwi"
   * @generated
   * @ordered
   */
  public static final int KIWI_VALUE = 6;

  /**
   * The '<em><b>Strawberry</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #STRAWBERRY
   * @model name="strawberry"
   * @generated
   * @ordered
   */
  public static final int STRAWBERRY_VALUE = 7;

  /**
   * The '<em><b>Blueberry</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BLUEBERRY
   * @model name="blueberry"
   * @generated
   * @ordered
   */
  public static final int BLUEBERRY_VALUE = 8;

  /**
   * The '<em><b>Raspberry</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #RASPBERRY
   * @model name="raspberry"
   * @generated
   * @ordered
   */
  public static final int RASPBERRY_VALUE = 9;

  /**
   * The '<em><b>Blackberry</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BLACKBERRY
   * @model name="blackberry"
   * @generated
   * @ordered
   */
  public static final int BLACKBERRY_VALUE = 10;

  /**
   * The '<em><b>Cherry</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CHERRY
   * @model name="cherry"
   * @generated
   * @ordered
   */
  public static final int CHERRY_VALUE = 11;

  /**
   * The '<em><b>Peach</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PEACH
   * @model name="peach"
   * @generated
   * @ordered
   */
  public static final int PEACH_VALUE = 12;

  /**
   * The '<em><b>Plum</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #PLUM
   * @model name="plum"
   * @generated
   * @ordered
   */
  public static final int PLUM_VALUE = 13;

  /**
   * The '<em><b>Watermelon</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #WATERMELON
   * @model name="watermelon"
   * @generated
   * @ordered
   */
  public static final int WATERMELON_VALUE = 14;

  /**
   * The '<em><b>Cucumber</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CUCUMBER
   * @model name="cucumber"
   * @generated
   * @ordered
   */
  public static final int CUCUMBER_VALUE = 15;

  /**
   * The '<em><b>Mint</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #MINT
   * @model name="mint"
   * @generated
   * @ordered
   */
  public static final int MINT_VALUE = 16;

  /**
   * The '<em><b>Basil</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BASIL
   * @model name="basil"
   * @generated
   * @ordered
   */
  public static final int BASIL_VALUE = 17;

  /**
   * The '<em><b>Thyme</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #THYME
   * @model name="thyme"
   * @generated
   * @ordered
   */
  public static final int THYME_VALUE = 18;

  /**
   * The '<em><b>Ginger</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #GINGER
   * @model name="ginger"
   * @generated
   * @ordered
   */
  public static final int GINGER_VALUE = 19;

  /**
   * An array of all the '<em><b>Fruit Statement</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final FruitStatement[] VALUES_ARRAY =
    new FruitStatement[]
    {
      LIME,
      LEMON,
      ORANGE,
      GRAPEFRUIT,
      PINEAPPLE,
      MANGO,
      KIWI,
      STRAWBERRY,
      BLUEBERRY,
      RASPBERRY,
      BLACKBERRY,
      CHERRY,
      PEACH,
      PLUM,
      WATERMELON,
      CUCUMBER,
      MINT,
      BASIL,
      THYME,
      GINGER,
    };

  /**
   * A public read-only list of all the '<em><b>Fruit Statement</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<FruitStatement> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Fruit Statement</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static FruitStatement get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      FruitStatement result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Fruit Statement</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static FruitStatement getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      FruitStatement result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Fruit Statement</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static FruitStatement get(int value)
  {
    switch (value)
    {
      case LIME_VALUE: return LIME;
      case LEMON_VALUE: return LEMON;
      case ORANGE_VALUE: return ORANGE;
      case GRAPEFRUIT_VALUE: return GRAPEFRUIT;
      case PINEAPPLE_VALUE: return PINEAPPLE;
      case MANGO_VALUE: return MANGO;
      case KIWI_VALUE: return KIWI;
      case STRAWBERRY_VALUE: return STRAWBERRY;
      case BLUEBERRY_VALUE: return BLUEBERRY;
      case RASPBERRY_VALUE: return RASPBERRY;
      case BLACKBERRY_VALUE: return BLACKBERRY;
      case CHERRY_VALUE: return CHERRY;
      case PEACH_VALUE: return PEACH;
      case PLUM_VALUE: return PLUM;
      case WATERMELON_VALUE: return WATERMELON;
      case CUCUMBER_VALUE: return CUCUMBER;
      case MINT_VALUE: return MINT;
      case BASIL_VALUE: return BASIL;
      case THYME_VALUE: return THYME;
      case GINGER_VALUE: return GINGER;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private FruitStatement(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //FruitStatement
