/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.cocktails;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Ice Statement</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#getIceStatement()
 * @model
 * @generated
 */
public enum IceStatement implements Enumerator
{
  /**
   * The '<em><b>Cube</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CUBE_VALUE
   * @generated
   * @ordered
   */
  CUBE(0, "cube", "cube"),

  /**
   * The '<em><b>Crush</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CRUSH_VALUE
   * @generated
   * @ordered
   */
  CRUSH(1, "crush", "crush"),

  /**
   * The '<em><b>Shave</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SHAVE_VALUE
   * @generated
   * @ordered
   */
  SHAVE(2, "shave", "shave"),

  /**
   * The '<em><b>Block</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BLOCK_VALUE
   * @generated
   * @ordered
   */
  BLOCK(3, "block", "block"),

  /**
   * The '<em><b>Ball</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BALL_VALUE
   * @generated
   * @ordered
   */
  BALL(4, "ball", "ball"),

  /**
   * The '<em><b>Cone</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CONE_VALUE
   * @generated
   * @ordered
   */
  CONE(5, "cone", "cone");

  /**
   * The '<em><b>Cube</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CUBE
   * @model name="cube"
   * @generated
   * @ordered
   */
  public static final int CUBE_VALUE = 0;

  /**
   * The '<em><b>Crush</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CRUSH
   * @model name="crush"
   * @generated
   * @ordered
   */
  public static final int CRUSH_VALUE = 1;

  /**
   * The '<em><b>Shave</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SHAVE
   * @model name="shave"
   * @generated
   * @ordered
   */
  public static final int SHAVE_VALUE = 2;

  /**
   * The '<em><b>Block</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BLOCK
   * @model name="block"
   * @generated
   * @ordered
   */
  public static final int BLOCK_VALUE = 3;

  /**
   * The '<em><b>Ball</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BALL
   * @model name="ball"
   * @generated
   * @ordered
   */
  public static final int BALL_VALUE = 4;

  /**
   * The '<em><b>Cone</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #CONE
   * @model name="cone"
   * @generated
   * @ordered
   */
  public static final int CONE_VALUE = 5;

  /**
   * An array of all the '<em><b>Ice Statement</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final IceStatement[] VALUES_ARRAY =
    new IceStatement[]
    {
      CUBE,
      CRUSH,
      SHAVE,
      BLOCK,
      BALL,
      CONE,
    };

  /**
   * A public read-only list of all the '<em><b>Ice Statement</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<IceStatement> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Ice Statement</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static IceStatement get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      IceStatement result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Ice Statement</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static IceStatement getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      IceStatement result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Ice Statement</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static IceStatement get(int value)
  {
    switch (value)
    {
      case CUBE_VALUE: return CUBE;
      case CRUSH_VALUE: return CRUSH;
      case SHAVE_VALUE: return SHAVE;
      case BLOCK_VALUE: return BLOCK;
      case BALL_VALUE: return BALL;
      case CONE_VALUE: return CONE;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private IceStatement(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //IceStatement
