/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.cocktails;

import java.util.Arrays;
import java.util.Collections;
import java.util.List;

import org.eclipse.emf.common.util.Enumerator;

/**
 * <!-- begin-user-doc -->
 * A representation of the literals of the enumeration '<em><b>Make Command</b></em>',
 * and utility methods for working with them.
 * <!-- end-user-doc -->
 * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#getMakeCommand()
 * @model
 * @generated
 */
public enum MakeCommand implements Enumerator
{
  /**
   * The '<em><b>Stir</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #STIR_VALUE
   * @generated
   * @ordered
   */
  STIR(0, "stir", "stir"),

  /**
   * The '<em><b>Shake</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SHAKE_VALUE
   * @generated
   * @ordered
   */
  SHAKE(1, "shake", "shake"),

  /**
   * The '<em><b>Blend</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BLEND_VALUE
   * @generated
   * @ordered
   */
  BLEND(2, "blend", "blend"),

  /**
   * The '<em><b>Filter</b></em>' literal object.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FILTER_VALUE
   * @generated
   * @ordered
   */
  FILTER(3, "filter", "filter");

  /**
   * The '<em><b>Stir</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #STIR
   * @model name="stir"
   * @generated
   * @ordered
   */
  public static final int STIR_VALUE = 0;

  /**
   * The '<em><b>Shake</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #SHAKE
   * @model name="shake"
   * @generated
   * @ordered
   */
  public static final int SHAKE_VALUE = 1;

  /**
   * The '<em><b>Blend</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #BLEND
   * @model name="blend"
   * @generated
   * @ordered
   */
  public static final int BLEND_VALUE = 2;

  /**
   * The '<em><b>Filter</b></em>' literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #FILTER
   * @model name="filter"
   * @generated
   * @ordered
   */
  public static final int FILTER_VALUE = 3;

  /**
   * An array of all the '<em><b>Make Command</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private static final MakeCommand[] VALUES_ARRAY =
    new MakeCommand[]
    {
      STIR,
      SHAKE,
      BLEND,
      FILTER,
    };

  /**
   * A public read-only list of all the '<em><b>Make Command</b></em>' enumerators.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static final List<MakeCommand> VALUES = Collections.unmodifiableList(Arrays.asList(VALUES_ARRAY));

  /**
   * Returns the '<em><b>Make Command</b></em>' literal with the specified literal value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param literal the literal.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static MakeCommand get(String literal)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      MakeCommand result = VALUES_ARRAY[i];
      if (result.toString().equals(literal))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Make Command</b></em>' literal with the specified name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param name the name.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static MakeCommand getByName(String name)
  {
    for (int i = 0; i < VALUES_ARRAY.length; ++i)
    {
      MakeCommand result = VALUES_ARRAY[i];
      if (result.getName().equals(name))
      {
        return result;
      }
    }
    return null;
  }

  /**
   * Returns the '<em><b>Make Command</b></em>' literal with the specified integer value.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the integer value.
   * @return the matching enumerator or <code>null</code>.
   * @generated
   */
  public static MakeCommand get(int value)
  {
    switch (value)
    {
      case STIR_VALUE: return STIR;
      case SHAKE_VALUE: return SHAKE;
      case BLEND_VALUE: return BLEND;
      case FILTER_VALUE: return FILTER;
    }
    return null;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final int value;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String name;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private final String literal;

  /**
   * Only this class can construct instances.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  private MakeCommand(int value, String name, String literal)
  {
    this.value = value;
    this.name = name;
    this.literal = literal;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int getValue()
  {
    return value;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getLiteral()
  {
    return literal;
  }

  /**
   * Returns the literal value of the enumerator, which is its string representation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    return literal;
  }
  
} //MakeCommand
