/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.cocktails;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Make Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.cocktails.MakeStatement#getMake <em>Make</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.cocktails.MakeStatement#getTime <em>Time</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#getMakeStatement()
 * @model
 * @generated
 */
public interface MakeStatement extends Instruction
{
  /**
   * Returns the value of the '<em><b>Make</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.cocktails.MakeCommand}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Make</em>' attribute.
   * @see org.xtext.example.mydsl.cocktails.MakeCommand
   * @see #setMake(MakeCommand)
   * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#getMakeStatement_Make()
   * @model
   * @generated
   */
  MakeCommand getMake();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.cocktails.MakeStatement#getMake <em>Make</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Make</em>' attribute.
   * @see org.xtext.example.mydsl.cocktails.MakeCommand
   * @see #getMake()
   * @generated
   */
  void setMake(MakeCommand value);

  /**
   * Returns the value of the '<em><b>Time</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Time</em>' containment reference.
   * @see #setTime(Expression)
   * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#getMakeStatement_Time()
   * @model containment="true"
   * @generated
   */
  Expression getTime();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.cocktails.MakeStatement#getTime <em>Time</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Time</em>' containment reference.
   * @see #getTime()
   * @generated
   */
  void setTime(Expression value);

} // MakeStatement
