/**
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.cocktails;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Muddle Statement</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.example.mydsl.cocktails.MuddleStatement#getMudFruit <em>Mud Fruit</em>}</li>
 *   <li>{@link org.xtext.example.mydsl.cocktails.MuddleStatement#getMtimes <em>Mtimes</em>}</li>
 * </ul>
 *
 * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#getMuddleStatement()
 * @model
 * @generated
 */
public interface MuddleStatement extends Instruction
{
  /**
   * Returns the value of the '<em><b>Mud Fruit</b></em>' attribute list.
   * The list contents are of type {@link org.xtext.example.mydsl.cocktails.FruitStatement}.
   * The literals are from the enumeration {@link org.xtext.example.mydsl.cocktails.FruitStatement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mud Fruit</em>' attribute list.
   * @see org.xtext.example.mydsl.cocktails.FruitStatement
   * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#getMuddleStatement_MudFruit()
   * @model unique="false"
   * @generated
   */
  EList<FruitStatement> getMudFruit();

  /**
   * Returns the value of the '<em><b>Mtimes</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Mtimes</em>' containment reference.
   * @see #setMtimes(Expression)
   * @see org.xtext.example.mydsl.cocktails.CocktailsPackage#getMuddleStatement_Mtimes()
   * @model containment="true"
   * @generated
   */
  Expression getMtimes();

  /**
   * Sets the value of the '{@link org.xtext.example.mydsl.cocktails.MuddleStatement#getMtimes <em>Mtimes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Mtimes</em>' containment reference.
   * @see #getMtimes()
   * @generated
   */
  void setMtimes(Expression value);

} // MuddleStatement
