/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class CocktailsStandaloneSetup extends CocktailsStandaloneSetupGenerated {

	def static void doSetup() {
		new CocktailsStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
