/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import uk.ac.kcl.inf.group6.cocktail.ui.internal.CocktailActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class CocktailsExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(CocktailActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		CocktailActivator activator = CocktailActivator.getInstance();
		return activator != null ? activator.getInjector(CocktailActivator.ORG_XTEXT_EXAMPLE_MYDSL_COCKTAILS) : null;
	}

}
