/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.serializer;

import com.google.inject.Inject;
import java.util.Set;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;
import org.xtext.example.mydsl.cocktails.AddDecoration;
import org.xtext.example.mydsl.cocktails.AddFixedIngredient;
import org.xtext.example.mydsl.cocktails.AddIce;
import org.xtext.example.mydsl.cocktails.AddIngredient;
import org.xtext.example.mydsl.cocktails.Addition;
import org.xtext.example.mydsl.cocktails.CocktailsPackage;
import org.xtext.example.mydsl.cocktails.FancyStatement;
import org.xtext.example.mydsl.cocktails.IntLiteral;
import org.xtext.example.mydsl.cocktails.IntVarExpression;
import org.xtext.example.mydsl.cocktails.MakeStatement;
import org.xtext.example.mydsl.cocktails.MuddleStatement;
import org.xtext.example.mydsl.cocktails.Multiplication;
import org.xtext.example.mydsl.cocktails.Order;
import org.xtext.example.mydsl.cocktails.VariableDeclaration;
import org.xtext.example.mydsl.services.CocktailsGrammarAccess;

@SuppressWarnings("all")
public class CocktailsSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private CocktailsGrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == CocktailsPackage.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case CocktailsPackage.ADD_DECORATION:
				sequence_AddDecoration(context, (AddDecoration) semanticObject); 
				return; 
			case CocktailsPackage.ADD_FIXED_INGREDIENT:
				sequence_AddFixedIngredient(context, (AddFixedIngredient) semanticObject); 
				return; 
			case CocktailsPackage.ADD_ICE:
				sequence_AddIce(context, (AddIce) semanticObject); 
				return; 
			case CocktailsPackage.ADD_INGREDIENT:
				sequence_AddIngredient(context, (AddIngredient) semanticObject); 
				return; 
			case CocktailsPackage.ADDITION:
				sequence_Addition(context, (Addition) semanticObject); 
				return; 
			case CocktailsPackage.FANCY_STATEMENT:
				sequence_FancyStatement(context, (FancyStatement) semanticObject); 
				return; 
			case CocktailsPackage.INT_LITERAL:
				sequence_IntLiteral(context, (IntLiteral) semanticObject); 
				return; 
			case CocktailsPackage.INT_VAR_EXPRESSION:
				sequence_IntVarExpression(context, (IntVarExpression) semanticObject); 
				return; 
			case CocktailsPackage.MAKE_STATEMENT:
				sequence_MakeStatement(context, (MakeStatement) semanticObject); 
				return; 
			case CocktailsPackage.MUDDLE_STATEMENT:
				sequence_MuddleStatement(context, (MuddleStatement) semanticObject); 
				return; 
			case CocktailsPackage.MULTIPLICATION:
				sequence_Multiplication(context, (Multiplication) semanticObject); 
				return; 
			case CocktailsPackage.ORDER:
				sequence_Order(context, (Order) semanticObject); 
				return; 
			case CocktailsPackage.VARIABLE_DECLARATION:
				sequence_VariableDeclaration(context, (VariableDeclaration) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruction returns AddDecoration
	 *     AddDecoration returns AddDecoration
	 *
	 * Constraint:
	 *     (decoration=DecorationStatement slice=Addition)
	 * </pre>
	 */
	protected void sequence_AddDecoration(ISerializationContext context, AddDecoration semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CocktailsPackage.Literals.ADD_DECORATION__DECORATION) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CocktailsPackage.Literals.ADD_DECORATION__DECORATION));
			if (transientValues.isValueTransient(semanticObject, CocktailsPackage.Literals.ADD_DECORATION__SLICE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CocktailsPackage.Literals.ADD_DECORATION__SLICE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAddDecorationAccess().getDecorationDecorationStatementEnumRuleCall_1_0(), semanticObject.getDecoration());
		feeder.accept(grammarAccess.getAddDecorationAccess().getSliceAdditionParserRuleCall_2_0(), semanticObject.getSlice());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruction returns AddFixedIngredient
	 *     AddFixedIngredient returns AddFixedIngredient
	 *
	 * Constraint:
	 *     (name=ID amount=Addition)
	 * </pre>
	 */
	protected void sequence_AddFixedIngredient(ISerializationContext context, AddFixedIngredient semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CocktailsPackage.Literals.ADD_FIXED_INGREDIENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CocktailsPackage.Literals.ADD_FIXED_INGREDIENT__NAME));
			if (transientValues.isValueTransient(semanticObject, CocktailsPackage.Literals.ADD_FIXED_INGREDIENT__AMOUNT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CocktailsPackage.Literals.ADD_FIXED_INGREDIENT__AMOUNT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAddFixedIngredientAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getAddFixedIngredientAccess().getAmountAdditionParserRuleCall_3_0(), semanticObject.getAmount());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruction returns AddIce
	 *     AddIce returns AddIce
	 *
	 * Constraint:
	 *     (ice=IceStatement ounce=Addition)
	 * </pre>
	 */
	protected void sequence_AddIce(ISerializationContext context, AddIce semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CocktailsPackage.Literals.ADD_ICE__ICE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CocktailsPackage.Literals.ADD_ICE__ICE));
			if (transientValues.isValueTransient(semanticObject, CocktailsPackage.Literals.ADD_ICE__OUNCE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CocktailsPackage.Literals.ADD_ICE__OUNCE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAddIceAccess().getIceIceStatementEnumRuleCall_1_0(), semanticObject.getIce());
		feeder.accept(grammarAccess.getAddIceAccess().getOunceAdditionParserRuleCall_3_0(), semanticObject.getOunce());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruction returns AddIngredient
	 *     AddIngredient returns AddIngredient
	 *
	 * Constraint:
	 *     (name=ID amount=Addition)
	 * </pre>
	 */
	protected void sequence_AddIngredient(ISerializationContext context, AddIngredient semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CocktailsPackage.Literals.ADD_INGREDIENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CocktailsPackage.Literals.ADD_INGREDIENT__NAME));
			if (transientValues.isValueTransient(semanticObject, CocktailsPackage.Literals.ADD_INGREDIENT__AMOUNT) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CocktailsPackage.Literals.ADD_INGREDIENT__AMOUNT));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getAddIngredientAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getAddIngredientAccess().getAmountAdditionParserRuleCall_3_0(), semanticObject.getAmount());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Addition returns Addition
	 *     Addition.Addition_1_0 returns Addition
	 *     Multiplication returns Addition
	 *     Multiplication.Multiplication_1_0 returns Addition
	 *     PrimaryExpression returns Addition
	 *
	 * Constraint:
	 *     (left=Addition_Addition_1_0 (operator+='+' | operator+='-') right+=Multiplication)
	 * </pre>
	 */
	protected void sequence_Addition(ISerializationContext context, Addition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruction returns FancyStatement
	 *     FancyStatement returns FancyStatement
	 *
	 * Constraint:
	 *     fcommand=FancyMakeStatement
	 * </pre>
	 */
	protected void sequence_FancyStatement(ISerializationContext context, FancyStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CocktailsPackage.Literals.FANCY_STATEMENT__FCOMMAND) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CocktailsPackage.Literals.FANCY_STATEMENT__FCOMMAND));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getFancyStatementAccess().getFcommandFancyMakeStatementEnumRuleCall_1_0(), semanticObject.getFcommand());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Addition returns IntLiteral
	 *     Addition.Addition_1_0 returns IntLiteral
	 *     Multiplication returns IntLiteral
	 *     Multiplication.Multiplication_1_0 returns IntLiteral
	 *     PrimaryExpression returns IntLiteral
	 *     IntLiteral returns IntLiteral
	 *
	 * Constraint:
	 *     val=INT
	 * </pre>
	 */
	protected void sequence_IntLiteral(ISerializationContext context, IntLiteral semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CocktailsPackage.Literals.INT_LITERAL__VAL) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CocktailsPackage.Literals.INT_LITERAL__VAL));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIntLiteralAccess().getValINTTerminalRuleCall_0(), semanticObject.getVal());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Addition returns IntVarExpression
	 *     Addition.Addition_1_0 returns IntVarExpression
	 *     Multiplication returns IntVarExpression
	 *     Multiplication.Multiplication_1_0 returns IntVarExpression
	 *     PrimaryExpression returns IntVarExpression
	 *     IntVarExpression returns IntVarExpression
	 *
	 * Constraint:
	 *     var=[VariableDeclaration|ID]
	 * </pre>
	 */
	protected void sequence_IntVarExpression(ISerializationContext context, IntVarExpression semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CocktailsPackage.Literals.INT_VAR_EXPRESSION__VAR) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CocktailsPackage.Literals.INT_VAR_EXPRESSION__VAR));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getIntVarExpressionAccess().getVarVariableDeclarationIDTerminalRuleCall_0_1(), semanticObject.eGet(CocktailsPackage.Literals.INT_VAR_EXPRESSION__VAR, false));
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruction returns MakeStatement
	 *     MakeStatement returns MakeStatement
	 *
	 * Constraint:
	 *     (make=MakeCommand time=Addition)
	 * </pre>
	 */
	protected void sequence_MakeStatement(ISerializationContext context, MakeStatement semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CocktailsPackage.Literals.MAKE_STATEMENT__MAKE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CocktailsPackage.Literals.MAKE_STATEMENT__MAKE));
			if (transientValues.isValueTransient(semanticObject, CocktailsPackage.Literals.MAKE_STATEMENT__TIME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CocktailsPackage.Literals.MAKE_STATEMENT__TIME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getMakeStatementAccess().getMakeMakeCommandEnumRuleCall_0_0(), semanticObject.getMake());
		feeder.accept(grammarAccess.getMakeStatementAccess().getTimeAdditionParserRuleCall_2_0(), semanticObject.getTime());
		feeder.finish();
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruction returns MuddleStatement
	 *     MuddleStatement returns MuddleStatement
	 *
	 * Constraint:
	 *     (mudFruit+=FruitStatement* mtimes=Addition)
	 * </pre>
	 */
	protected void sequence_MuddleStatement(ISerializationContext context, MuddleStatement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Addition returns Multiplication
	 *     Addition.Addition_1_0 returns Multiplication
	 *     Multiplication returns Multiplication
	 *     Multiplication.Multiplication_1_0 returns Multiplication
	 *     PrimaryExpression returns Multiplication
	 *
	 * Constraint:
	 *     (left=Multiplication_Multiplication_1_0 (operator+='*' | operator+='/') right+=PrimaryExpression)
	 * </pre>
	 */
	protected void sequence_Multiplication(ISerializationContext context, Multiplication semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Order returns Order
	 *
	 * Constraint:
	 *     instructions+=Instruction+
	 * </pre>
	 */
	protected void sequence_Order(ISerializationContext context, Order semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * <pre>
	 * Contexts:
	 *     Instruction returns VariableDeclaration
	 *     VariableDeclaration returns VariableDeclaration
	 *
	 * Constraint:
	 *     (name=ID value=INT)
	 * </pre>
	 */
	protected void sequence_VariableDeclaration(ISerializationContext context, VariableDeclaration semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, CocktailsPackage.Literals.VARIABLE_DECLARATION__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CocktailsPackage.Literals.VARIABLE_DECLARATION__NAME));
			if (transientValues.isValueTransient(semanticObject, CocktailsPackage.Literals.VARIABLE_DECLARATION__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, CocktailsPackage.Literals.VARIABLE_DECLARATION__VALUE));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getVariableDeclarationAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getVariableDeclarationAccess().getValueINTTerminalRuleCall_3_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
}
