/*
 * generated by Xtext 2.29.0
 */
package org.xtext.example.mydsl.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.example.mydsl.CocktailsRuntimeModule
import org.xtext.example.mydsl.CocktailsStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class CocktailsIdeSetup extends CocktailsStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new CocktailsRuntimeModule, new CocktailsIdeModule))
	}
	
}
